# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinearReadWrite.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_subLinearReadWrite(object):
    def setupUi(self, subLinearReadWrite):
        subLinearReadWrite.setObjectName("subLinearReadWrite")
        subLinearReadWrite.resize(612, 336)
        self.tabLinearRW = QtWidgets.QTabWidget(subLinearReadWrite)
        self.tabLinearRW.setGeometry(QtCore.QRect(10, 50, 591, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabLinearRW.setFont(font)
        self.tabLinearRW.setObjectName("tabLinearRW")
        self.tbLinearRead = QtWidgets.QWidget()
        self.tbLinearRead.setObjectName("tbLinearRead")
        self.lblLinearRead = QtWidgets.QLabel(self.tbLinearRead)
        self.lblLinearRead.setGeometry(QtCore.QRect(20, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearRead.setFont(font)
        self.lblLinearRead.setObjectName("lblLinearRead")
        self.txtLinearRead = QtWidgets.QTextEdit(self.tbLinearRead)
        self.txtLinearRead.setGeometry(QtCore.QRect(20, 22, 541, 150))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearRead.setFont(font)
        self.txtLinearRead.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearRead.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearRead.setReadOnly(True)
        self.txtLinearRead.setObjectName("txtLinearRead")
        self.lblLinearAdressRead = QtWidgets.QLabel(self.tbLinearRead)
        self.lblLinearAdressRead.setGeometry(QtCore.QRect(20, 183, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressRead.setFont(font)
        self.lblLinearAdressRead.setObjectName("lblLinearAdressRead")
        self.txtLinearAddressRead = QtWidgets.QLineEdit(self.tbLinearRead)
        self.txtLinearAddressRead.setGeometry(QtCore.QRect(130, 182, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressRead.setFont(font)
        self.txtLinearAddressRead.setReadOnly(False)
        self.txtLinearAddressRead.setObjectName("txtLinearAddressRead")
        self.txtDataLengthRead = QtWidgets.QLineEdit(self.tbLinearRead)
        self.txtDataLengthRead.setGeometry(QtCore.QRect(130, 204, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthRead.setFont(font)
        self.txtDataLengthRead.setReadOnly(False)
        self.txtDataLengthRead.setObjectName("txtDataLengthRead")
        self.lblDataLengthRead = QtWidgets.QLabel(self.tbLinearRead)
        self.lblDataLengthRead.setGeometry(QtCore.QRect(20, 205, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthRead.setFont(font)
        self.lblDataLengthRead.setObjectName("lblDataLengthRead")
        self.txtReadBytes = QtWidgets.QLineEdit(self.tbLinearRead)
        self.txtReadBytes.setGeometry(QtCore.QRect(340, 190, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtReadBytes.setFont(font)
        self.txtReadBytes.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtReadBytes.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReadBytes.setReadOnly(True)
        self.txtReadBytes.setObjectName("txtReadBytes")
        self.lblReadBytes = QtWidgets.QLabel(self.tbLinearRead)
        self.lblReadBytes.setGeometry(QtCore.QRect(254, 190, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReadBytes.setFont(font)
        self.lblReadBytes.setObjectName("lblReadBytes")
        self.btnLinearRead = QtWidgets.QPushButton(self.tbLinearRead)
        self.btnLinearRead.setGeometry(QtCore.QRect(410, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearRead.setFont(font)
        self.btnLinearRead.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearRead.setObjectName("btnLinearRead")
        self.tabLinearRW.addTab(self.tbLinearRead, "")
        self.tbLinearReadAKM12 = QtWidgets.QWidget()
        self.tbLinearReadAKM12.setObjectName("tbLinearReadAKM12")
        self.tabLRAKM12 = QtWidgets.QTabWidget(self.tbLinearReadAKM12)
        self.tabLRAKM12.setGeometry(QtCore.QRect(10, 0, 571, 230))
        self.tabLRAKM12.setObjectName("tabLRAKM12")
        self.tabAKM1 = QtWidgets.QWidget()
        self.tabAKM1.setObjectName("tabAKM1")
        self.txtLinearReadAKM1 = QtWidgets.QTextEdit(self.tabAKM1)
        self.txtLinearReadAKM1.setGeometry(QtCore.QRect(10, 22, 541, 120))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearReadAKM1.setFont(font)
        self.txtLinearReadAKM1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearReadAKM1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearReadAKM1.setReadOnly(True)
        self.txtLinearReadAKM1.setObjectName("txtLinearReadAKM1")
        self.lblLinearReadAKM1 = QtWidgets.QLabel(self.tabAKM1)
        self.lblLinearReadAKM1.setGeometry(QtCore.QRect(10, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearReadAKM1.setFont(font)
        self.lblLinearReadAKM1.setObjectName("lblLinearReadAKM1")
        self.lblReadBytesAKM1 = QtWidgets.QLabel(self.tabAKM1)
        self.lblReadBytesAKM1.setGeometry(QtCore.QRect(244, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReadBytesAKM1.setFont(font)
        self.lblReadBytesAKM1.setObjectName("lblReadBytesAKM1")
        self.btnLinearReadAKM1 = QtWidgets.QPushButton(self.tabAKM1)
        self.btnLinearReadAKM1.setGeometry(QtCore.QRect(400, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearReadAKM1.setFont(font)
        self.btnLinearReadAKM1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearReadAKM1.setObjectName("btnLinearReadAKM1")
        self.txtDataLengthReadAKM1 = QtWidgets.QLineEdit(self.tabAKM1)
        self.txtDataLengthReadAKM1.setGeometry(QtCore.QRect(120, 174, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthReadAKM1.setFont(font)
        self.txtDataLengthReadAKM1.setReadOnly(True)
        self.txtDataLengthReadAKM1.setObjectName("txtDataLengthReadAKM1")
        self.txtReadBytesAKM1 = QtWidgets.QLineEdit(self.tabAKM1)
        self.txtReadBytesAKM1.setGeometry(QtCore.QRect(330, 160, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtReadBytesAKM1.setFont(font)
        self.txtReadBytesAKM1.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtReadBytesAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReadBytesAKM1.setReadOnly(True)
        self.txtReadBytesAKM1.setObjectName("txtReadBytesAKM1")
        self.txtLinearAddressReadAKM1 = QtWidgets.QLineEdit(self.tabAKM1)
        self.txtLinearAddressReadAKM1.setGeometry(QtCore.QRect(120, 152, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressReadAKM1.setFont(font)
        self.txtLinearAddressReadAKM1.setReadOnly(True)
        self.txtLinearAddressReadAKM1.setObjectName("txtLinearAddressReadAKM1")
        self.lblLinearAdressReadAKM1 = QtWidgets.QLabel(self.tabAKM1)
        self.lblLinearAdressReadAKM1.setGeometry(QtCore.QRect(10, 153, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressReadAKM1.setFont(font)
        self.lblLinearAdressReadAKM1.setObjectName("lblLinearAdressReadAKM1")
        self.lblDataLengthReadAKM1 = QtWidgets.QLabel(self.tabAKM1)
        self.lblDataLengthReadAKM1.setGeometry(QtCore.QRect(10, 175, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthReadAKM1.setFont(font)
        self.lblDataLengthReadAKM1.setObjectName("lblDataLengthReadAKM1")
        self.tabLRAKM12.addTab(self.tabAKM1, "")
        self.tabAKM2 = QtWidgets.QWidget()
        self.tabAKM2.setObjectName("tabAKM2")
        self.txtLinearReadAKM2 = QtWidgets.QTextEdit(self.tabAKM2)
        self.txtLinearReadAKM2.setGeometry(QtCore.QRect(10, 22, 541, 120))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearReadAKM2.setFont(font)
        self.txtLinearReadAKM2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearReadAKM2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearReadAKM2.setReadOnly(True)
        self.txtLinearReadAKM2.setObjectName("txtLinearReadAKM2")
        self.txtReadBytesAKM2 = QtWidgets.QLineEdit(self.tabAKM2)
        self.txtReadBytesAKM2.setGeometry(QtCore.QRect(330, 160, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtReadBytesAKM2.setFont(font)
        self.txtReadBytesAKM2.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtReadBytesAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReadBytesAKM2.setReadOnly(True)
        self.txtReadBytesAKM2.setObjectName("txtReadBytesAKM2")
        self.lblLinearAdressReadAKM2 = QtWidgets.QLabel(self.tabAKM2)
        self.lblLinearAdressReadAKM2.setGeometry(QtCore.QRect(10, 153, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressReadAKM2.setFont(font)
        self.lblLinearAdressReadAKM2.setObjectName("lblLinearAdressReadAKM2")
        self.lblLinearReadAKM2 = QtWidgets.QLabel(self.tabAKM2)
        self.lblLinearReadAKM2.setGeometry(QtCore.QRect(10, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearReadAKM2.setFont(font)
        self.lblLinearReadAKM2.setObjectName("lblLinearReadAKM2")
        self.lblDataLengthReadAKM2 = QtWidgets.QLabel(self.tabAKM2)
        self.lblDataLengthReadAKM2.setGeometry(QtCore.QRect(10, 175, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthReadAKM2.setFont(font)
        self.lblDataLengthReadAKM2.setObjectName("lblDataLengthReadAKM2")
        self.btnLinearReadAKM2 = QtWidgets.QPushButton(self.tabAKM2)
        self.btnLinearReadAKM2.setGeometry(QtCore.QRect(400, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearReadAKM2.setFont(font)
        self.btnLinearReadAKM2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearReadAKM2.setObjectName("btnLinearReadAKM2")
        self.txtLinearAddressReadAKM2 = QtWidgets.QLineEdit(self.tabAKM2)
        self.txtLinearAddressReadAKM2.setGeometry(QtCore.QRect(120, 152, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressReadAKM2.setFont(font)
        self.txtLinearAddressReadAKM2.setReadOnly(False)
        self.txtLinearAddressReadAKM2.setObjectName("txtLinearAddressReadAKM2")
        self.lblReadBytesAKM2 = QtWidgets.QLabel(self.tabAKM2)
        self.lblReadBytesAKM2.setGeometry(QtCore.QRect(244, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReadBytesAKM2.setFont(font)
        self.lblReadBytesAKM2.setObjectName("lblReadBytesAKM2")
        self.txtDataLengthReadAKM2 = QtWidgets.QLineEdit(self.tabAKM2)
        self.txtDataLengthReadAKM2.setGeometry(QtCore.QRect(120, 174, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthReadAKM2.setFont(font)
        self.txtDataLengthReadAKM2.setReadOnly(False)
        self.txtDataLengthReadAKM2.setObjectName("txtDataLengthReadAKM2")
        self.tabLRAKM12.addTab(self.tabAKM2, "")
        self.tabLinearRW.addTab(self.tbLinearReadAKM12, "")
        self.tbLinearReadPK = QtWidgets.QWidget()
        self.tbLinearReadPK.setObjectName("tbLinearReadPK")
        self.lblReadBytesPK = QtWidgets.QLabel(self.tbLinearReadPK)
        self.lblReadBytesPK.setGeometry(QtCore.QRect(255, 189, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReadBytesPK.setFont(font)
        self.lblReadBytesPK.setObjectName("lblReadBytesPK")
        self.btnLinearReadPK = QtWidgets.QPushButton(self.tbLinearReadPK)
        self.btnLinearReadPK.setGeometry(QtCore.QRect(411, 179, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearReadPK.setFont(font)
        self.btnLinearReadPK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearReadPK.setObjectName("btnLinearReadPK")
        self.txtDataLengthReadPK = QtWidgets.QLineEdit(self.tbLinearReadPK)
        self.txtDataLengthReadPK.setGeometry(QtCore.QRect(131, 203, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthReadPK.setFont(font)
        self.txtDataLengthReadPK.setReadOnly(False)
        self.txtDataLengthReadPK.setObjectName("txtDataLengthReadPK")
        self.txtLinearReadPK = QtWidgets.QTextEdit(self.tbLinearReadPK)
        self.txtLinearReadPK.setGeometry(QtCore.QRect(21, 21, 541, 150))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearReadPK.setFont(font)
        self.txtLinearReadPK.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearReadPK.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearReadPK.setReadOnly(True)
        self.txtLinearReadPK.setObjectName("txtLinearReadPK")
        self.txtReadBytesPK = QtWidgets.QLineEdit(self.tbLinearReadPK)
        self.txtReadBytesPK.setGeometry(QtCore.QRect(341, 189, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtReadBytesPK.setFont(font)
        self.txtReadBytesPK.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtReadBytesPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReadBytesPK.setReadOnly(True)
        self.txtReadBytesPK.setObjectName("txtReadBytesPK")
        self.txtLinearAddressReadPK = QtWidgets.QLineEdit(self.tbLinearReadPK)
        self.txtLinearAddressReadPK.setGeometry(QtCore.QRect(131, 181, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressReadPK.setFont(font)
        self.txtLinearAddressReadPK.setReadOnly(False)
        self.txtLinearAddressReadPK.setObjectName("txtLinearAddressReadPK")
        self.lblLinearReadPK = QtWidgets.QLabel(self.tbLinearReadPK)
        self.lblLinearReadPK.setGeometry(QtCore.QRect(21, 4, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearReadPK.setFont(font)
        self.lblLinearReadPK.setObjectName("lblLinearReadPK")
        self.lblLinearAdressReadPK = QtWidgets.QLabel(self.tbLinearReadPK)
        self.lblLinearAdressReadPK.setGeometry(QtCore.QRect(21, 182, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressReadPK.setFont(font)
        self.lblLinearAdressReadPK.setObjectName("lblLinearAdressReadPK")
        self.lblDataLengthReadPK = QtWidgets.QLabel(self.tbLinearReadPK)
        self.lblDataLengthReadPK.setGeometry(QtCore.QRect(21, 204, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthReadPK.setFont(font)
        self.lblDataLengthReadPK.setObjectName("lblDataLengthReadPK")
        self.tabLinearRW.addTab(self.tbLinearReadPK, "")
        self.tbLinearWrite = QtWidgets.QWidget()
        self.tbLinearWrite.setObjectName("tbLinearWrite")
        self.txtLinearAddressWrite = QtWidgets.QLineEdit(self.tbLinearWrite)
        self.txtLinearAddressWrite.setGeometry(QtCore.QRect(130, 182, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressWrite.setFont(font)
        self.txtLinearAddressWrite.setReadOnly(False)
        self.txtLinearAddressWrite.setObjectName("txtLinearAddressWrite")
        self.lblLinearAdressWrite = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblLinearAdressWrite.setGeometry(QtCore.QRect(20, 183, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressWrite.setFont(font)
        self.lblLinearAdressWrite.setObjectName("lblLinearAdressWrite")
        self.lblDataLengthWrite = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblDataLengthWrite.setGeometry(QtCore.QRect(20, 205, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthWrite.setFont(font)
        self.lblDataLengthWrite.setObjectName("lblDataLengthWrite")
        self.lblLinearWrite = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblLinearWrite.setGeometry(QtCore.QRect(20, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearWrite.setFont(font)
        self.lblLinearWrite.setObjectName("lblLinearWrite")
        self.lblBytesWritten = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblBytesWritten.setGeometry(QtCore.QRect(252, 190, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblBytesWritten.setFont(font)
        self.lblBytesWritten.setObjectName("lblBytesWritten")
        self.txtBytesWritten = QtWidgets.QLineEdit(self.tbLinearWrite)
        self.txtBytesWritten.setGeometry(QtCore.QRect(341, 190, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtBytesWritten.setFont(font)
        self.txtBytesWritten.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtBytesWritten.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBytesWritten.setReadOnly(True)
        self.txtBytesWritten.setObjectName("txtBytesWritten")
        self.txtDataLengthWrite = QtWidgets.QLineEdit(self.tbLinearWrite)
        self.txtDataLengthWrite.setGeometry(QtCore.QRect(130, 204, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthWrite.setFont(font)
        self.txtDataLengthWrite.setReadOnly(False)
        self.txtDataLengthWrite.setObjectName("txtDataLengthWrite")
        self.txtLinearWrite = QtWidgets.QTextEdit(self.tbLinearWrite)
        self.txtLinearWrite.setGeometry(QtCore.QRect(20, 22, 541, 150))
        self.txtLinearWrite.setAutoFillBackground(True)
        self.txtLinearWrite.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearWrite.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearWrite.setTabChangesFocus(True)
        self.txtLinearWrite.setReadOnly(False)
        self.txtLinearWrite.setObjectName("txtLinearWrite")
        self.btnLinearWrite = QtWidgets.QPushButton(self.tbLinearWrite)
        self.btnLinearWrite.setGeometry(QtCore.QRect(410, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearWrite.setFont(font)
        self.btnLinearWrite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearWrite.setObjectName("btnLinearWrite")
        self.tabLinearRW.addTab(self.tbLinearWrite, "")
        self.tbLinearWriteAKM12 = QtWidgets.QWidget()
        self.tbLinearWriteAKM12.setObjectName("tbLinearWriteAKM12")
        self.tabLWAKM12 = QtWidgets.QTabWidget(self.tbLinearWriteAKM12)
        self.tabLWAKM12.setGeometry(QtCore.QRect(10, 0, 571, 230))
        self.tabLWAKM12.setObjectName("tabLWAKM12")
        self.tabLWAKM1 = QtWidgets.QWidget()
        self.tabLWAKM1.setObjectName("tabLWAKM1")
        self.txtLinearWriteAKM1 = QtWidgets.QTextEdit(self.tabLWAKM1)
        self.txtLinearWriteAKM1.setGeometry(QtCore.QRect(10, 22, 541, 120))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearWriteAKM1.setFont(font)
        self.txtLinearWriteAKM1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearWriteAKM1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearWriteAKM1.setTabChangesFocus(True)
        self.txtLinearWriteAKM1.setReadOnly(False)
        self.txtLinearWriteAKM1.setObjectName("txtLinearWriteAKM1")
        self.lblLinearWriteAKM1 = QtWidgets.QLabel(self.tabLWAKM1)
        self.lblLinearWriteAKM1.setGeometry(QtCore.QRect(10, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearWriteAKM1.setFont(font)
        self.lblLinearWriteAKM1.setObjectName("lblLinearWriteAKM1")
        self.lblBytesWrittenAKM1 = QtWidgets.QLabel(self.tabLWAKM1)
        self.lblBytesWrittenAKM1.setGeometry(QtCore.QRect(244, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblBytesWrittenAKM1.setFont(font)
        self.lblBytesWrittenAKM1.setObjectName("lblBytesWrittenAKM1")
        self.btnLinearWriteAKM1 = QtWidgets.QPushButton(self.tabLWAKM1)
        self.btnLinearWriteAKM1.setGeometry(QtCore.QRect(400, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearWriteAKM1.setFont(font)
        self.btnLinearWriteAKM1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearWriteAKM1.setObjectName("btnLinearWriteAKM1")
        self.txtDataLengthWriteAKM1 = QtWidgets.QLineEdit(self.tabLWAKM1)
        self.txtDataLengthWriteAKM1.setGeometry(QtCore.QRect(120, 174, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthWriteAKM1.setFont(font)
        self.txtDataLengthWriteAKM1.setReadOnly(False)
        self.txtDataLengthWriteAKM1.setObjectName("txtDataLengthWriteAKM1")
        self.txtBytesWrittenAKM1 = QtWidgets.QLineEdit(self.tabLWAKM1)
        self.txtBytesWrittenAKM1.setGeometry(QtCore.QRect(330, 160, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtBytesWrittenAKM1.setFont(font)
        self.txtBytesWrittenAKM1.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtBytesWrittenAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBytesWrittenAKM1.setReadOnly(True)
        self.txtBytesWrittenAKM1.setObjectName("txtBytesWrittenAKM1")
        self.txtLinearAddressWriteAKM1 = QtWidgets.QLineEdit(self.tabLWAKM1)
        self.txtLinearAddressWriteAKM1.setGeometry(QtCore.QRect(120, 152, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressWriteAKM1.setFont(font)
        self.txtLinearAddressWriteAKM1.setReadOnly(False)
        self.txtLinearAddressWriteAKM1.setObjectName("txtLinearAddressWriteAKM1")
        self.lblLinearAdressWriteAKM1 = QtWidgets.QLabel(self.tabLWAKM1)
        self.lblLinearAdressWriteAKM1.setGeometry(QtCore.QRect(10, 153, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressWriteAKM1.setFont(font)
        self.lblLinearAdressWriteAKM1.setObjectName("lblLinearAdressWriteAKM1")
        self.lblDataLengthWriteAKM1 = QtWidgets.QLabel(self.tabLWAKM1)
        self.lblDataLengthWriteAKM1.setGeometry(QtCore.QRect(10, 175, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthWriteAKM1.setFont(font)
        self.lblDataLengthWriteAKM1.setObjectName("lblDataLengthWriteAKM1")
        self.tabLWAKM12.addTab(self.tabLWAKM1, "")
        self.tabAKM2_2 = QtWidgets.QWidget()
        self.tabAKM2_2.setObjectName("tabAKM2_2")
        self.txtLinearWriteAKM2 = QtWidgets.QTextEdit(self.tabAKM2_2)
        self.txtLinearWriteAKM2.setGeometry(QtCore.QRect(10, 22, 541, 120))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearWriteAKM2.setFont(font)
        self.txtLinearWriteAKM2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearWriteAKM2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearWriteAKM2.setTabChangesFocus(True)
        self.txtLinearWriteAKM2.setReadOnly(False)
        self.txtLinearWriteAKM2.setObjectName("txtLinearWriteAKM2")
        self.txtBytesWrittenAKM2 = QtWidgets.QLineEdit(self.tabAKM2_2)
        self.txtBytesWrittenAKM2.setGeometry(QtCore.QRect(330, 160, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtBytesWrittenAKM2.setFont(font)
        self.txtBytesWrittenAKM2.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtBytesWrittenAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBytesWrittenAKM2.setReadOnly(True)
        self.txtBytesWrittenAKM2.setObjectName("txtBytesWrittenAKM2")
        self.lblLinearAdressWriteAKM2 = QtWidgets.QLabel(self.tabAKM2_2)
        self.lblLinearAdressWriteAKM2.setGeometry(QtCore.QRect(10, 153, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressWriteAKM2.setFont(font)
        self.lblLinearAdressWriteAKM2.setObjectName("lblLinearAdressWriteAKM2")
        self.lblLinearWriteAKM2 = QtWidgets.QLabel(self.tabAKM2_2)
        self.lblLinearWriteAKM2.setGeometry(QtCore.QRect(10, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearWriteAKM2.setFont(font)
        self.lblLinearWriteAKM2.setObjectName("lblLinearWriteAKM2")
        self.lblDataLengthWriteAKM2 = QtWidgets.QLabel(self.tabAKM2_2)
        self.lblDataLengthWriteAKM2.setGeometry(QtCore.QRect(10, 175, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthWriteAKM2.setFont(font)
        self.lblDataLengthWriteAKM2.setObjectName("lblDataLengthWriteAKM2")
        self.btnLinearWriteAKM2 = QtWidgets.QPushButton(self.tabAKM2_2)
        self.btnLinearWriteAKM2.setGeometry(QtCore.QRect(400, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearWriteAKM2.setFont(font)
        self.btnLinearWriteAKM2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearWriteAKM2.setObjectName("btnLinearWriteAKM2")
        self.txtLinearAddressWriteAKM2 = QtWidgets.QLineEdit(self.tabAKM2_2)
        self.txtLinearAddressWriteAKM2.setGeometry(QtCore.QRect(120, 152, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressWriteAKM2.setFont(font)
        self.txtLinearAddressWriteAKM2.setReadOnly(False)
        self.txtLinearAddressWriteAKM2.setObjectName("txtLinearAddressWriteAKM2")
        self.lblBytesWrittenAKM2 = QtWidgets.QLabel(self.tabAKM2_2)
        self.lblBytesWrittenAKM2.setGeometry(QtCore.QRect(244, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblBytesWrittenAKM2.setFont(font)
        self.lblBytesWrittenAKM2.setObjectName("lblBytesWrittenAKM2")
        self.txtDataLengthWriteAKM2 = QtWidgets.QLineEdit(self.tabAKM2_2)
        self.txtDataLengthWriteAKM2.setGeometry(QtCore.QRect(120, 174, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthWriteAKM2.setFont(font)
        self.txtDataLengthWriteAKM2.setReadOnly(False)
        self.txtDataLengthWriteAKM2.setObjectName("txtDataLengthWriteAKM2")
        self.tabLWAKM12.addTab(self.tabAKM2_2, "")
        self.tabLinearRW.addTab(self.tbLinearWriteAKM12, "")
        self.tbLinearWritePK = QtWidgets.QWidget()
        self.tbLinearWritePK.setObjectName("tbLinearWritePK")
        self.txtLinearAddressWritePK = QtWidgets.QLineEdit(self.tbLinearWritePK)
        self.txtLinearAddressWritePK.setGeometry(QtCore.QRect(129, 181, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressWritePK.setFont(font)
        self.txtLinearAddressWritePK.setReadOnly(False)
        self.txtLinearAddressWritePK.setObjectName("txtLinearAddressWritePK")
        self.txtDataLengthWritePK = QtWidgets.QLineEdit(self.tbLinearWritePK)
        self.txtDataLengthWritePK.setGeometry(QtCore.QRect(129, 203, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthWritePK.setFont(font)
        self.txtDataLengthWritePK.setReadOnly(False)
        self.txtDataLengthWritePK.setObjectName("txtDataLengthWritePK")
        self.txtBytesWrittenPK = QtWidgets.QLineEdit(self.tbLinearWritePK)
        self.txtBytesWrittenPK.setGeometry(QtCore.QRect(340, 189, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtBytesWrittenPK.setFont(font)
        self.txtBytesWrittenPK.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtBytesWrittenPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBytesWrittenPK.setReadOnly(True)
        self.txtBytesWrittenPK.setObjectName("txtBytesWrittenPK")
        self.lblLinearAdressWritePK = QtWidgets.QLabel(self.tbLinearWritePK)
        self.lblLinearAdressWritePK.setGeometry(QtCore.QRect(19, 182, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressWritePK.setFont(font)
        self.lblLinearAdressWritePK.setObjectName("lblLinearAdressWritePK")
        self.txtLinearWritePK = QtWidgets.QTextEdit(self.tbLinearWritePK)
        self.txtLinearWritePK.setGeometry(QtCore.QRect(19, 21, 541, 150))
        self.txtLinearWritePK.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearWritePK.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearWritePK.setTabChangesFocus(True)
        self.txtLinearWritePK.setReadOnly(False)
        self.txtLinearWritePK.setObjectName("txtLinearWritePK")
        self.btnLinearWritePK = QtWidgets.QPushButton(self.tbLinearWritePK)
        self.btnLinearWritePK.setGeometry(QtCore.QRect(409, 179, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearWritePK.setFont(font)
        self.btnLinearWritePK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearWritePK.setObjectName("btnLinearWritePK")
        self.lblLinearWritePK = QtWidgets.QLabel(self.tbLinearWritePK)
        self.lblLinearWritePK.setGeometry(QtCore.QRect(19, 4, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearWritePK.setFont(font)
        self.lblLinearWritePK.setObjectName("lblLinearWritePK")
        self.lblDataLengthWritePK = QtWidgets.QLabel(self.tbLinearWritePK)
        self.lblDataLengthWritePK.setGeometry(QtCore.QRect(19, 204, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthWritePK.setFont(font)
        self.lblDataLengthWritePK.setObjectName("lblDataLengthWritePK")
        self.lblBytesWrittenPK = QtWidgets.QLabel(self.tbLinearWritePK)
        self.lblBytesWrittenPK.setGeometry(QtCore.QRect(251, 189, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblBytesWrittenPK.setFont(font)
        self.lblBytesWrittenPK.setObjectName("lblBytesWrittenPK")
        self.tabLinearRW.addTab(self.tbLinearWritePK, "")
        self.lblFnError = QtWidgets.QLabel(subLinearReadWrite)
        self.lblFnError.setGeometry(QtCore.QRect(1, 316, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnValue = QtWidgets.QLabel(subLinearReadWrite)
        self.lblFnValue.setGeometry(QtCore.QRect(111, 316, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnExplain = QtWidgets.QLabel(subLinearReadWrite)
        self.lblFnExplain.setGeometry(QtCore.QRect(192, 316, 420, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.pnlAuth = QtWidgets.QFrame(subLinearReadWrite)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 1, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(263, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setCurrentText("")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")

        self.retranslateUi(subLinearReadWrite)
        self.tabLinearRW.setCurrentIndex(0)
        self.tabLRAKM12.setCurrentIndex(0)
        self.tabLWAKM12.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(subLinearReadWrite)
        subLinearReadWrite.setTabOrder(self.tabLinearRW, self.rbAUTH1A)
        subLinearReadWrite.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        subLinearReadWrite.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        subLinearReadWrite.setTabOrder(self.cboKeyIndex, self.txtLinearRead)
        subLinearReadWrite.setTabOrder(self.txtLinearRead, self.txtLinearAddressRead)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressRead, self.txtDataLengthRead)
        subLinearReadWrite.setTabOrder(self.txtDataLengthRead, self.txtReadBytes)
        subLinearReadWrite.setTabOrder(self.txtReadBytes, self.btnLinearRead)
        subLinearReadWrite.setTabOrder(self.btnLinearRead, self.tabLRAKM12)
        subLinearReadWrite.setTabOrder(self.tabLRAKM12, self.txtLinearAddressReadAKM1)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressReadAKM1, self.txtDataLengthReadAKM1)
        subLinearReadWrite.setTabOrder(self.txtDataLengthReadAKM1, self.btnLinearReadAKM1)
        subLinearReadWrite.setTabOrder(self.btnLinearReadAKM1, self.txtLinearReadAKM1)
        subLinearReadWrite.setTabOrder(self.txtLinearReadAKM1, self.txtReadBytesAKM1)
        subLinearReadWrite.setTabOrder(self.txtReadBytesAKM1, self.txtLinearReadAKM2)
        subLinearReadWrite.setTabOrder(self.txtLinearReadAKM2, self.txtLinearAddressReadAKM2)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressReadAKM2, self.txtDataLengthReadAKM2)
        subLinearReadWrite.setTabOrder(self.txtDataLengthReadAKM2, self.btnLinearReadAKM2)
        subLinearReadWrite.setTabOrder(self.btnLinearReadAKM2, self.txtReadBytesAKM2)
        subLinearReadWrite.setTabOrder(self.txtReadBytesAKM2, self.txtLinearAddressReadPK)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressReadPK, self.txtDataLengthReadPK)
        subLinearReadWrite.setTabOrder(self.txtDataLengthReadPK, self.btnLinearReadPK)
        subLinearReadWrite.setTabOrder(self.btnLinearReadPK, self.txtLinearReadPK)
        subLinearReadWrite.setTabOrder(self.txtLinearReadPK, self.txtReadBytesPK)
        subLinearReadWrite.setTabOrder(self.txtReadBytesPK, self.tabLWAKM12)
        subLinearReadWrite.setTabOrder(self.tabLWAKM12, self.txtLinearWrite)
        subLinearReadWrite.setTabOrder(self.txtLinearWrite, self.txtLinearAddressWrite)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressWrite, self.txtDataLengthWrite)
        subLinearReadWrite.setTabOrder(self.txtDataLengthWrite, self.btnLinearWrite)
        subLinearReadWrite.setTabOrder(self.btnLinearWrite, self.txtBytesWritten)
        subLinearReadWrite.setTabOrder(self.txtBytesWritten, self.txtLinearWriteAKM1)
        subLinearReadWrite.setTabOrder(self.txtLinearWriteAKM1, self.txtLinearAddressWriteAKM1)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressWriteAKM1, self.txtDataLengthWriteAKM1)
        subLinearReadWrite.setTabOrder(self.txtDataLengthWriteAKM1, self.txtBytesWrittenAKM1)
        subLinearReadWrite.setTabOrder(self.txtBytesWrittenAKM1, self.btnLinearWriteAKM1)
        subLinearReadWrite.setTabOrder(self.btnLinearWriteAKM1, self.txtLinearWriteAKM2)
        subLinearReadWrite.setTabOrder(self.txtLinearWriteAKM2, self.txtLinearAddressWriteAKM2)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressWriteAKM2, self.txtDataLengthWriteAKM2)
        subLinearReadWrite.setTabOrder(self.txtDataLengthWriteAKM2, self.txtBytesWrittenAKM2)
        subLinearReadWrite.setTabOrder(self.txtBytesWrittenAKM2, self.btnLinearWriteAKM2)
        subLinearReadWrite.setTabOrder(self.btnLinearWriteAKM2, self.txtLinearWritePK)
        subLinearReadWrite.setTabOrder(self.txtLinearWritePK, self.txtLinearAddressWritePK)
        subLinearReadWrite.setTabOrder(self.txtLinearAddressWritePK, self.txtDataLengthWritePK)
        subLinearReadWrite.setTabOrder(self.txtDataLengthWritePK, self.btnLinearWritePK)
        subLinearReadWrite.setTabOrder(self.btnLinearWritePK, self.txtBytesWrittenPK)

    def retranslateUi(self, subLinearReadWrite):
        _translate = QtCore.QCoreApplication.translate
        subLinearReadWrite.setWindowTitle(_translate("subLinearReadWrite", "Dialog"))
        self.lblLinearRead.setText(_translate("subLinearReadWrite", "Linear Read"))
        self.lblLinearAdressRead.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblDataLengthRead.setText(_translate("subLinearReadWrite", "Data Length"))
        self.lblReadBytes.setText(_translate("subLinearReadWrite", "Read Bytes"))
        self.btnLinearRead.setText(_translate("subLinearReadWrite", "LINEAR READ"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearRead), _translate("subLinearReadWrite", "Linear Read"))
        self.lblLinearReadAKM1.setText(_translate("subLinearReadWrite", "Linear Read"))
        self.lblReadBytesAKM1.setText(_translate("subLinearReadWrite", "Read Bytes"))
        self.btnLinearReadAKM1.setText(_translate("subLinearReadWrite", "LINEAR READ AKM1"))
        self.lblLinearAdressReadAKM1.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblDataLengthReadAKM1.setText(_translate("subLinearReadWrite", "Data Length"))
        self.tabLRAKM12.setTabText(self.tabLRAKM12.indexOf(self.tabAKM1), _translate("subLinearReadWrite", "Linear Read AKM1"))
        self.lblLinearAdressReadAKM2.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblLinearReadAKM2.setText(_translate("subLinearReadWrite", "Linear Read"))
        self.lblDataLengthReadAKM2.setText(_translate("subLinearReadWrite", "Data Length"))
        self.btnLinearReadAKM2.setText(_translate("subLinearReadWrite", "LINEAR READ AKM2"))
        self.lblReadBytesAKM2.setText(_translate("subLinearReadWrite", "Read Bytes"))
        self.tabLRAKM12.setTabText(self.tabLRAKM12.indexOf(self.tabAKM2), _translate("subLinearReadWrite", "Linear Read AKM2"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearReadAKM12), _translate("subLinearReadWrite", "Linear Read (AKM1 / AKM2)"))
        self.lblReadBytesPK.setText(_translate("subLinearReadWrite", "Read Bytes"))
        self.btnLinearReadPK.setText(_translate("subLinearReadWrite", "LINEAR READ PK"))
        self.lblLinearReadPK.setText(_translate("subLinearReadWrite", "Linear Read"))
        self.lblLinearAdressReadPK.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblDataLengthReadPK.setText(_translate("subLinearReadWrite", "Data Length"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearReadPK), _translate("subLinearReadWrite", "Linear Read PK"))
        self.lblLinearAdressWrite.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblDataLengthWrite.setText(_translate("subLinearReadWrite", "Data Length"))
        self.lblLinearWrite.setText(_translate("subLinearReadWrite", "Linear Write"))
        self.lblBytesWritten.setText(_translate("subLinearReadWrite", "Bytes Written"))
        self.btnLinearWrite.setText(_translate("subLinearReadWrite", "LINEAR WRITE"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearWrite), _translate("subLinearReadWrite", "Linear Write"))
        self.lblLinearWriteAKM1.setText(_translate("subLinearReadWrite", "Linear Write"))
        self.lblBytesWrittenAKM1.setText(_translate("subLinearReadWrite", "Bytes Written"))
        self.btnLinearWriteAKM1.setText(_translate("subLinearReadWrite", "LINEAR WRITE AKM1"))
        self.lblLinearAdressWriteAKM1.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblDataLengthWriteAKM1.setText(_translate("subLinearReadWrite", "Data Length"))
        self.tabLWAKM12.setTabText(self.tabLWAKM12.indexOf(self.tabLWAKM1), _translate("subLinearReadWrite", "Linear Write AKM1"))
        self.lblLinearAdressWriteAKM2.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.lblLinearWriteAKM2.setText(_translate("subLinearReadWrite", "Linear Write"))
        self.lblDataLengthWriteAKM2.setText(_translate("subLinearReadWrite", "Data Length"))
        self.btnLinearWriteAKM2.setText(_translate("subLinearReadWrite", "LINEAR WRITE AKM2"))
        self.lblBytesWrittenAKM2.setText(_translate("subLinearReadWrite", "Bytes Written"))
        self.tabLWAKM12.setTabText(self.tabLWAKM12.indexOf(self.tabAKM2_2), _translate("subLinearReadWrite", "Linear Write AKM2"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearWriteAKM12), _translate("subLinearReadWrite", "Linear Write (AKM1/AKM2)"))
        self.lblLinearAdressWritePK.setText(_translate("subLinearReadWrite", "Linear Address"))
        self.btnLinearWritePK.setText(_translate("subLinearReadWrite", "LINEAR WRITE PK"))
        self.lblLinearWritePK.setText(_translate("subLinearReadWrite", "Linear Write"))
        self.lblDataLengthWritePK.setText(_translate("subLinearReadWrite", "Data Length"))
        self.lblBytesWrittenPK.setText(_translate("subLinearReadWrite", "Bytes Written"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearWritePK), _translate("subLinearReadWrite", "Linear Write PK"))
        self.lblFnError.setText(_translate("subLinearReadWrite", "Function Error :"))
        self.rbAUTH1A.setText(_translate("subLinearReadWrite", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("subLinearReadWrite", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("subLinearReadWrite", "Key Index"))
        self.lblPKKeys.setText(_translate("subLinearReadWrite", "PK Key"))

