# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uFSimpleForm.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 663)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(36, 77, 471, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lblReaderType = QtWidgets.QLabel(self.centralwidget)
        self.lblReaderType.setGeometry(QtCore.QRect(36, 35, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReaderType.setFont(font)
        self.lblReaderType.setObjectName("lblReaderType")
        self.txtReaderType = QtWidgets.QLineEdit(self.centralwidget)
        self.txtReaderType.setGeometry(QtCore.QRect(127, 32, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderType.setFont(font)
        self.txtReaderType.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderType.setReadOnly(True)
        self.txtReaderType.setObjectName("txtReaderType")
        self.txtReaderSerial = QtWidgets.QLineEdit(self.centralwidget)
        self.txtReaderSerial.setGeometry(QtCore.QRect(127, 54, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderSerial.setFont(font)
        self.txtReaderSerial.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderSerial.setReadOnly(True)
        self.txtReaderSerial.setObjectName("txtReaderSerial")
        self.lblReaderSerial = QtWidgets.QLabel(self.centralwidget)
        self.lblReaderSerial.setGeometry(QtCore.QRect(36, 57, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReaderSerial.setFont(font)
        self.lblReaderSerial.setObjectName("lblReaderSerial")
        self.lblCardType = QtWidgets.QLabel(self.centralwidget)
        self.lblCardType.setGeometry(QtCore.QRect(256, 35, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblCardType.setFont(font)
        self.lblCardType.setObjectName("lblCardType")
        self.txtCardType = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCardType.setGeometry(QtCore.QRect(336, 32, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardType.setFont(font)
        self.txtCardType.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardType.setReadOnly(True)
        self.txtCardType.setObjectName("txtCardType")
        self.lblUIDSize = QtWidgets.QLabel(self.centralwidget)
        self.lblUIDSize.setGeometry(QtCore.QRect(394, 35, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblUIDSize.setFont(font)
        self.lblUIDSize.setObjectName("lblUIDSize")
        self.txtUIDSize = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUIDSize.setGeometry(QtCore.QRect(455, 32, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtUIDSize.setFont(font)
        self.txtUIDSize.setAlignment(QtCore.Qt.AlignCenter)
        self.txtUIDSize.setReadOnly(True)
        self.txtUIDSize.setObjectName("txtUIDSize")
        self.lblCardSerial = QtWidgets.QLabel(self.centralwidget)
        self.lblCardSerial.setGeometry(QtCore.QRect(256, 57, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblCardSerial.setFont(font)
        self.lblCardSerial.setObjectName("lblCardSerial")
        self.txtCardSerial = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCardSerial.setGeometry(QtCore.QRect(336, 54, 170, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardSerial.setFont(font)
        self.txtCardSerial.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardSerial.setReadOnly(True)
        self.txtCardSerial.setObjectName("txtCardSerial")
        self.lblLightMode = QtWidgets.QLabel(self.centralwidget)
        self.lblLightMode.setGeometry(QtCore.QRect(38, 101, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLightMode.setFont(font)
        self.lblLightMode.setObjectName("lblLightMode")
        self.lblSoundMode = QtWidgets.QLabel(self.centralwidget)
        self.lblSoundMode.setGeometry(QtCore.QRect(38, 125, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblSoundMode.setFont(font)
        self.lblSoundMode.setObjectName("lblSoundMode")
        self.cboLightMode = QtWidgets.QComboBox(self.centralwidget)
        self.cboLightMode.setGeometry(QtCore.QRect(128, 97, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.cboLightMode.setFont(font)
        self.cboLightMode.setObjectName("cboLightMode")
        self.cboLightMode.addItem("")
        self.cboLightMode.addItem("")
        self.cboLightMode.addItem("")
        self.cboLightMode.addItem("")
        self.cboLightMode.addItem("")
        self.cboSoundMode = QtWidgets.QComboBox(self.centralwidget)
        self.cboSoundMode.setGeometry(QtCore.QRect(128, 123, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.cboSoundMode.setFont(font)
        self.cboSoundMode.setObjectName("cboSoundMode")
        self.cboSoundMode.addItem("")
        self.cboSoundMode.addItem("")
        self.cboSoundMode.addItem("")
        self.cboSoundMode.addItem("")
        self.cboSoundMode.addItem("")
        self.cboSoundMode.addItem("")
        self.btnReaderUISignal = QtWidgets.QPushButton(self.centralwidget)
        self.btnReaderUISignal.setGeometry(QtCore.QRect(278, 97, 231, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnReaderUISignal.setFont(font)
        self.btnReaderUISignal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReaderUISignal.setObjectName("btnReaderUISignal")
        self.lblCONN = QtWidgets.QLabel(self.centralwidget)
        self.lblCONN.setGeometry(QtCore.QRect(0, 161, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblCONN.setFont(font)
        self.lblCONN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblCONN.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCONN.setText("")
        self.lblCONN.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCONN.setObjectName("lblCONN")
        self.lblFnResult = QtWidgets.QLabel(self.centralwidget)
        self.lblFnResult.setGeometry(QtCore.QRect(150, 161, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lblFnResult.setFont(font)
        self.lblFnResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFnResult.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblFnResult.setText("")
        self.lblFnResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnResult.setObjectName("lblFnResult")
        self.lblFnExplain = QtWidgets.QLabel(self.centralwidget)
        self.lblFnExplain.setGeometry(QtCore.QRect(220, 161, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.frameAuth = QtWidgets.QFrame(self.centralwidget)
        self.frameAuth.setGeometry(QtCore.QRect(0, 186, 541, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(198, 188, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 188, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 188, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        self.frameAuth.setPalette(palette)
        self.frameAuth.setAutoFillBackground(True)
        self.frameAuth.setFrameShape(QtWidgets.QFrame.Box)
        self.frameAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAuth.setObjectName("frameAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.frameAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(130, 11, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.frameAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(310, 11, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.frameCardReadKeys = QtWidgets.QFrame(self.centralwidget)
        self.frameCardReadKeys.setGeometry(QtCore.QRect(0, 228, 541, 140))
        self.frameCardReadKeys.setAutoFillBackground(False)
        self.frameCardReadKeys.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameCardReadKeys.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCardReadKeys.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameCardReadKeys.setObjectName("frameCardReadKeys")
        self.tabWidget = QtWidgets.QTabWidget(self.frameCardReadKeys)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 501, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tbCardKeys = QtWidgets.QWidget()
        self.tbCardKeys.setObjectName("tbCardKeys")
        self.lblKeyA = QtWidgets.QLabel(self.tbCardKeys)
        self.lblKeyA.setGeometry(QtCore.QRect(20, 10, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblKeyA.setFont(font)
        self.lblKeyA.setObjectName("lblKeyA")
        self.lblKeyB = QtWidgets.QLabel(self.tbCardKeys)
        self.lblKeyB.setGeometry(QtCore.QRect(20, 40, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblKeyB.setFont(font)
        self.lblKeyB.setObjectName("lblKeyB")
        self.chkHexCardKeys = QtWidgets.QCheckBox(self.tbCardKeys)
        self.chkHexCardKeys.setGeometry(QtCore.QRect(81, 68, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.chkHexCardKeys.setFont(font)
        self.chkHexCardKeys.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chkHexCardKeys.setObjectName("chkHexCardKeys")
        self.btnFormatCardKeys = QtWidgets.QPushButton(self.tbCardKeys)
        self.btnFormatCardKeys.setGeometry(QtCore.QRect(300, 10, 181, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnFormatCardKeys.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.btnFormatCardKeys.setFont(font)
        self.btnFormatCardKeys.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFormatCardKeys.setAutoFillBackground(False)
        self.btnFormatCardKeys.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.btnFormatCardKeys.setFlat(False)
        self.btnFormatCardKeys.setObjectName("btnFormatCardKeys")
        self.lblSectorsFormat = QtWidgets.QLabel(self.tbCardKeys)
        self.lblSectorsFormat.setGeometry(QtCore.QRect(300, 70, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblSectorsFormat.setFont(font)
        self.lblSectorsFormat.setObjectName("lblSectorsFormat")
        self.txtSectorsFormat = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtSectorsFormat.setGeometry(QtCore.QRect(428, 69, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorsFormat.setFont(font)
        self.txtSectorsFormat.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtSectorsFormat.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorsFormat.setReadOnly(True)
        self.txtSectorsFormat.setObjectName("txtSectorsFormat")
        self.txtCardKeysA1 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysA1.setGeometry(QtCore.QRect(81, 10, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysA1.setFont(font)
        self.txtCardKeysA1.setMaxLength(3)
        self.txtCardKeysA1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysA1.setObjectName("txtCardKeysA1")
        self.txtCardKeysA2 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysA2.setGeometry(QtCore.QRect(113, 10, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysA2.setFont(font)
        self.txtCardKeysA2.setMaxLength(3)
        self.txtCardKeysA2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysA2.setObjectName("txtCardKeysA2")
        self.txtCardKeysA3 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysA3.setGeometry(QtCore.QRect(145, 10, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysA3.setFont(font)
        self.txtCardKeysA3.setMaxLength(3)
        self.txtCardKeysA3.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysA3.setObjectName("txtCardKeysA3")
        self.txtCardKeysA4 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysA4.setGeometry(QtCore.QRect(177, 10, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysA4.setFont(font)
        self.txtCardKeysA4.setMaxLength(3)
        self.txtCardKeysA4.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysA4.setObjectName("txtCardKeysA4")
        self.txtCardKeysA5 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysA5.setGeometry(QtCore.QRect(209, 10, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysA5.setFont(font)
        self.txtCardKeysA5.setMaxLength(3)
        self.txtCardKeysA5.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysA5.setObjectName("txtCardKeysA5")
        self.txtCardKeysA6 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysA6.setGeometry(QtCore.QRect(241, 10, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysA6.setFont(font)
        self.txtCardKeysA6.setMaxLength(3)
        self.txtCardKeysA6.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysA6.setObjectName("txtCardKeysA6")
        self.txtCardKeysB3 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysB3.setGeometry(QtCore.QRect(145, 39, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysB3.setFont(font)
        self.txtCardKeysB3.setMaxLength(3)
        self.txtCardKeysB3.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysB3.setObjectName("txtCardKeysB3")
        self.txtCardKeysB1 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysB1.setGeometry(QtCore.QRect(81, 39, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysB1.setFont(font)
        self.txtCardKeysB1.setMaxLength(3)
        self.txtCardKeysB1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysB1.setObjectName("txtCardKeysB1")
        self.txtCardKeysB6 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysB6.setGeometry(QtCore.QRect(241, 39, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysB6.setFont(font)
        self.txtCardKeysB6.setMaxLength(3)
        self.txtCardKeysB6.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysB6.setObjectName("txtCardKeysB6")
        self.txtCardKeysB2 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysB2.setGeometry(QtCore.QRect(113, 39, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysB2.setFont(font)
        self.txtCardKeysB2.setMaxLength(3)
        self.txtCardKeysB2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysB2.setObjectName("txtCardKeysB2")
        self.txtCardKeysB4 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysB4.setGeometry(QtCore.QRect(177, 39, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysB4.setFont(font)
        self.txtCardKeysB4.setMaxLength(3)
        self.txtCardKeysB4.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysB4.setObjectName("txtCardKeysB4")
        self.txtCardKeysB5 = QtWidgets.QLineEdit(self.tbCardKeys)
        self.txtCardKeysB5.setGeometry(QtCore.QRect(209, 39, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtCardKeysB5.setFont(font)
        self.txtCardKeysB5.setMaxLength(3)
        self.txtCardKeysB5.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCardKeysB5.setObjectName("txtCardKeysB5")
        self.tabWidget.addTab(self.tbCardKeys, "")
        self.tbReaderKey = QtWidgets.QWidget()
        self.tbReaderKey.setObjectName("tbReaderKey")
        self.chkHexReaderKey = QtWidgets.QCheckBox(self.tbReaderKey)
        self.chkHexReaderKey.setGeometry(QtCore.QRect(69, 60, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.chkHexReaderKey.setFont(font)
        self.chkHexReaderKey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chkHexReaderKey.setObjectName("chkHexReaderKey")
        self.btnFormatReadKey = QtWidgets.QPushButton(self.tbReaderKey)
        self.btnFormatReadKey.setGeometry(QtCore.QRect(300, 21, 181, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnFormatReadKey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnFormatReadKey.setFont(font)
        self.btnFormatReadKey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFormatReadKey.setAutoFillBackground(False)
        self.btnFormatReadKey.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.btnFormatReadKey.setFlat(False)
        self.btnFormatReadKey.setObjectName("btnFormatReadKey")
        self.lblKeyIndex = QtWidgets.QLabel(self.tbReaderKey)
        self.lblKeyIndex.setGeometry(QtCore.QRect(149, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.txtKeyIndex = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtKeyIndex.setGeometry(QtCore.QRect(226, 59, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtKeyIndex.setFont(font)
        self.txtKeyIndex.setAlignment(QtCore.Qt.AlignCenter)
        self.txtKeyIndex.setReadOnly(True)
        self.txtKeyIndex.setObjectName("txtKeyIndex")
        self.txtReaderKey5 = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtReaderKey5.setGeometry(QtCore.QRect(196, 22, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderKey5.setFont(font)
        self.txtReaderKey5.setMaxLength(3)
        self.txtReaderKey5.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderKey5.setObjectName("txtReaderKey5")
        self.txtReaderKey6 = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtReaderKey6.setGeometry(QtCore.QRect(228, 22, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderKey6.setFont(font)
        self.txtReaderKey6.setMaxLength(3)
        self.txtReaderKey6.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderKey6.setObjectName("txtReaderKey6")
        self.txtReaderKey3 = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtReaderKey3.setGeometry(QtCore.QRect(132, 22, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderKey3.setFont(font)
        self.txtReaderKey3.setMaxLength(3)
        self.txtReaderKey3.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderKey3.setObjectName("txtReaderKey3")
        self.txtReaderKey1 = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtReaderKey1.setGeometry(QtCore.QRect(68, 22, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderKey1.setFont(font)
        self.txtReaderKey1.setMaxLength(3)
        self.txtReaderKey1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderKey1.setObjectName("txtReaderKey1")
        self.txtReaderKey4 = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtReaderKey4.setGeometry(QtCore.QRect(164, 22, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderKey4.setFont(font)
        self.txtReaderKey4.setMaxLength(3)
        self.txtReaderKey4.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderKey4.setObjectName("txtReaderKey4")
        self.txtReaderKey2 = QtWidgets.QLineEdit(self.tbReaderKey)
        self.txtReaderKey2.setGeometry(QtCore.QRect(100, 22, 30, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtReaderKey2.setFont(font)
        self.txtReaderKey2.setMaxLength(3)
        self.txtReaderKey2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReaderKey2.setObjectName("txtReaderKey2")
        self.tabWidget.addTab(self.tbReaderKey, "")
        self.tabLinearRW = QtWidgets.QTabWidget(self.centralwidget)
        self.tabLinearRW.setGeometry(QtCore.QRect(0, 370, 541, 230))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabLinearRW.setFont(font)
        self.tabLinearRW.setObjectName("tabLinearRW")
        self.tbLinearRead = QtWidgets.QWidget()
        self.tbLinearRead.setObjectName("tbLinearRead")
        self.lblLinearRead = QtWidgets.QLabel(self.tbLinearRead)
        self.lblLinearRead.setGeometry(QtCore.QRect(20, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearRead.setFont(font)
        self.lblLinearRead.setObjectName("lblLinearRead")
        self.txtLinearRead = QtWidgets.QTextEdit(self.tbLinearRead)
        self.txtLinearRead.setGeometry(QtCore.QRect(20, 22, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.txtLinearRead.setFont(font)
        self.txtLinearRead.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearRead.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearRead.setReadOnly(True)
        self.txtLinearRead.setObjectName("txtLinearRead")
        self.lblLinearAdressRead = QtWidgets.QLabel(self.tbLinearRead)
        self.lblLinearAdressRead.setGeometry(QtCore.QRect(20, 160, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressRead.setFont(font)
        self.lblLinearAdressRead.setObjectName("lblLinearAdressRead")
        self.txtLinearAddressRead = QtWidgets.QLineEdit(self.tbLinearRead)
        self.txtLinearAddressRead.setGeometry(QtCore.QRect(130, 159, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressRead.setFont(font)
        self.txtLinearAddressRead.setObjectName("txtLinearAddressRead")
        self.txtDataLengthRead = QtWidgets.QLineEdit(self.tbLinearRead)
        self.txtDataLengthRead.setGeometry(QtCore.QRect(130, 181, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthRead.setFont(font)
        self.txtDataLengthRead.setObjectName("txtDataLengthRead")
        self.lblDataLengthRead = QtWidgets.QLabel(self.tbLinearRead)
        self.lblDataLengthRead.setGeometry(QtCore.QRect(20, 182, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthRead.setFont(font)
        self.lblDataLengthRead.setObjectName("lblDataLengthRead")
        self.txtReadBytes = QtWidgets.QLineEdit(self.tbLinearRead)
        self.txtReadBytes.setGeometry(QtCore.QRect(300, 167, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtReadBytes.setFont(font)
        self.txtReadBytes.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtReadBytes.setAlignment(QtCore.Qt.AlignCenter)
        self.txtReadBytes.setReadOnly(True)
        self.txtReadBytes.setObjectName("txtReadBytes")
        self.lblReadBytes = QtWidgets.QLabel(self.tbLinearRead)
        self.lblReadBytes.setGeometry(QtCore.QRect(214, 167, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblReadBytes.setFont(font)
        self.lblReadBytes.setObjectName("lblReadBytes")
        self.btnLinearRead = QtWidgets.QPushButton(self.tbLinearRead)
        self.btnLinearRead.setGeometry(QtCore.QRect(370, 157, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btnLinearRead.setFont(font)
        self.btnLinearRead.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearRead.setObjectName("btnLinearRead")
        self.tabLinearRW.addTab(self.tbLinearRead, "")
        self.tbLinearWrite = QtWidgets.QWidget()
        self.tbLinearWrite.setObjectName("tbLinearWrite")
        self.txtLinearAddressWrite = QtWidgets.QLineEdit(self.tbLinearWrite)
        self.txtLinearAddressWrite.setGeometry(QtCore.QRect(130, 159, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtLinearAddressWrite.setFont(font)
        self.txtLinearAddressWrite.setObjectName("txtLinearAddressWrite")
        self.lblLinearAdressWrite = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblLinearAdressWrite.setGeometry(QtCore.QRect(20, 160, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearAdressWrite.setFont(font)
        self.lblLinearAdressWrite.setObjectName("lblLinearAdressWrite")
        self.lblDataLengthWrite = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblDataLengthWrite.setGeometry(QtCore.QRect(20, 182, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblDataLengthWrite.setFont(font)
        self.lblDataLengthWrite.setObjectName("lblDataLengthWrite")
        self.lblLinearWrite = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblLinearWrite.setGeometry(QtCore.QRect(20, 5, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblLinearWrite.setFont(font)
        self.lblLinearWrite.setObjectName("lblLinearWrite")
        self.lblBytesWritten = QtWidgets.QLabel(self.tbLinearWrite)
        self.lblBytesWritten.setGeometry(QtCore.QRect(212, 167, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lblBytesWritten.setFont(font)
        self.lblBytesWritten.setObjectName("lblBytesWritten")
        self.txtBytesWritten = QtWidgets.QLineEdit(self.tbLinearWrite)
        self.txtBytesWritten.setGeometry(QtCore.QRect(301, 167, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtBytesWritten.setFont(font)
        self.txtBytesWritten.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.txtBytesWritten.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBytesWritten.setReadOnly(True)
        self.txtBytesWritten.setObjectName("txtBytesWritten")
        self.txtDataLengthWrite = QtWidgets.QLineEdit(self.tbLinearWrite)
        self.txtDataLengthWrite.setGeometry(QtCore.QRect(130, 181, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.txtDataLengthWrite.setFont(font)
        self.txtDataLengthWrite.setObjectName("txtDataLengthWrite")
        self.txtLinearWrite = QtWidgets.QTextEdit(self.tbLinearWrite)
        self.txtLinearWrite.setGeometry(QtCore.QRect(20, 22, 501, 131))
        self.txtLinearWrite.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtLinearWrite.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLinearWrite.setReadOnly(False)
        self.txtLinearWrite.setObjectName("txtLinearWrite")
        self.btnLinearWrite = QtWidgets.QPushButton(self.tbLinearWrite)
        self.btnLinearWrite.setGeometry(QtCore.QRect(370, 157, 151, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnLinearWrite.setFont(font)
        self.btnLinearWrite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLinearWrite.setObjectName("btnLinearWrite")
        self.tabLinearRW.addTab(self.tbLinearWrite, "")
        self.lblCardStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblCardStatus.setGeometry(QtCore.QRect(0, 622, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.lblCardStatus.setFont(font)
        self.lblCardStatus.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lblCardStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblCardStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCardStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCardStatus.setObjectName("lblCardStatus")
        self.lblCardStatusValue = QtWidgets.QLabel(self.centralwidget)
        self.lblCardStatusValue.setGeometry(QtCore.QRect(150, 622, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.lblCardStatusValue.setFont(font)
        self.lblCardStatusValue.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lblCardStatusValue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblCardStatusValue.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCardStatusValue.setText("")
        self.lblCardStatusValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCardStatusValue.setObjectName("lblCardStatusValue")
        self.lblCardStatusExplain = QtWidgets.QLabel(self.centralwidget)
        self.lblCardStatusExplain.setGeometry(QtCore.QRect(220, 622, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.lblCardStatusExplain.setFont(font)
        self.lblCardStatusExplain.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lblCardStatusExplain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblCardStatusExplain.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCardStatusExplain.setText("")
        self.lblCardStatusExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCardStatusExplain.setObjectName("lblCardStatusExplain")
        self.lblFnErrorValue = QtWidgets.QLabel(self.centralwidget)
        self.lblFnErrorValue.setGeometry(QtCore.QRect(150, 602, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.lblFnErrorValue.setFont(font)
        self.lblFnErrorValue.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lblFnErrorValue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFnErrorValue.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblFnErrorValue.setText("")
        self.lblFnErrorValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnErrorValue.setObjectName("lblFnErrorValue")
        self.lblFnError = QtWidgets.QLabel(self.centralwidget)
        self.lblFnError.setGeometry(QtCore.QRect(0, 602, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblFnError.setFont(font)
        self.lblFnError.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnErrorExplain = QtWidgets.QLabel(self.centralwidget)
        self.lblFnErrorExplain.setGeometry(QtCore.QRect(220, 602, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.lblFnErrorExplain.setFont(font)
        self.lblFnErrorExplain.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lblFnErrorExplain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFnErrorExplain.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblFnErrorExplain.setText("")
        self.lblFnErrorExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnErrorExplain.setObjectName("lblFnErrorExplain")
        self.linkLabel = QtWidgets.QLabel(self.centralwidget)
        self.linkLabel.setGeometry(QtCore.QRect(40, 8, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.linkLabel.setFont(font)
        self.linkLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.linkLabel.setStyleSheet("color: rgb(0, 0, 255);")
        self.linkLabel.setObjectName("linkLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.mnuExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.mnuExit.setFont(font)
        self.mnuExit.setIconVisibleInMenu(False)
        self.mnuExit.setObjectName("mnuExit")
        self.menuFile.addAction(self.mnuExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabLinearRW.setCurrentIndex(0)
        self.mnuExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtReaderType, self.txtCardType)
        MainWindow.setTabOrder(self.txtCardType, self.txtUIDSize)
        MainWindow.setTabOrder(self.txtUIDSize, self.txtCardSerial)
        MainWindow.setTabOrder(self.txtCardSerial, self.cboLightMode)
        MainWindow.setTabOrder(self.cboLightMode, self.cboSoundMode)
        MainWindow.setTabOrder(self.cboSoundMode, self.btnReaderUISignal)
        MainWindow.setTabOrder(self.btnReaderUISignal, self.rbAUTH1A)
        MainWindow.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        MainWindow.setTabOrder(self.rbAUTH1B, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.chkHexCardKeys)
        MainWindow.setTabOrder(self.chkHexCardKeys, self.txtCardKeysA1)
        MainWindow.setTabOrder(self.txtCardKeysA1, self.txtCardKeysA2)
        MainWindow.setTabOrder(self.txtCardKeysA2, self.txtCardKeysA3)
        MainWindow.setTabOrder(self.txtCardKeysA3, self.txtCardKeysA4)
        MainWindow.setTabOrder(self.txtCardKeysA4, self.txtCardKeysA5)
        MainWindow.setTabOrder(self.txtCardKeysA5, self.txtCardKeysA6)
        MainWindow.setTabOrder(self.txtCardKeysA6, self.txtCardKeysB1)
        MainWindow.setTabOrder(self.txtCardKeysB1, self.txtCardKeysB2)
        MainWindow.setTabOrder(self.txtCardKeysB2, self.txtCardKeysB3)
        MainWindow.setTabOrder(self.txtCardKeysB3, self.txtCardKeysB4)
        MainWindow.setTabOrder(self.txtCardKeysB4, self.txtCardKeysB5)
        MainWindow.setTabOrder(self.txtCardKeysB5, self.txtCardKeysB6)
        MainWindow.setTabOrder(self.txtCardKeysB6, self.btnFormatCardKeys)
        MainWindow.setTabOrder(self.btnFormatCardKeys, self.txtSectorsFormat)
        MainWindow.setTabOrder(self.txtSectorsFormat, self.txtKeyIndex)
        MainWindow.setTabOrder(self.txtKeyIndex, self.txtReaderSerial)
        MainWindow.setTabOrder(self.txtReaderSerial, self.txtReaderKey1)
        MainWindow.setTabOrder(self.txtReaderKey1, self.txtReaderKey2)
        MainWindow.setTabOrder(self.txtReaderKey2, self.txtReaderKey3)
        MainWindow.setTabOrder(self.txtReaderKey3, self.txtReaderKey4)
        MainWindow.setTabOrder(self.txtReaderKey4, self.txtReaderKey5)
        MainWindow.setTabOrder(self.txtReaderKey5, self.txtReaderKey6)
        MainWindow.setTabOrder(self.txtReaderKey6, self.chkHexReaderKey)
        MainWindow.setTabOrder(self.chkHexReaderKey, self.btnFormatReadKey)
        MainWindow.setTabOrder(self.btnFormatReadKey, self.tabLinearRW)
        MainWindow.setTabOrder(self.tabLinearRW, self.txtLinearRead)
        MainWindow.setTabOrder(self.txtLinearRead, self.txtLinearAddressRead)
        MainWindow.setTabOrder(self.txtLinearAddressRead, self.txtDataLengthRead)
        MainWindow.setTabOrder(self.txtDataLengthRead, self.txtReadBytes)
        MainWindow.setTabOrder(self.txtReadBytes, self.btnLinearRead)
        MainWindow.setTabOrder(self.btnLinearRead, self.txtLinearAddressWrite)
        MainWindow.setTabOrder(self.txtLinearAddressWrite, self.txtBytesWritten)
        MainWindow.setTabOrder(self.txtBytesWritten, self.txtDataLengthWrite)
        MainWindow.setTabOrder(self.txtDataLengthWrite, self.txtLinearWrite)
        MainWindow.setTabOrder(self.txtLinearWrite, self.btnLinearWrite)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "uFCoder Simple"))
        self.lblReaderType.setText(_translate("MainWindow", "Reader Type"))
        self.lblReaderSerial.setText(_translate("MainWindow", "Reader Serial"))
        self.lblCardType.setText(_translate("MainWindow", "Card Type"))
        self.lblUIDSize.setText(_translate("MainWindow", "UID Size"))
        self.lblCardSerial.setText(_translate("MainWindow", "Card Serial"))
        self.lblLightMode.setText(_translate("MainWindow", "Light Mode"))
        self.lblSoundMode.setText(_translate("MainWindow", "Sound Mode"))
        self.cboLightMode.setItemText(0, _translate("MainWindow", "None"))
        self.cboLightMode.setItemText(1, _translate("MainWindow", "Long Green"))
        self.cboLightMode.setItemText(2, _translate("MainWindow", "Long Red"))
        self.cboLightMode.setItemText(3, _translate("MainWindow", "Alternation"))
        self.cboLightMode.setItemText(4, _translate("MainWindow", "Flash"))
        self.cboSoundMode.setItemText(0, _translate("MainWindow", "None"))
        self.cboSoundMode.setItemText(1, _translate("MainWindow", "Short"))
        self.cboSoundMode.setItemText(2, _translate("MainWindow", "Long "))
        self.cboSoundMode.setItemText(3, _translate("MainWindow", "Double Short"))
        self.cboSoundMode.setItemText(4, _translate("MainWindow", "Tripple Short"))
        self.cboSoundMode.setItemText(5, _translate("MainWindow", "Tripplet Melody"))
        self.btnReaderUISignal.setText(_translate("MainWindow", "READER UI SIGNAL"))
        self.rbAUTH1A.setText(_translate("MainWindow", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("MainWindow", "AUTH 1B"))
        self.lblKeyA.setText(_translate("MainWindow", "Key A"))
        self.lblKeyB.setText(_translate("MainWindow", "Key B"))
        self.chkHexCardKeys.setText(_translate("MainWindow", "Hex"))
        self.btnFormatCardKeys.setText(_translate("MainWindow", "FORMAT CARD KEYS"))
        self.lblSectorsFormat.setText(_translate("MainWindow", "Sectors Formatting"))
        self.txtCardKeysA1.setText(_translate("MainWindow", "255"))
        self.txtCardKeysA2.setText(_translate("MainWindow", "255"))
        self.txtCardKeysA3.setText(_translate("MainWindow", "255"))
        self.txtCardKeysA4.setText(_translate("MainWindow", "255"))
        self.txtCardKeysA5.setText(_translate("MainWindow", "255"))
        self.txtCardKeysA6.setText(_translate("MainWindow", "255"))
        self.txtCardKeysB3.setText(_translate("MainWindow", "255"))
        self.txtCardKeysB1.setText(_translate("MainWindow", "255"))
        self.txtCardKeysB6.setText(_translate("MainWindow", "255"))
        self.txtCardKeysB2.setText(_translate("MainWindow", "255"))
        self.txtCardKeysB4.setText(_translate("MainWindow", "255"))
        self.txtCardKeysB5.setText(_translate("MainWindow", "255"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbCardKeys), _translate("MainWindow", "New Card Keys"))
        self.chkHexReaderKey.setText(_translate("MainWindow", "Hex"))
        self.btnFormatReadKey.setText(_translate("MainWindow", "FORMAT READER KEY"))
        self.lblKeyIndex.setText(_translate("MainWindow", "Key Index"))
        self.txtKeyIndex.setText(_translate("MainWindow", "0"))
        self.txtReaderKey5.setText(_translate("MainWindow", "255"))
        self.txtReaderKey6.setText(_translate("MainWindow", "255"))
        self.txtReaderKey3.setText(_translate("MainWindow", "255"))
        self.txtReaderKey1.setText(_translate("MainWindow", "255"))
        self.txtReaderKey4.setText(_translate("MainWindow", "255"))
        self.txtReaderKey2.setText(_translate("MainWindow", "255"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbReaderKey), _translate("MainWindow", "New Reader Key"))
        self.lblLinearRead.setText(_translate("MainWindow", "Linear Read"))
        self.lblLinearAdressRead.setText(_translate("MainWindow", "Linear Address"))
        self.lblDataLengthRead.setText(_translate("MainWindow", "Data Length"))
        self.lblReadBytes.setText(_translate("MainWindow", "Read Bytes"))
        self.btnLinearRead.setText(_translate("MainWindow", "LINEAR READ"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearRead), _translate("MainWindow", "Linear Read"))
        self.lblLinearAdressWrite.setText(_translate("MainWindow", "Linear Address"))
        self.lblDataLengthWrite.setText(_translate("MainWindow", "Data Length"))
        self.lblLinearWrite.setText(_translate("MainWindow", "Linear Write"))
        self.lblBytesWritten.setText(_translate("MainWindow", "Bytes Written"))
        self.btnLinearWrite.setText(_translate("MainWindow", "LINEAR WRITE"))
        self.tabLinearRW.setTabText(self.tabLinearRW.indexOf(self.tbLinearWrite), _translate("MainWindow", "Linear Write"))
        self.lblCardStatus.setText(_translate("MainWindow", "CARD STATUS"))
        self.lblFnError.setText(_translate("MainWindow", "FUNCTION ERROR"))
        self.linkLabel.setText(_translate("MainWindow", "http://www.d-logic.net/nfc-rfid-reader-sdk/"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.mnuExit.setText(_translate("MainWindow", "Exit"))

