# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewAll.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewAll(object):
    def setupUi(self, ViewAll):
        ViewAll.setObjectName("ViewAll")
        ViewAll.resize(620, 380)
        self.grdViewAll = QtWidgets.QTableWidget(ViewAll)
        self.grdViewAll.setGeometry(QtCore.QRect(11, 10, 600, 260))
        self.grdViewAll.setAlternatingRowColors(True)
        self.grdViewAll.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.grdViewAll.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.grdViewAll.setGridStyle(QtCore.Qt.SolidLine)
        self.grdViewAll.setCornerButtonEnabled(False)
        self.grdViewAll.setRowCount(4)
        self.grdViewAll.setColumnCount(3)
        self.grdViewAll.setObjectName("grdViewAll")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(100, 0, 0))
        self.grdViewAll.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.grdViewAll.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.grdViewAll.setItem(0, 1, item)
        self.grdViewAll.horizontalHeader().setDefaultSectionSize(30)
        self.grdViewAll.verticalHeader().setVisible(False)
        self.lblFnExplain = QtWidgets.QLabel(ViewAll)
        self.lblFnExplain.setGeometry(QtCore.QRect(199, 340, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.lblFnError = QtWidgets.QLabel(ViewAll)
        self.lblFnError.setGeometry(QtCore.QRect(8, 340, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnValue = QtWidgets.QLabel(ViewAll)
        self.lblFnValue.setGeometry(QtCore.QRect(118, 340, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.fmControls = QtWidgets.QFrame(ViewAll)
        self.fmControls.setGeometry(QtCore.QRect(10, 272, 601, 60))
        self.fmControls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmControls.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.fmControls.setObjectName("fmControls")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.fmControls)
        self.rbAUTH1A.setGeometry(QtCore.QRect(30, 5, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setAutoFillBackground(True)
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.fmControls)
        self.rbAUTH1B.setGeometry(QtCore.QRect(30, 32, 96, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.fmControls)
        self.lblKeyIndex.setGeometry(QtCore.QRect(169, 18, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.fmControls)
        self.cboKeyIndex.setGeometry(QtCore.QRect(239, 12, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.btnReadCard = QtWidgets.QPushButton(self.fmControls)
        self.btnReadCard.setGeometry(QtCore.QRect(410, 3, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnReadCard.setFont(font)
        self.btnReadCard.setObjectName("btnReadCard")
        self.chkHex = QtWidgets.QCheckBox(self.fmControls)
        self.chkHex.setGeometry(QtCore.QRect(340, 17, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHex.setFont(font)
        self.chkHex.setObjectName("chkHex")
        self.pBar = QtWidgets.QProgressBar(self.fmControls)
        self.pBar.setGeometry(QtCore.QRect(410, 45, 180, 10))
        self.pBar.setProperty("value", 0)
        self.pBar.setObjectName("pBar")

        self.retranslateUi(ViewAll)
        QtCore.QMetaObject.connectSlotsByName(ViewAll)

    def retranslateUi(self, ViewAll):
        _translate = QtCore.QCoreApplication.translate
        ViewAll.setWindowTitle(_translate("ViewAll", "Dialog"))
        item = self.grdViewAll.verticalHeaderItem(0)
        item.setText(_translate("ViewAll", "11"))
        item = self.grdViewAll.verticalHeaderItem(1)
        item.setText(_translate("ViewAll", "New Row"))
        item = self.grdViewAll.verticalHeaderItem(2)
        item.setText(_translate("ViewAll", "FF"))
        item = self.grdViewAll.verticalHeaderItem(3)
        item.setText(_translate("ViewAll", "FA"))
        item = self.grdViewAll.horizontalHeaderItem(0)
        item.setText(_translate("ViewAll", "1"))
        item = self.grdViewAll.horizontalHeaderItem(1)
        item.setText(_translate("ViewAll", "New Column"))
        item = self.grdViewAll.horizontalHeaderItem(2)
        item.setText(_translate("ViewAll", "3"))
        __sortingEnabled = self.grdViewAll.isSortingEnabled()
        self.grdViewAll.setSortingEnabled(False)
        item = self.grdViewAll.item(0, 0)
        item.setText(_translate("ViewAll", "11"))
        item = self.grdViewAll.item(0, 1)
        item.setText(_translate("ViewAll", "19"))
        self.grdViewAll.setSortingEnabled(__sortingEnabled)
        self.lblFnError.setText(_translate("ViewAll", "Function Error :"))
        self.rbAUTH1A.setText(_translate("ViewAll", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("ViewAll", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("ViewAll", "Key Index"))
        self.btnReadCard.setText(_translate("ViewAll", "READ CARD"))
        self.chkHex.setText(_translate("ViewAll", "Hex"))

