# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BlockInSectorReadWrite.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BlockRWInSector(object):
    def setupUi(self, BlockRWInSector):
        BlockRWInSector.setObjectName("BlockRWInSector")
        BlockRWInSector.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(BlockRWInSector)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.tabBlockInSectorReadWrite = QtWidgets.QTabWidget(BlockRWInSector)
        self.tabBlockInSectorReadWrite.setGeometry(QtCore.QRect(5, 48, 611, 290))
        self.tabBlockInSectorReadWrite.setObjectName("tabBlockInSectorReadWrite")
        self.tbBlockInSectorRead = QtWidgets.QWidget()
        self.tbBlockInSectorRead.setObjectName("tbBlockInSectorRead")
        self.fmBlockInSectorRead = QtWidgets.QFrame(self.tbBlockInSectorRead)
        self.fmBlockInSectorRead.setGeometry(QtCore.QRect(8, 10, 271, 120))
        self.fmBlockInSectorRead.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockInSectorRead.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockInSectorRead.setObjectName("fmBlockInSectorRead")
        self.lblHeaderBSBR = QtWidgets.QLabel(self.fmBlockInSectorRead)
        self.lblHeaderBSBR.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBSBR.setFont(font)
        self.lblHeaderBSBR.setAutoFillBackground(False)
        self.lblHeaderBSBR.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBSBR.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBSBR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBSBR.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBSBR.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBSBR.setObjectName("lblHeaderBSBR")
        self.lblBlockAddressBR = QtWidgets.QLabel(self.fmBlockInSectorRead)
        self.lblBlockAddressBR.setGeometry(QtCore.QRect(13, 53, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBR.setFont(font)
        self.lblBlockAddressBR.setObjectName("lblBlockAddressBR")
        self.txtBlockInSAddressBR = QtWidgets.QLineEdit(self.fmBlockInSectorRead)
        self.txtBlockInSAddressBR.setGeometry(QtCore.QRect(105, 53, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBR.setFont(font)
        self.txtBlockInSAddressBR.setObjectName("txtBlockInSAddressBR")
        self.btnBlockInSRead = QtWidgets.QPushButton(self.fmBlockInSectorRead)
        self.btnBlockInSRead.setGeometry(QtCore.QRect(164, 31, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSRead.setFont(font)
        self.btnBlockInSRead.setObjectName("btnBlockInSRead")
        self.lblReadDataBR = QtWidgets.QLabel(self.fmBlockInSectorRead)
        self.lblReadDataBR.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBR.setFont(font)
        self.lblReadDataBR.setObjectName("lblReadDataBR")
        self.txtReadInSDataBR = QtWidgets.QLineEdit(self.fmBlockInSectorRead)
        self.txtReadInSDataBR.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtReadInSDataBR.setFont(font)
        self.txtReadInSDataBR.setReadOnly(True)
        self.txtReadInSDataBR.setObjectName("txtReadInSDataBR")
        self.txtSectorAddressBR = QtWidgets.QLineEdit(self.fmBlockInSectorRead)
        self.txtSectorAddressBR.setGeometry(QtCore.QRect(105, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBR.setFont(font)
        self.txtSectorAddressBR.setObjectName("txtSectorAddressBR")
        self.lblSectorAddressBR = QtWidgets.QLabel(self.fmBlockInSectorRead)
        self.lblSectorAddressBR.setGeometry(QtCore.QRect(13, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBR.setFont(font)
        self.lblSectorAddressBR.setObjectName("lblSectorAddressBR")
        self.fmBlockInSectorReadAKM1 = QtWidgets.QFrame(self.tbBlockInSectorRead)
        self.fmBlockInSectorReadAKM1.setGeometry(QtCore.QRect(320, 10, 271, 120))
        self.fmBlockInSectorReadAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockInSectorReadAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockInSectorReadAKM1.setObjectName("fmBlockInSectorReadAKM1")
        self.lblHeaderBSBRAKM1 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM1)
        self.lblHeaderBSBRAKM1.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBSBRAKM1.setFont(font)
        self.lblHeaderBSBRAKM1.setAutoFillBackground(False)
        self.lblHeaderBSBRAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBSBRAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBSBRAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBSBRAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBSBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBSBRAKM1.setObjectName("lblHeaderBSBRAKM1")
        self.lblBlockAddressBRAKM1 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM1)
        self.lblBlockAddressBRAKM1.setGeometry(QtCore.QRect(13, 53, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRAKM1.setFont(font)
        self.lblBlockAddressBRAKM1.setObjectName("lblBlockAddressBRAKM1")
        self.txtBlockInSAddressBRAKM1 = QtWidgets.QLineEdit(self.fmBlockInSectorReadAKM1)
        self.txtBlockInSAddressBRAKM1.setGeometry(QtCore.QRect(105, 53, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBRAKM1.setFont(font)
        self.txtBlockInSAddressBRAKM1.setObjectName("txtBlockInSAddressBRAKM1")
        self.btnBlockInSReadAKM1 = QtWidgets.QPushButton(self.fmBlockInSectorReadAKM1)
        self.btnBlockInSReadAKM1.setGeometry(QtCore.QRect(164, 31, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSReadAKM1.setFont(font)
        self.btnBlockInSReadAKM1.setObjectName("btnBlockInSReadAKM1")
        self.lblReadDataBRAKM1 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM1)
        self.lblReadDataBRAKM1.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM1.setFont(font)
        self.lblReadDataBRAKM1.setObjectName("lblReadDataBRAKM1")
        self.txtReadInSDataBRAKM1 = QtWidgets.QLineEdit(self.fmBlockInSectorReadAKM1)
        self.txtReadInSDataBRAKM1.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtReadInSDataBRAKM1.setFont(font)
        self.txtReadInSDataBRAKM1.setReadOnly(True)
        self.txtReadInSDataBRAKM1.setObjectName("txtReadInSDataBRAKM1")
        self.txtSectorAddressBRAKM1 = QtWidgets.QLineEdit(self.fmBlockInSectorReadAKM1)
        self.txtSectorAddressBRAKM1.setGeometry(QtCore.QRect(105, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBRAKM1.setFont(font)
        self.txtSectorAddressBRAKM1.setObjectName("txtSectorAddressBRAKM1")
        self.lblSectorAddressBRAKM1 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM1)
        self.lblSectorAddressBRAKM1.setGeometry(QtCore.QRect(13, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBRAKM1.setFont(font)
        self.lblSectorAddressBRAKM1.setObjectName("lblSectorAddressBRAKM1")
        self.fmBlockInSectorReadAKM2 = QtWidgets.QFrame(self.tbBlockInSectorRead)
        self.fmBlockInSectorReadAKM2.setGeometry(QtCore.QRect(10, 140, 271, 120))
        self.fmBlockInSectorReadAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockInSectorReadAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockInSectorReadAKM2.setObjectName("fmBlockInSectorReadAKM2")
        self.lblHeaderBSBRAKM2 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM2)
        self.lblHeaderBSBRAKM2.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBSBRAKM2.setFont(font)
        self.lblHeaderBSBRAKM2.setAutoFillBackground(False)
        self.lblHeaderBSBRAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBSBRAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBSBRAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBSBRAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBSBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBSBRAKM2.setObjectName("lblHeaderBSBRAKM2")
        self.lblBlockAddressBRAKM2 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM2)
        self.lblBlockAddressBRAKM2.setGeometry(QtCore.QRect(13, 53, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRAKM2.setFont(font)
        self.lblBlockAddressBRAKM2.setObjectName("lblBlockAddressBRAKM2")
        self.txtBlockInSAddressBRAKM2 = QtWidgets.QLineEdit(self.fmBlockInSectorReadAKM2)
        self.txtBlockInSAddressBRAKM2.setGeometry(QtCore.QRect(105, 53, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBRAKM2.setFont(font)
        self.txtBlockInSAddressBRAKM2.setObjectName("txtBlockInSAddressBRAKM2")
        self.btnBlockInSReadAKM2 = QtWidgets.QPushButton(self.fmBlockInSectorReadAKM2)
        self.btnBlockInSReadAKM2.setGeometry(QtCore.QRect(164, 31, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSReadAKM2.setFont(font)
        self.btnBlockInSReadAKM2.setObjectName("btnBlockInSReadAKM2")
        self.lblReadDataBRAKM2 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM2)
        self.lblReadDataBRAKM2.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM2.setFont(font)
        self.lblReadDataBRAKM2.setObjectName("lblReadDataBRAKM2")
        self.txtReadInSDataBRAKM2 = QtWidgets.QLineEdit(self.fmBlockInSectorReadAKM2)
        self.txtReadInSDataBRAKM2.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtReadInSDataBRAKM2.setFont(font)
        self.txtReadInSDataBRAKM2.setReadOnly(True)
        self.txtReadInSDataBRAKM2.setObjectName("txtReadInSDataBRAKM2")
        self.txtSectorAddressBRAKM2 = QtWidgets.QLineEdit(self.fmBlockInSectorReadAKM2)
        self.txtSectorAddressBRAKM2.setGeometry(QtCore.QRect(105, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBRAKM2.setFont(font)
        self.txtSectorAddressBRAKM2.setObjectName("txtSectorAddressBRAKM2")
        self.lblSectorAddressBRAKM2 = QtWidgets.QLabel(self.fmBlockInSectorReadAKM2)
        self.lblSectorAddressBRAKM2.setGeometry(QtCore.QRect(13, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBRAKM2.setFont(font)
        self.lblSectorAddressBRAKM2.setObjectName("lblSectorAddressBRAKM2")
        self.fmBlockInSectorReadPK = QtWidgets.QFrame(self.tbBlockInSectorRead)
        self.fmBlockInSectorReadPK.setGeometry(QtCore.QRect(320, 140, 271, 120))
        self.fmBlockInSectorReadPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockInSectorReadPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockInSectorReadPK.setObjectName("fmBlockInSectorReadPK")
        self.lblHeaderBSBRPK = QtWidgets.QLabel(self.fmBlockInSectorReadPK)
        self.lblHeaderBSBRPK.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBSBRPK.setFont(font)
        self.lblHeaderBSBRPK.setAutoFillBackground(False)
        self.lblHeaderBSBRPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBSBRPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBSBRPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBSBRPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBSBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBSBRPK.setObjectName("lblHeaderBSBRPK")
        self.lblBlockAddressBRPK = QtWidgets.QLabel(self.fmBlockInSectorReadPK)
        self.lblBlockAddressBRPK.setGeometry(QtCore.QRect(13, 53, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRPK.setFont(font)
        self.lblBlockAddressBRPK.setObjectName("lblBlockAddressBRPK")
        self.txtBlockInSAddressBRPK = QtWidgets.QLineEdit(self.fmBlockInSectorReadPK)
        self.txtBlockInSAddressBRPK.setGeometry(QtCore.QRect(105, 53, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBRPK.setFont(font)
        self.txtBlockInSAddressBRPK.setObjectName("txtBlockInSAddressBRPK")
        self.btnBlockInSReadPK = QtWidgets.QPushButton(self.fmBlockInSectorReadPK)
        self.btnBlockInSReadPK.setGeometry(QtCore.QRect(164, 31, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSReadPK.setFont(font)
        self.btnBlockInSReadPK.setObjectName("btnBlockInSReadPK")
        self.lblReadDataBRPK = QtWidgets.QLabel(self.fmBlockInSectorReadPK)
        self.lblReadDataBRPK.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRPK.setFont(font)
        self.lblReadDataBRPK.setObjectName("lblReadDataBRPK")
        self.txtReadInSDataBRPK = QtWidgets.QLineEdit(self.fmBlockInSectorReadPK)
        self.txtReadInSDataBRPK.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtReadInSDataBRPK.setFont(font)
        self.txtReadInSDataBRPK.setReadOnly(True)
        self.txtReadInSDataBRPK.setObjectName("txtReadInSDataBRPK")
        self.txtSectorAddressBRPK = QtWidgets.QLineEdit(self.fmBlockInSectorReadPK)
        self.txtSectorAddressBRPK.setGeometry(QtCore.QRect(105, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBRPK.setFont(font)
        self.txtSectorAddressBRPK.setObjectName("txtSectorAddressBRPK")
        self.lblSectorAddressBRPK = QtWidgets.QLabel(self.fmBlockInSectorReadPK)
        self.lblSectorAddressBRPK.setGeometry(QtCore.QRect(13, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBRPK.setFont(font)
        self.lblSectorAddressBRPK.setObjectName("lblSectorAddressBRPK")
        self.tabBlockInSectorReadWrite.addTab(self.tbBlockInSectorRead, "")
        self.tbBlockWrite = QtWidgets.QWidget()
        self.tbBlockWrite.setObjectName("tbBlockWrite")
        self.fmBlockWrite = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWrite.setGeometry(QtCore.QRect(8, 10, 271, 120))
        self.fmBlockWrite.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWrite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWrite.setObjectName("fmBlockWrite")
        self.lblHeaderBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblHeaderBW.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBW.setFont(font)
        self.lblHeaderBW.setAutoFillBackground(False)
        self.lblHeaderBW.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBW.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBW.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBW.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBW.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBW.setObjectName("lblHeaderBW")
        self.lblBlockAddressBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblBlockAddressBW.setGeometry(QtCore.QRect(10, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBW.setFont(font)
        self.lblBlockAddressBW.setObjectName("lblBlockAddressBW")
        self.txtBlockInSAddressBW = QtWidgets.QLineEdit(self.fmBlockWrite)
        self.txtBlockInSAddressBW.setGeometry(QtCore.QRect(102, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBW.setFont(font)
        self.txtBlockInSAddressBW.setObjectName("txtBlockInSAddressBW")
        self.btnBlockInSWrite = QtWidgets.QPushButton(self.fmBlockWrite)
        self.btnBlockInSWrite.setGeometry(QtCore.QRect(164, 69, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSWrite.setFont(font)
        self.btnBlockInSWrite.setObjectName("btnBlockInSWrite")
        self.lblWriteDataBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblWriteDataBW.setGeometry(QtCore.QRect(9, 21, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBW.setFont(font)
        self.lblWriteDataBW.setObjectName("lblWriteDataBW")
        self.txtWriteInSDataBW = QtWidgets.QLineEdit(self.fmBlockWrite)
        self.txtWriteInSDataBW.setGeometry(QtCore.QRect(11, 39, 240, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteInSDataBW.setFont(font)
        self.txtWriteInSDataBW.setReadOnly(False)
        self.txtWriteInSDataBW.setObjectName("txtWriteInSDataBW")
        self.lblSectorAddressBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblSectorAddressBW.setGeometry(QtCore.QRect(8, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBW.setFont(font)
        self.lblSectorAddressBW.setObjectName("lblSectorAddressBW")
        self.txtSectorAddressBW = QtWidgets.QLineEdit(self.fmBlockWrite)
        self.txtSectorAddressBW.setGeometry(QtCore.QRect(102, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBW.setFont(font)
        self.txtSectorAddressBW.setObjectName("txtSectorAddressBW")
        self.fmBlockWriteAKM1 = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWriteAKM1.setGeometry(QtCore.QRect(320, 10, 271, 120))
        self.fmBlockWriteAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWriteAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWriteAKM1.setObjectName("fmBlockWriteAKM1")
        self.lblHeaderBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblHeaderBWAKM1.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM1.setFont(font)
        self.lblHeaderBWAKM1.setAutoFillBackground(False)
        self.lblHeaderBWAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM1.setObjectName("lblHeaderBWAKM1")
        self.lblBlockAddressBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblBlockAddressBWAKM1.setGeometry(QtCore.QRect(10, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM1.setFont(font)
        self.lblBlockAddressBWAKM1.setObjectName("lblBlockAddressBWAKM1")
        self.txtBlockInSAddressBWAKM1 = QtWidgets.QLineEdit(self.fmBlockWriteAKM1)
        self.txtBlockInSAddressBWAKM1.setGeometry(QtCore.QRect(102, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBWAKM1.setFont(font)
        self.txtBlockInSAddressBWAKM1.setObjectName("txtBlockInSAddressBWAKM1")
        self.btnBlockInSWriteAKM1 = QtWidgets.QPushButton(self.fmBlockWriteAKM1)
        self.btnBlockInSWriteAKM1.setGeometry(QtCore.QRect(164, 69, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSWriteAKM1.setFont(font)
        self.btnBlockInSWriteAKM1.setObjectName("btnBlockInSWriteAKM1")
        self.lblWriteDataBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblWriteDataBWAKM1.setGeometry(QtCore.QRect(9, 21, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBWAKM1.setFont(font)
        self.lblWriteDataBWAKM1.setObjectName("lblWriteDataBWAKM1")
        self.txtWriteInSDataBWAKM1 = QtWidgets.QLineEdit(self.fmBlockWriteAKM1)
        self.txtWriteInSDataBWAKM1.setGeometry(QtCore.QRect(11, 39, 240, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteInSDataBWAKM1.setFont(font)
        self.txtWriteInSDataBWAKM1.setReadOnly(False)
        self.txtWriteInSDataBWAKM1.setObjectName("txtWriteInSDataBWAKM1")
        self.lblSectorAddressBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblSectorAddressBWAKM1.setGeometry(QtCore.QRect(8, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBWAKM1.setFont(font)
        self.lblSectorAddressBWAKM1.setObjectName("lblSectorAddressBWAKM1")
        self.txtSectorAddressBWAKM1 = QtWidgets.QLineEdit(self.fmBlockWriteAKM1)
        self.txtSectorAddressBWAKM1.setGeometry(QtCore.QRect(102, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBWAKM1.setFont(font)
        self.txtSectorAddressBWAKM1.setObjectName("txtSectorAddressBWAKM1")
        self.fmBlockWriteAKM2 = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWriteAKM2.setGeometry(QtCore.QRect(8, 140, 271, 120))
        self.fmBlockWriteAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWriteAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWriteAKM2.setObjectName("fmBlockWriteAKM2")
        self.lblHeaderBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblHeaderBWAKM2.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM2.setFont(font)
        self.lblHeaderBWAKM2.setAutoFillBackground(False)
        self.lblHeaderBWAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM2.setObjectName("lblHeaderBWAKM2")
        self.lblBlockAddressBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblBlockAddressBWAKM2.setGeometry(QtCore.QRect(10, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM2.setFont(font)
        self.lblBlockAddressBWAKM2.setObjectName("lblBlockAddressBWAKM2")
        self.txtBlockInSAddressBWAKM2 = QtWidgets.QLineEdit(self.fmBlockWriteAKM2)
        self.txtBlockInSAddressBWAKM2.setGeometry(QtCore.QRect(102, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBWAKM2.setFont(font)
        self.txtBlockInSAddressBWAKM2.setObjectName("txtBlockInSAddressBWAKM2")
        self.btnBlockInSWriteAKM2 = QtWidgets.QPushButton(self.fmBlockWriteAKM2)
        self.btnBlockInSWriteAKM2.setGeometry(QtCore.QRect(164, 69, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSWriteAKM2.setFont(font)
        self.btnBlockInSWriteAKM2.setObjectName("btnBlockInSWriteAKM2")
        self.lblWriteDataBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblWriteDataBWAKM2.setGeometry(QtCore.QRect(9, 21, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBWAKM2.setFont(font)
        self.lblWriteDataBWAKM2.setObjectName("lblWriteDataBWAKM2")
        self.txtWriteInSDataBWAKM2 = QtWidgets.QLineEdit(self.fmBlockWriteAKM2)
        self.txtWriteInSDataBWAKM2.setGeometry(QtCore.QRect(11, 39, 240, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteInSDataBWAKM2.setFont(font)
        self.txtWriteInSDataBWAKM2.setReadOnly(False)
        self.txtWriteInSDataBWAKM2.setObjectName("txtWriteInSDataBWAKM2")
        self.lblSectorAddressBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblSectorAddressBWAKM2.setGeometry(QtCore.QRect(8, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBWAKM2.setFont(font)
        self.lblSectorAddressBWAKM2.setObjectName("lblSectorAddressBWAKM2")
        self.txtSectorAddressBWAKM2 = QtWidgets.QLineEdit(self.fmBlockWriteAKM2)
        self.txtSectorAddressBWAKM2.setGeometry(QtCore.QRect(102, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBWAKM2.setFont(font)
        self.txtSectorAddressBWAKM2.setObjectName("txtSectorAddressBWAKM2")
        self.fmBlockWritePK = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWritePK.setGeometry(QtCore.QRect(320, 140, 271, 120))
        self.fmBlockWritePK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWritePK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWritePK.setObjectName("fmBlockWritePK")
        self.lblHeaderBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblHeaderBWPK.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWPK.setFont(font)
        self.lblHeaderBWPK.setAutoFillBackground(False)
        self.lblHeaderBWPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWPK.setObjectName("lblHeaderBWPK")
        self.lblBlockAddressBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblBlockAddressBWPK.setGeometry(QtCore.QRect(10, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWPK.setFont(font)
        self.lblBlockAddressBWPK.setObjectName("lblBlockAddressBWPK")
        self.txtBlockInSAddressBWPK = QtWidgets.QLineEdit(self.fmBlockWritePK)
        self.txtBlockInSAddressBWPK.setGeometry(QtCore.QRect(102, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockInSAddressBWPK.setFont(font)
        self.txtBlockInSAddressBWPK.setObjectName("txtBlockInSAddressBWPK")
        self.btnBlockInSWritePK = QtWidgets.QPushButton(self.fmBlockWritePK)
        self.btnBlockInSWritePK.setGeometry(QtCore.QRect(164, 69, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockInSWritePK.setFont(font)
        self.btnBlockInSWritePK.setObjectName("btnBlockInSWritePK")
        self.lblWriteDataBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblWriteDataBWPK.setGeometry(QtCore.QRect(9, 21, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBWPK.setFont(font)
        self.lblWriteDataBWPK.setObjectName("lblWriteDataBWPK")
        self.txtWriteInSDataBWPK = QtWidgets.QLineEdit(self.fmBlockWritePK)
        self.txtWriteInSDataBWPK.setGeometry(QtCore.QRect(11, 39, 240, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteInSDataBWPK.setFont(font)
        self.txtWriteInSDataBWPK.setReadOnly(False)
        self.txtWriteInSDataBWPK.setObjectName("txtWriteInSDataBWPK")
        self.lblSectorAddressBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblSectorAddressBWPK.setGeometry(QtCore.QRect(8, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBWPK.setFont(font)
        self.lblSectorAddressBWPK.setObjectName("lblSectorAddressBWPK")
        self.txtSectorAddressBWPK = QtWidgets.QLineEdit(self.fmBlockWritePK)
        self.txtSectorAddressBWPK.setGeometry(QtCore.QRect(102, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBWPK.setFont(font)
        self.txtSectorAddressBWPK.setObjectName("txtSectorAddressBWPK")
        self.tabBlockInSectorReadWrite.addTab(self.tbBlockWrite, "")
        self.lblFnValue = QtWidgets.QLabel(BlockRWInSector)
        self.lblFnValue.setGeometry(QtCore.QRect(120, 341, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnExplain = QtWidgets.QLabel(BlockRWInSector)
        self.lblFnExplain.setGeometry(QtCore.QRect(201, 341, 420, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.lblFnError = QtWidgets.QLabel(BlockRWInSector)
        self.lblFnError.setGeometry(QtCore.QRect(10, 341, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")

        self.retranslateUi(BlockRWInSector)
        self.tabBlockInSectorReadWrite.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BlockRWInSector)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBR, self.txtBlockInSAddressBR)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBR, self.btnBlockInSRead)
        BlockRWInSector.setTabOrder(self.btnBlockInSRead, self.txtSectorAddressBRAKM1)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBRAKM1, self.txtBlockInSAddressBRAKM1)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBRAKM1, self.btnBlockInSReadAKM1)
        BlockRWInSector.setTabOrder(self.btnBlockInSReadAKM1, self.txtSectorAddressBRAKM2)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBRAKM2, self.txtBlockInSAddressBRAKM2)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBRAKM2, self.btnBlockInSReadAKM2)
        BlockRWInSector.setTabOrder(self.btnBlockInSReadAKM2, self.txtSectorAddressBRPK)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBRPK, self.txtBlockInSAddressBRPK)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBRPK, self.btnBlockInSReadPK)
        BlockRWInSector.setTabOrder(self.btnBlockInSReadPK, self.txtWriteInSDataBW)
        BlockRWInSector.setTabOrder(self.txtWriteInSDataBW, self.txtSectorAddressBW)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBW, self.txtBlockInSAddressBW)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBW, self.btnBlockInSWrite)
        BlockRWInSector.setTabOrder(self.btnBlockInSWrite, self.txtWriteInSDataBWAKM1)
        BlockRWInSector.setTabOrder(self.txtWriteInSDataBWAKM1, self.txtSectorAddressBWAKM1)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBWAKM1, self.txtBlockInSAddressBWAKM1)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBWAKM1, self.btnBlockInSWriteAKM1)
        BlockRWInSector.setTabOrder(self.btnBlockInSWriteAKM1, self.txtWriteInSDataBWAKM2)
        BlockRWInSector.setTabOrder(self.txtWriteInSDataBWAKM2, self.txtSectorAddressBWAKM2)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBWAKM2, self.txtBlockInSAddressBWAKM2)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBWAKM2, self.btnBlockInSWriteAKM2)
        BlockRWInSector.setTabOrder(self.btnBlockInSWriteAKM2, self.txtWriteInSDataBWPK)
        BlockRWInSector.setTabOrder(self.txtWriteInSDataBWPK, self.txtSectorAddressBWPK)
        BlockRWInSector.setTabOrder(self.txtSectorAddressBWPK, self.txtBlockInSAddressBWPK)
        BlockRWInSector.setTabOrder(self.txtBlockInSAddressBWPK, self.btnBlockInSWritePK)
        BlockRWInSector.setTabOrder(self.btnBlockInSWritePK, self.tabBlockInSectorReadWrite)
        BlockRWInSector.setTabOrder(self.tabBlockInSectorReadWrite, self.rbAUTH1A)
        BlockRWInSector.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        BlockRWInSector.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        BlockRWInSector.setTabOrder(self.cboKeyIndex, self.txtReadInSDataBR)
        BlockRWInSector.setTabOrder(self.txtReadInSDataBR, self.txtReadInSDataBRAKM1)
        BlockRWInSector.setTabOrder(self.txtReadInSDataBRAKM1, self.txtReadInSDataBRAKM2)
        BlockRWInSector.setTabOrder(self.txtReadInSDataBRAKM2, self.txtReadInSDataBRPK)

    def retranslateUi(self, BlockRWInSector):
        _translate = QtCore.QCoreApplication.translate
        BlockRWInSector.setWindowTitle(_translate("BlockRWInSector", "Dialog"))
        self.rbAUTH1A.setText(_translate("BlockRWInSector", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("BlockRWInSector", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("BlockRWInSector", "Key Index"))
        self.lblPKKeys.setText(_translate("BlockRWInSector", "PK Key"))
        self.lblHeaderBSBR.setText(_translate("BlockRWInSector", "BLOCK IN SECTOR  READ"))
        self.lblBlockAddressBR.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSRead.setText(_translate("BlockRWInSector", "READ"))
        self.lblReadDataBR.setText(_translate("BlockRWInSector", "Read Data"))
        self.lblSectorAddressBR.setText(_translate("BlockRWInSector", "Sector Address"))
        self.lblHeaderBSBRAKM1.setText(_translate("BlockRWInSector", "BLOCK IN SECTOR  READ AKM1"))
        self.lblBlockAddressBRAKM1.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSReadAKM1.setText(_translate("BlockRWInSector", "READ"))
        self.lblReadDataBRAKM1.setText(_translate("BlockRWInSector", "Read Data"))
        self.lblSectorAddressBRAKM1.setText(_translate("BlockRWInSector", "Sector Address"))
        self.lblHeaderBSBRAKM2.setText(_translate("BlockRWInSector", "BLOCK IN SECTOR  READ AKM2"))
        self.lblBlockAddressBRAKM2.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSReadAKM2.setText(_translate("BlockRWInSector", "READ"))
        self.lblReadDataBRAKM2.setText(_translate("BlockRWInSector", "Read Data"))
        self.lblSectorAddressBRAKM2.setText(_translate("BlockRWInSector", "Sector Address"))
        self.lblHeaderBSBRPK.setText(_translate("BlockRWInSector", "BLOCK IN SECTOR  READ PK"))
        self.lblBlockAddressBRPK.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSReadPK.setText(_translate("BlockRWInSector", "READ"))
        self.lblReadDataBRPK.setText(_translate("BlockRWInSector", "Read Data"))
        self.lblSectorAddressBRPK.setText(_translate("BlockRWInSector", "Sector Address"))
        self.tabBlockInSectorReadWrite.setTabText(self.tabBlockInSectorReadWrite.indexOf(self.tbBlockInSectorRead), _translate("BlockRWInSector", "BlockInSector Read"))
        self.lblHeaderBW.setText(_translate("BlockRWInSector", "BLOCK WRITE"))
        self.lblBlockAddressBW.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSWrite.setText(_translate("BlockRWInSector", "WRITE"))
        self.lblWriteDataBW.setText(_translate("BlockRWInSector", "Write Data"))
        self.lblSectorAddressBW.setText(_translate("BlockRWInSector", "Sector Address"))
        self.lblHeaderBWAKM1.setText(_translate("BlockRWInSector", "BLOCK WRITE AKM1"))
        self.lblBlockAddressBWAKM1.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSWriteAKM1.setText(_translate("BlockRWInSector", "WRITE"))
        self.lblWriteDataBWAKM1.setText(_translate("BlockRWInSector", "Write Data"))
        self.lblSectorAddressBWAKM1.setText(_translate("BlockRWInSector", "Sector Address"))
        self.lblHeaderBWAKM2.setText(_translate("BlockRWInSector", "BLOCK WRITE AKM2"))
        self.lblBlockAddressBWAKM2.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSWriteAKM2.setText(_translate("BlockRWInSector", "WRITE"))
        self.lblWriteDataBWAKM2.setText(_translate("BlockRWInSector", "Write Data"))
        self.lblSectorAddressBWAKM2.setText(_translate("BlockRWInSector", "Sector Address"))
        self.lblHeaderBWPK.setText(_translate("BlockRWInSector", "BLOCK WRITE AKM1"))
        self.lblBlockAddressBWPK.setText(_translate("BlockRWInSector", "Block Address"))
        self.btnBlockInSWritePK.setText(_translate("BlockRWInSector", "WRITE"))
        self.lblWriteDataBWPK.setText(_translate("BlockRWInSector", "Write Data"))
        self.lblSectorAddressBWPK.setText(_translate("BlockRWInSector", "Sector Address"))
        self.tabBlockInSectorReadWrite.setTabText(self.tabBlockInSectorReadWrite.indexOf(self.tbBlockWrite), _translate("BlockRWInSector", "BlockInSector  Write"))
        self.lblFnError.setText(_translate("BlockRWInSector", "Function Error :"))

