# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BlockReadWrite.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_subBlockReadWrite(object):
    def setupUi(self, subBlockReadWrite):
        subBlockReadWrite.setObjectName("subBlockReadWrite")
        subBlockReadWrite.resize(620, 380)
        self.lblFnError = QtWidgets.QLabel(subBlockReadWrite)
        self.lblFnError.setGeometry(QtCore.QRect(0, 336, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnExplain = QtWidgets.QLabel(subBlockReadWrite)
        self.lblFnExplain.setGeometry(QtCore.QRect(191, 336, 420, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.lblFnValue = QtWidgets.QLabel(subBlockReadWrite)
        self.lblFnValue.setGeometry(QtCore.QRect(110, 336, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.tabBlockReadWrite = QtWidgets.QTabWidget(subBlockReadWrite)
        self.tabBlockReadWrite.setGeometry(QtCore.QRect(0, 42, 611, 290))
        self.tabBlockReadWrite.setObjectName("tabBlockReadWrite")
        self.tbBlockRead = QtWidgets.QWidget()
        self.tbBlockRead.setObjectName("tbBlockRead")
        self.fmBlockRead = QtWidgets.QFrame(self.tbBlockRead)
        self.fmBlockRead.setGeometry(QtCore.QRect(8, 10, 271, 120))
        self.fmBlockRead.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockRead.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockRead.setObjectName("fmBlockRead")
        self.lblHeaderBR = QtWidgets.QLabel(self.fmBlockRead)
        self.lblHeaderBR.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBR.setFont(font)
        self.lblHeaderBR.setAutoFillBackground(False)
        self.lblHeaderBR.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBR.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBR.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBR.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBR.setObjectName("lblHeaderBR")
        self.lblBlockAddressBR = QtWidgets.QLabel(self.fmBlockRead)
        self.lblBlockAddressBR.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBR.setFont(font)
        self.lblBlockAddressBR.setObjectName("lblBlockAddressBR")
        self.txtBlockAddressBR = QtWidgets.QLineEdit(self.fmBlockRead)
        self.txtBlockAddressBR.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBR.setFont(font)
        self.txtBlockAddressBR.setObjectName("txtBlockAddressBR")
        self.btnBlockRead = QtWidgets.QPushButton(self.fmBlockRead)
        self.btnBlockRead.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockRead.setFont(font)
        self.btnBlockRead.setObjectName("btnBlockRead")
        self.lblReadDataBR = QtWidgets.QLabel(self.fmBlockRead)
        self.lblReadDataBR.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBR.setFont(font)
        self.lblReadDataBR.setObjectName("lblReadDataBR")
        self.txtReadDataBR = QtWidgets.QLineEdit(self.fmBlockRead)
        self.txtReadDataBR.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.txtReadDataBR.setFont(font)
        self.txtReadDataBR.setText("")
        self.txtReadDataBR.setReadOnly(True)
        self.txtReadDataBR.setObjectName("txtReadDataBR")
        self.chkHexBoxBR = QtWidgets.QCheckBox(self.fmBlockRead)
        self.chkHexBoxBR.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBR.setFont(font)
        self.chkHexBoxBR.setObjectName("chkHexBoxBR")
        self.fmBlockReadAKM1 = QtWidgets.QFrame(self.tbBlockRead)
        self.fmBlockReadAKM1.setGeometry(QtCore.QRect(320, 10, 271, 120))
        self.fmBlockReadAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockReadAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockReadAKM1.setObjectName("fmBlockReadAKM1")
        self.lblHeaderBRAKM1 = QtWidgets.QLabel(self.fmBlockReadAKM1)
        self.lblHeaderBRAKM1.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBRAKM1.setFont(font)
        self.lblHeaderBRAKM1.setAutoFillBackground(False)
        self.lblHeaderBRAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBRAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBRAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBRAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBRAKM1.setObjectName("lblHeaderBRAKM1")
        self.lblBlockAddressBRAKM1 = QtWidgets.QLabel(self.fmBlockReadAKM1)
        self.lblBlockAddressBRAKM1.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRAKM1.setFont(font)
        self.lblBlockAddressBRAKM1.setObjectName("lblBlockAddressBRAKM1")
        self.txtBlockAddressBRAKM1 = QtWidgets.QLineEdit(self.fmBlockReadAKM1)
        self.txtBlockAddressBRAKM1.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBRAKM1.setFont(font)
        self.txtBlockAddressBRAKM1.setObjectName("txtBlockAddressBRAKM1")
        self.btnBlockReadAKM1 = QtWidgets.QPushButton(self.fmBlockReadAKM1)
        self.btnBlockReadAKM1.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockReadAKM1.setFont(font)
        self.btnBlockReadAKM1.setObjectName("btnBlockReadAKM1")
        self.lblReadDataBRAKM1 = QtWidgets.QLabel(self.fmBlockReadAKM1)
        self.lblReadDataBRAKM1.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM1.setFont(font)
        self.lblReadDataBRAKM1.setObjectName("lblReadDataBRAKM1")
        self.txtReadDataBRAKM1 = QtWidgets.QLineEdit(self.fmBlockReadAKM1)
        self.txtReadDataBRAKM1.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.txtReadDataBRAKM1.setFont(font)
        self.txtReadDataBRAKM1.setReadOnly(True)
        self.txtReadDataBRAKM1.setObjectName("txtReadDataBRAKM1")
        self.chkHexBoxBRAKM1 = QtWidgets.QCheckBox(self.fmBlockReadAKM1)
        self.chkHexBoxBRAKM1.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBRAKM1.setFont(font)
        self.chkHexBoxBRAKM1.setObjectName("chkHexBoxBRAKM1")
        self.fmBlockReadAKM2 = QtWidgets.QFrame(self.tbBlockRead)
        self.fmBlockReadAKM2.setGeometry(QtCore.QRect(8, 139, 271, 120))
        self.fmBlockReadAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockReadAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockReadAKM2.setObjectName("fmBlockReadAKM2")
        self.lblHeaderBRAKM2 = QtWidgets.QLabel(self.fmBlockReadAKM2)
        self.lblHeaderBRAKM2.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBRAKM2.setFont(font)
        self.lblHeaderBRAKM2.setAutoFillBackground(False)
        self.lblHeaderBRAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBRAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBRAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBRAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBRAKM2.setObjectName("lblHeaderBRAKM2")
        self.lblBlockAddressBRAKM2 = QtWidgets.QLabel(self.fmBlockReadAKM2)
        self.lblBlockAddressBRAKM2.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRAKM2.setFont(font)
        self.lblBlockAddressBRAKM2.setObjectName("lblBlockAddressBRAKM2")
        self.txtBlockAddressBRAKM2 = QtWidgets.QLineEdit(self.fmBlockReadAKM2)
        self.txtBlockAddressBRAKM2.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBRAKM2.setFont(font)
        self.txtBlockAddressBRAKM2.setObjectName("txtBlockAddressBRAKM2")
        self.btnBlockReadAKM2 = QtWidgets.QPushButton(self.fmBlockReadAKM2)
        self.btnBlockReadAKM2.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockReadAKM2.setFont(font)
        self.btnBlockReadAKM2.setObjectName("btnBlockReadAKM2")
        self.lblReadDataBRAKM2 = QtWidgets.QLabel(self.fmBlockReadAKM2)
        self.lblReadDataBRAKM2.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM2.setFont(font)
        self.lblReadDataBRAKM2.setObjectName("lblReadDataBRAKM2")
        self.txtReadDataBRAKM2 = QtWidgets.QLineEdit(self.fmBlockReadAKM2)
        self.txtReadDataBRAKM2.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.txtReadDataBRAKM2.setFont(font)
        self.txtReadDataBRAKM2.setReadOnly(True)
        self.txtReadDataBRAKM2.setObjectName("txtReadDataBRAKM2")
        self.chkHexBoxBRAKM2 = QtWidgets.QCheckBox(self.fmBlockReadAKM2)
        self.chkHexBoxBRAKM2.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBRAKM2.setFont(font)
        self.chkHexBoxBRAKM2.setObjectName("chkHexBoxBRAKM2")
        self.fmBlockReadPK = QtWidgets.QFrame(self.tbBlockRead)
        self.fmBlockReadPK.setGeometry(QtCore.QRect(320, 139, 271, 120))
        self.fmBlockReadPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockReadPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockReadPK.setObjectName("fmBlockReadPK")
        self.lblHeaderBRPK = QtWidgets.QLabel(self.fmBlockReadPK)
        self.lblHeaderBRPK.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBRPK.setFont(font)
        self.lblHeaderBRPK.setAutoFillBackground(False)
        self.lblHeaderBRPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBRPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBRPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBRPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBRPK.setObjectName("lblHeaderBRPK")
        self.lblBlockAddressBRPK = QtWidgets.QLabel(self.fmBlockReadPK)
        self.lblBlockAddressBRPK.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRPK.setFont(font)
        self.lblBlockAddressBRPK.setObjectName("lblBlockAddressBRPK")
        self.txtBlockAddressBRPK = QtWidgets.QLineEdit(self.fmBlockReadPK)
        self.txtBlockAddressBRPK.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBRPK.setFont(font)
        self.txtBlockAddressBRPK.setObjectName("txtBlockAddressBRPK")
        self.btnBlockReadPK = QtWidgets.QPushButton(self.fmBlockReadPK)
        self.btnBlockReadPK.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockReadPK.setFont(font)
        self.btnBlockReadPK.setObjectName("btnBlockReadPK")
        self.lblReadDataBRPK = QtWidgets.QLabel(self.fmBlockReadPK)
        self.lblReadDataBRPK.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRPK.setFont(font)
        self.lblReadDataBRPK.setObjectName("lblReadDataBRPK")
        self.txtReadDataBRPK = QtWidgets.QLineEdit(self.fmBlockReadPK)
        self.txtReadDataBRPK.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.txtReadDataBRPK.setFont(font)
        self.txtReadDataBRPK.setReadOnly(True)
        self.txtReadDataBRPK.setObjectName("txtReadDataBRPK")
        self.chkHexBoxBRPK = QtWidgets.QCheckBox(self.fmBlockReadPK)
        self.chkHexBoxBRPK.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBRPK.setFont(font)
        self.chkHexBoxBRPK.setObjectName("chkHexBoxBRPK")
        self.tabBlockReadWrite.addTab(self.tbBlockRead, "")
        self.tbBlockWrite = QtWidgets.QWidget()
        self.tbBlockWrite.setObjectName("tbBlockWrite")
        self.fmBlockWrite = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWrite.setGeometry(QtCore.QRect(8, 10, 271, 120))
        self.fmBlockWrite.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWrite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWrite.setObjectName("fmBlockWrite")
        self.lblHeaderBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblHeaderBW.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBW.setFont(font)
        self.lblHeaderBW.setAutoFillBackground(False)
        self.lblHeaderBW.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBW.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBW.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBW.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBW.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBW.setObjectName("lblHeaderBW")
        self.lblBlockAddressBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblBlockAddressBW.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBW.setFont(font)
        self.lblBlockAddressBW.setObjectName("lblBlockAddressBW")
        self.txtBlockAddressBW = QtWidgets.QLineEdit(self.fmBlockWrite)
        self.txtBlockAddressBW.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBW.setFont(font)
        self.txtBlockAddressBW.setObjectName("txtBlockAddressBW")
        self.btnBlockWrite = QtWidgets.QPushButton(self.fmBlockWrite)
        self.btnBlockWrite.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockWrite.setFont(font)
        self.btnBlockWrite.setObjectName("btnBlockWrite")
        self.lblWriteDataBW = QtWidgets.QLabel(self.fmBlockWrite)
        self.lblWriteDataBW.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBW.setFont(font)
        self.lblWriteDataBW.setObjectName("lblWriteDataBW")
        self.txtWriteDataBW = QtWidgets.QLineEdit(self.fmBlockWrite)
        self.txtWriteDataBW.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteDataBW.setFont(font)
        self.txtWriteDataBW.setReadOnly(False)
        self.txtWriteDataBW.setObjectName("txtWriteDataBW")
        self.chkHexBoxBW = QtWidgets.QCheckBox(self.fmBlockWrite)
        self.chkHexBoxBW.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBW.setFont(font)
        self.chkHexBoxBW.setObjectName("chkHexBoxBW")
        self.fmBlockWriteAKM1 = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWriteAKM1.setGeometry(QtCore.QRect(320, 10, 271, 120))
        self.fmBlockWriteAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWriteAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWriteAKM1.setObjectName("fmBlockWriteAKM1")
        self.lblHeaderBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblHeaderBWAKM1.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM1.setFont(font)
        self.lblHeaderBWAKM1.setAutoFillBackground(False)
        self.lblHeaderBWAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM1.setObjectName("lblHeaderBWAKM1")
        self.lblBlockAddressBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblBlockAddressBWAKM1.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM1.setFont(font)
        self.lblBlockAddressBWAKM1.setObjectName("lblBlockAddressBWAKM1")
        self.txtBlockAddressBWAKM1 = QtWidgets.QLineEdit(self.fmBlockWriteAKM1)
        self.txtBlockAddressBWAKM1.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBWAKM1.setFont(font)
        self.txtBlockAddressBWAKM1.setObjectName("txtBlockAddressBWAKM1")
        self.btnBlockWriteAKM1 = QtWidgets.QPushButton(self.fmBlockWriteAKM1)
        self.btnBlockWriteAKM1.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockWriteAKM1.setFont(font)
        self.btnBlockWriteAKM1.setObjectName("btnBlockWriteAKM1")
        self.lblWriteDataBWAKM1 = QtWidgets.QLabel(self.fmBlockWriteAKM1)
        self.lblWriteDataBWAKM1.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBWAKM1.setFont(font)
        self.lblWriteDataBWAKM1.setObjectName("lblWriteDataBWAKM1")
        self.txtWriteDataAKM1 = QtWidgets.QLineEdit(self.fmBlockWriteAKM1)
        self.txtWriteDataAKM1.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteDataAKM1.setFont(font)
        self.txtWriteDataAKM1.setReadOnly(False)
        self.txtWriteDataAKM1.setObjectName("txtWriteDataAKM1")
        self.chkHexBoxBWAKM1 = QtWidgets.QCheckBox(self.fmBlockWriteAKM1)
        self.chkHexBoxBWAKM1.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBWAKM1.setFont(font)
        self.chkHexBoxBWAKM1.setObjectName("chkHexBoxBWAKM1")
        self.fmBlockWriteAKM2 = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWriteAKM2.setGeometry(QtCore.QRect(8, 140, 271, 120))
        self.fmBlockWriteAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWriteAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWriteAKM2.setObjectName("fmBlockWriteAKM2")
        self.lblHeaderBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblHeaderBWAKM2.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM2.setFont(font)
        self.lblHeaderBWAKM2.setAutoFillBackground(False)
        self.lblHeaderBWAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM2.setObjectName("lblHeaderBWAKM2")
        self.lblBlockAddressBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblBlockAddressBWAKM2.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM2.setFont(font)
        self.lblBlockAddressBWAKM2.setObjectName("lblBlockAddressBWAKM2")
        self.txtBlockAddressBWAKM2 = QtWidgets.QLineEdit(self.fmBlockWriteAKM2)
        self.txtBlockAddressBWAKM2.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBWAKM2.setFont(font)
        self.txtBlockAddressBWAKM2.setObjectName("txtBlockAddressBWAKM2")
        self.btnBlockWriteAKM2 = QtWidgets.QPushButton(self.fmBlockWriteAKM2)
        self.btnBlockWriteAKM2.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockWriteAKM2.setFont(font)
        self.btnBlockWriteAKM2.setObjectName("btnBlockWriteAKM2")
        self.lblWriteDataBWAKM2 = QtWidgets.QLabel(self.fmBlockWriteAKM2)
        self.lblWriteDataBWAKM2.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBWAKM2.setFont(font)
        self.lblWriteDataBWAKM2.setObjectName("lblWriteDataBWAKM2")
        self.txtWriteDataAKM2 = QtWidgets.QLineEdit(self.fmBlockWriteAKM2)
        self.txtWriteDataAKM2.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteDataAKM2.setFont(font)
        self.txtWriteDataAKM2.setReadOnly(False)
        self.txtWriteDataAKM2.setObjectName("txtWriteDataAKM2")
        self.chkHexBoxBWAKM2 = QtWidgets.QCheckBox(self.fmBlockWriteAKM2)
        self.chkHexBoxBWAKM2.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBWAKM2.setFont(font)
        self.chkHexBoxBWAKM2.setObjectName("chkHexBoxBWAKM2")
        self.fmBlockWritePK = QtWidgets.QFrame(self.tbBlockWrite)
        self.fmBlockWritePK.setGeometry(QtCore.QRect(320, 140, 271, 120))
        self.fmBlockWritePK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmBlockWritePK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmBlockWritePK.setObjectName("fmBlockWritePK")
        self.lblHeaderBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblHeaderBWPK.setGeometry(QtCore.QRect(2, 2, 270, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWPK.setFont(font)
        self.lblHeaderBWPK.setAutoFillBackground(False)
        self.lblHeaderBWPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWPK.setObjectName("lblHeaderBWPK")
        self.lblBlockAddressBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblBlockAddressBWPK.setGeometry(QtCore.QRect(12, 30, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWPK.setFont(font)
        self.lblBlockAddressBWPK.setObjectName("lblBlockAddressBWPK")
        self.txtBlockAddressBWPK = QtWidgets.QLineEdit(self.fmBlockWritePK)
        self.txtBlockAddressBWPK.setGeometry(QtCore.QRect(99, 30, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressBWPK.setFont(font)
        self.txtBlockAddressBWPK.setObjectName("txtBlockAddressBWPK")
        self.btnBlockWritePK = QtWidgets.QPushButton(self.fmBlockWritePK)
        self.btnBlockWritePK.setGeometry(QtCore.QRect(164, 29, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnBlockWritePK.setFont(font)
        self.btnBlockWritePK.setObjectName("btnBlockWritePK")
        self.lblWriteDataBWPK = QtWidgets.QLabel(self.fmBlockWritePK)
        self.lblWriteDataBWPK.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblWriteDataBWPK.setFont(font)
        self.lblWriteDataBWPK.setObjectName("lblWriteDataBWPK")
        self.txtWriteDataPK = QtWidgets.QLineEdit(self.fmBlockWritePK)
        self.txtWriteDataPK.setGeometry(QtCore.QRect(16, 92, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtWriteDataPK.setFont(font)
        self.txtWriteDataPK.setReadOnly(False)
        self.txtWriteDataPK.setObjectName("txtWriteDataPK")
        self.chkHexBoxBWPK = QtWidgets.QCheckBox(self.fmBlockWritePK)
        self.chkHexBoxBWPK.setGeometry(QtCore.QRect(215, 71, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.chkHexBoxBWPK.setFont(font)
        self.chkHexBoxBWPK.setObjectName("chkHexBoxBWPK")
        self.tabBlockReadWrite.addTab(self.tbBlockWrite, "")
        self.pnlAuth = QtWidgets.QFrame(subBlockReadWrite)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setCurrentText("")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")

        self.retranslateUi(subBlockReadWrite)
        self.tabBlockReadWrite.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(subBlockReadWrite)
        subBlockReadWrite.setTabOrder(self.txtBlockAddressBR, self.btnBlockRead)
        subBlockReadWrite.setTabOrder(self.btnBlockRead, self.tabBlockReadWrite)
        subBlockReadWrite.setTabOrder(self.tabBlockReadWrite, self.rbAUTH1A)
        subBlockReadWrite.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        subBlockReadWrite.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        subBlockReadWrite.setTabOrder(self.cboKeyIndex, self.txtReadDataBR)
        subBlockReadWrite.setTabOrder(self.txtReadDataBR, self.chkHexBoxBR)

    def retranslateUi(self, subBlockReadWrite):
        _translate = QtCore.QCoreApplication.translate
        subBlockReadWrite.setWindowTitle(_translate("subBlockReadWrite", "Dialog"))
        self.lblFnError.setText(_translate("subBlockReadWrite", "Function Error :"))
        self.lblHeaderBR.setText(_translate("subBlockReadWrite", "BLOCK READ"))
        self.lblBlockAddressBR.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockRead.setText(_translate("subBlockReadWrite", "READ"))
        self.lblReadDataBR.setText(_translate("subBlockReadWrite", "Read Data"))
        self.chkHexBoxBR.setText(_translate("subBlockReadWrite", "Hex"))
        self.lblHeaderBRAKM1.setText(_translate("subBlockReadWrite", "BLOCK READ AKM1"))
        self.lblBlockAddressBRAKM1.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockReadAKM1.setText(_translate("subBlockReadWrite", "READ"))
        self.lblReadDataBRAKM1.setText(_translate("subBlockReadWrite", "Read Data"))
        self.chkHexBoxBRAKM1.setText(_translate("subBlockReadWrite", "Hex"))
        self.lblHeaderBRAKM2.setText(_translate("subBlockReadWrite", "BLOCK READ AKM2"))
        self.lblBlockAddressBRAKM2.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockReadAKM2.setText(_translate("subBlockReadWrite", "READ"))
        self.lblReadDataBRAKM2.setText(_translate("subBlockReadWrite", "Read Data"))
        self.chkHexBoxBRAKM2.setText(_translate("subBlockReadWrite", "Hex"))
        self.lblHeaderBRPK.setText(_translate("subBlockReadWrite", "BLOCK READ PK"))
        self.lblBlockAddressBRPK.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockReadPK.setText(_translate("subBlockReadWrite", "READ"))
        self.lblReadDataBRPK.setText(_translate("subBlockReadWrite", "Read Data"))
        self.chkHexBoxBRPK.setText(_translate("subBlockReadWrite", "Hex"))
        self.tabBlockReadWrite.setTabText(self.tabBlockReadWrite.indexOf(self.tbBlockRead), _translate("subBlockReadWrite", "Block Read"))
        self.lblHeaderBW.setText(_translate("subBlockReadWrite", "BLOCK WRITE"))
        self.lblBlockAddressBW.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockWrite.setText(_translate("subBlockReadWrite", "WRITE"))
        self.lblWriteDataBW.setText(_translate("subBlockReadWrite", "Write Data"))
        self.chkHexBoxBW.setText(_translate("subBlockReadWrite", "Hex"))
        self.lblHeaderBWAKM1.setText(_translate("subBlockReadWrite", "BLOCK WRITE AKM1"))
        self.lblBlockAddressBWAKM1.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockWriteAKM1.setText(_translate("subBlockReadWrite", "WRITE"))
        self.lblWriteDataBWAKM1.setText(_translate("subBlockReadWrite", "Write Data"))
        self.chkHexBoxBWAKM1.setText(_translate("subBlockReadWrite", "Hex"))
        self.lblHeaderBWAKM2.setText(_translate("subBlockReadWrite", "BLOCK WRITE AKM2"))
        self.lblBlockAddressBWAKM2.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockWriteAKM2.setText(_translate("subBlockReadWrite", "WRITE"))
        self.lblWriteDataBWAKM2.setText(_translate("subBlockReadWrite", "Write Data"))
        self.chkHexBoxBWAKM2.setText(_translate("subBlockReadWrite", "Hex"))
        self.lblHeaderBWPK.setText(_translate("subBlockReadWrite", "BLOCK WRITE PK"))
        self.lblBlockAddressBWPK.setText(_translate("subBlockReadWrite", "Block Address"))
        self.btnBlockWritePK.setText(_translate("subBlockReadWrite", "WRITE"))
        self.lblWriteDataBWPK.setText(_translate("subBlockReadWrite", "Write Data"))
        self.chkHexBoxBWPK.setText(_translate("subBlockReadWrite", "Hex"))
        self.tabBlockReadWrite.setTabText(self.tabBlockReadWrite.indexOf(self.tbBlockWrite), _translate("subBlockReadWrite", "Block Write"))
        self.rbAUTH1A.setText(_translate("subBlockReadWrite", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("subBlockReadWrite", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("subBlockReadWrite", "Key Index"))
        self.lblPKKeys.setText(_translate("subBlockReadWrite", "PK Key"))

