# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinearFormatCard.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LinearFormatCard(object):
    def setupUi(self, LinearFormatCard):
        LinearFormatCard.setObjectName("LinearFormatCard")
        LinearFormatCard.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(LinearFormatCard)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 610, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.lblFnValue = QtWidgets.QLabel(LinearFormatCard)
        self.lblFnValue.setGeometry(QtCore.QRect(118, 340, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnExplain = QtWidgets.QLabel(LinearFormatCard)
        self.lblFnExplain.setGeometry(QtCore.QRect(199, 340, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.lblFnError = QtWidgets.QLabel(LinearFormatCard)
        self.lblFnError.setGeometry(QtCore.QRect(8, 340, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.fmKeyA = QtWidgets.QFrame(LinearFormatCard)
        self.fmKeyA.setGeometry(QtCore.QRect(6, 41, 300, 90))
        self.fmKeyA.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fmKeyA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmKeyA.setObjectName("fmKeyA")
        self.chkKeyA = QtWidgets.QCheckBox(self.fmKeyA)
        self.chkKeyA.setGeometry(QtCore.QRect(56, 57, 86, 21))
        self.chkKeyA.setObjectName("chkKeyA")
        self.lblKeyA = QtWidgets.QLabel(self.fmKeyA)
        self.lblKeyA.setGeometry(QtCore.QRect(1, 1, 300, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblKeyA.setFont(font)
        self.lblKeyA.setAutoFillBackground(False)
        self.lblKeyA.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lblKeyA.setFrameShape(QtWidgets.QFrame.Box)
        self.lblKeyA.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblKeyA.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKeyA.setObjectName("lblKeyA")
        self.fmKeyB = QtWidgets.QFrame(LinearFormatCard)
        self.fmKeyB.setGeometry(QtCore.QRect(310, 41, 300, 90))
        self.fmKeyB.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fmKeyB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmKeyB.setObjectName("fmKeyB")
        self.chkKeyB = QtWidgets.QCheckBox(self.fmKeyB)
        self.chkKeyB.setGeometry(QtCore.QRect(56, 57, 86, 21))
        self.chkKeyB.setObjectName("chkKeyB")
        self.lblKeyB = QtWidgets.QLabel(self.fmKeyB)
        self.lblKeyB.setGeometry(QtCore.QRect(0, 1, 300, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblKeyB.setFont(font)
        self.lblKeyB.setAutoFillBackground(False)
        self.lblKeyB.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lblKeyB.setFrameShape(QtWidgets.QFrame.Box)
        self.lblKeyB.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblKeyB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKeyB.setObjectName("lblKeyB")
        self.tabLinearFormatCard = QtWidgets.QTabWidget(LinearFormatCard)
        self.tabLinearFormatCard.setGeometry(QtCore.QRect(1, 132, 611, 201))
        self.tabLinearFormatCard.setAutoFillBackground(True)
        self.tabLinearFormatCard.setObjectName("tabLinearFormatCard")
        self.tbFormatCard = QtWidgets.QWidget()
        self.tbFormatCard.setObjectName("tbFormatCard")
        self.fmContainer = QtWidgets.QFrame(self.tbFormatCard)
        self.fmContainer.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainer.setObjectName("fmContainer")
        self.lblBlockAccessBits = QtWidgets.QLabel(self.fmContainer)
        self.lblBlockAccessBits.setGeometry(QtCore.QRect(70, 29, 101, 16))
        self.lblBlockAccessBits.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockAccessBits.setObjectName("lblBlockAccessBits")
        self.lblSectorTrailerAccessBits = QtWidgets.QLabel(self.fmContainer)
        self.lblSectorTrailerAccessBits.setGeometry(QtCore.QRect(69, 60, 141, 16))
        self.lblSectorTrailerAccessBits.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerAccessBits.setObjectName("lblSectorTrailerAccessBits")
        self.lblSectorTrailerByte9 = QtWidgets.QLabel(self.fmContainer)
        self.lblSectorTrailerByte9.setGeometry(QtCore.QRect(70, 89, 141, 16))
        self.lblSectorTrailerByte9.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9.setObjectName("lblSectorTrailerByte9")
        self.btnLinearFormat = QtWidgets.QPushButton(self.fmContainer)
        self.btnLinearFormat.setGeometry(QtCore.QRect(300, 21, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearFormat.setFont(font)
        self.btnLinearFormat.setObjectName("btnLinearFormat")
        self.lblSectorFormatted = QtWidgets.QLabel(self.fmContainer)
        self.lblSectorFormatted.setGeometry(QtCore.QRect(355, 117, 101, 16))
        self.lblSectorFormatted.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorFormatted.setObjectName("lblSectorFormatted")
        self.cboSectorTrailerAccessBits = QtWidgets.QComboBox(self.fmContainer)
        self.cboSectorTrailerAccessBits.setGeometry(QtCore.QRect(220, 52, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboSectorTrailerAccessBits.setFont(font)
        self.cboSectorTrailerAccessBits.setObjectName("cboSectorTrailerAccessBits")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.cboSectorTrailerAccessBits.addItem("")
        self.txtSectorFormatted = QtWidgets.QLineEdit(self.fmContainer)
        self.txtSectorFormatted.setGeometry(QtCore.QRect(470, 109, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorFormatted.setFont(font)
        self.txtSectorFormatted.setAutoFillBackground(False)
        self.txtSectorFormatted.setStyleSheet("background-color: rgb(150, 145, 140);\n"
"color: rgb(255, 255, 255);")
        self.txtSectorFormatted.setText("")
        self.txtSectorFormatted.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorFormatted.setReadOnly(True)
        self.txtSectorFormatted.setObjectName("txtSectorFormatted")
        self.cboBlockAccessBits = QtWidgets.QComboBox(self.fmContainer)
        self.cboBlockAccessBits.setGeometry(QtCore.QRect(220, 21, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboBlockAccessBits.setFont(font)
        self.cboBlockAccessBits.setObjectName("cboBlockAccessBits")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.cboBlockAccessBits.addItem("")
        self.txtSectorTrailerByte9 = QtWidgets.QLineEdit(self.fmContainer)
        self.txtSectorTrailerByte9.setGeometry(QtCore.QRect(220, 84, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9.setFont(font)
        self.txtSectorTrailerByte9.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9.setObjectName("txtSectorTrailerByte9")
        self.tabLinearFormatCard.addTab(self.tbFormatCard, "")
        self.tbFormatCardAKM1 = QtWidgets.QWidget()
        self.tbFormatCardAKM1.setObjectName("tbFormatCardAKM1")
        self.fmContainerAKM1 = QtWidgets.QFrame(self.tbFormatCardAKM1)
        self.fmContainerAKM1.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainerAKM1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainerAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainerAKM1.setObjectName("fmContainerAKM1")
        self.lblBlockAccessBitsAKM1 = QtWidgets.QLabel(self.fmContainerAKM1)
        self.lblBlockAccessBitsAKM1.setGeometry(QtCore.QRect(70, 29, 101, 16))
        self.lblBlockAccessBitsAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockAccessBitsAKM1.setObjectName("lblBlockAccessBitsAKM1")
        self.lblSectorTrailerAccessBitsAKM1 = QtWidgets.QLabel(self.fmContainerAKM1)
        self.lblSectorTrailerAccessBitsAKM1.setGeometry(QtCore.QRect(69, 60, 141, 16))
        self.lblSectorTrailerAccessBitsAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerAccessBitsAKM1.setObjectName("lblSectorTrailerAccessBitsAKM1")
        self.lblSectorTrailerByte9AKM1 = QtWidgets.QLabel(self.fmContainerAKM1)
        self.lblSectorTrailerByte9AKM1.setGeometry(QtCore.QRect(70, 89, 141, 16))
        self.lblSectorTrailerByte9AKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9AKM1.setObjectName("lblSectorTrailerByte9AKM1")
        self.btnLinearFormatAKM1 = QtWidgets.QPushButton(self.fmContainerAKM1)
        self.btnLinearFormatAKM1.setGeometry(QtCore.QRect(300, 21, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearFormatAKM1.setFont(font)
        self.btnLinearFormatAKM1.setObjectName("btnLinearFormatAKM1")
        self.lblSectorFormattedAKM1 = QtWidgets.QLabel(self.fmContainerAKM1)
        self.lblSectorFormattedAKM1.setGeometry(QtCore.QRect(355, 117, 101, 16))
        self.lblSectorFormattedAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorFormattedAKM1.setObjectName("lblSectorFormattedAKM1")
        self.cboSectorTrailerAccessBitsAKM1 = QtWidgets.QComboBox(self.fmContainerAKM1)
        self.cboSectorTrailerAccessBitsAKM1.setGeometry(QtCore.QRect(220, 52, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboSectorTrailerAccessBitsAKM1.setFont(font)
        self.cboSectorTrailerAccessBitsAKM1.setObjectName("cboSectorTrailerAccessBitsAKM1")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.cboSectorTrailerAccessBitsAKM1.addItem("")
        self.txtSectorFormattedAKM1 = QtWidgets.QLineEdit(self.fmContainerAKM1)
        self.txtSectorFormattedAKM1.setGeometry(QtCore.QRect(470, 109, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorFormattedAKM1.setFont(font)
        self.txtSectorFormattedAKM1.setAutoFillBackground(False)
        self.txtSectorFormattedAKM1.setStyleSheet("background-color: rgb(150, 145, 140);\n"
"color: rgb(255, 255, 255);")
        self.txtSectorFormattedAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorFormattedAKM1.setReadOnly(True)
        self.txtSectorFormattedAKM1.setObjectName("txtSectorFormattedAKM1")
        self.cboBlockAccessBitsAKM1 = QtWidgets.QComboBox(self.fmContainerAKM1)
        self.cboBlockAccessBitsAKM1.setGeometry(QtCore.QRect(220, 21, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboBlockAccessBitsAKM1.setFont(font)
        self.cboBlockAccessBitsAKM1.setObjectName("cboBlockAccessBitsAKM1")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.cboBlockAccessBitsAKM1.addItem("")
        self.txtSectorTrailerByte9AKM1 = QtWidgets.QLineEdit(self.fmContainerAKM1)
        self.txtSectorTrailerByte9AKM1.setGeometry(QtCore.QRect(220, 84, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9AKM1.setFont(font)
        self.txtSectorTrailerByte9AKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9AKM1.setObjectName("txtSectorTrailerByte9AKM1")
        self.tabLinearFormatCard.addTab(self.tbFormatCardAKM1, "")
        self.tbFormatCardAKM2 = QtWidgets.QWidget()
        self.tbFormatCardAKM2.setObjectName("tbFormatCardAKM2")
        self.fmContainerAKM2 = QtWidgets.QFrame(self.tbFormatCardAKM2)
        self.fmContainerAKM2.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainerAKM2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainerAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainerAKM2.setObjectName("fmContainerAKM2")
        self.lblBlockAccessBitsAKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblBlockAccessBitsAKM2.setGeometry(QtCore.QRect(70, 29, 101, 16))
        self.lblBlockAccessBitsAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockAccessBitsAKM2.setObjectName("lblBlockAccessBitsAKM2")
        self.lblSectorTrailerAccessBitsAKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblSectorTrailerAccessBitsAKM2.setGeometry(QtCore.QRect(69, 60, 141, 16))
        self.lblSectorTrailerAccessBitsAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerAccessBitsAKM2.setObjectName("lblSectorTrailerAccessBitsAKM2")
        self.lblSectorTrailerByte9AKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblSectorTrailerByte9AKM2.setGeometry(QtCore.QRect(70, 89, 141, 16))
        self.lblSectorTrailerByte9AKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9AKM2.setObjectName("lblSectorTrailerByte9AKM2")
        self.btnLinearFormatAKM2 = QtWidgets.QPushButton(self.fmContainerAKM2)
        self.btnLinearFormatAKM2.setGeometry(QtCore.QRect(300, 21, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearFormatAKM2.setFont(font)
        self.btnLinearFormatAKM2.setObjectName("btnLinearFormatAKM2")
        self.lblSectorFormattedAKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblSectorFormattedAKM2.setGeometry(QtCore.QRect(355, 117, 101, 16))
        self.lblSectorFormattedAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorFormattedAKM2.setObjectName("lblSectorFormattedAKM2")
        self.cboSectorTrailerAccessBitsAKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboSectorTrailerAccessBitsAKM2.setGeometry(QtCore.QRect(220, 52, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboSectorTrailerAccessBitsAKM2.setFont(font)
        self.cboSectorTrailerAccessBitsAKM2.setObjectName("cboSectorTrailerAccessBitsAKM2")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.cboSectorTrailerAccessBitsAKM2.addItem("")
        self.txtSectorFormattedAKM2 = QtWidgets.QLineEdit(self.fmContainerAKM2)
        self.txtSectorFormattedAKM2.setGeometry(QtCore.QRect(470, 109, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorFormattedAKM2.setFont(font)
        self.txtSectorFormattedAKM2.setAutoFillBackground(False)
        self.txtSectorFormattedAKM2.setStyleSheet("background-color: rgb(150, 145, 140);\n"
"color: rgb(255, 255, 255);")
        self.txtSectorFormattedAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorFormattedAKM2.setReadOnly(True)
        self.txtSectorFormattedAKM2.setObjectName("txtSectorFormattedAKM2")
        self.cboBlockAccessBitsAKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboBlockAccessBitsAKM2.setGeometry(QtCore.QRect(220, 21, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboBlockAccessBitsAKM2.setFont(font)
        self.cboBlockAccessBitsAKM2.setObjectName("cboBlockAccessBitsAKM2")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.cboBlockAccessBitsAKM2.addItem("")
        self.txtSectorTrailerByte9AKM2 = QtWidgets.QLineEdit(self.fmContainerAKM2)
        self.txtSectorTrailerByte9AKM2.setGeometry(QtCore.QRect(220, 84, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9AKM2.setFont(font)
        self.txtSectorTrailerByte9AKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9AKM2.setObjectName("txtSectorTrailerByte9AKM2")
        self.tabLinearFormatCard.addTab(self.tbFormatCardAKM2, "")
        self.tbFormatCardPK = QtWidgets.QWidget()
        self.tbFormatCardPK.setObjectName("tbFormatCardPK")
        self.fmContainerPK = QtWidgets.QFrame(self.tbFormatCardPK)
        self.fmContainerPK.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainerPK.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainerPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainerPK.setObjectName("fmContainerPK")
        self.lblBlockAccessBitsPK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblBlockAccessBitsPK.setGeometry(QtCore.QRect(70, 29, 101, 16))
        self.lblBlockAccessBitsPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockAccessBitsPK.setObjectName("lblBlockAccessBitsPK")
        self.lblSectorTrailerAccessBitsPK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblSectorTrailerAccessBitsPK.setGeometry(QtCore.QRect(69, 60, 141, 16))
        self.lblSectorTrailerAccessBitsPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerAccessBitsPK.setObjectName("lblSectorTrailerAccessBitsPK")
        self.lblSectorTrailerByte9PK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblSectorTrailerByte9PK.setGeometry(QtCore.QRect(70, 89, 141, 16))
        self.lblSectorTrailerByte9PK.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9PK.setObjectName("lblSectorTrailerByte9PK")
        self.btnLinearFormatPK = QtWidgets.QPushButton(self.fmContainerPK)
        self.btnLinearFormatPK.setGeometry(QtCore.QRect(300, 21, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnLinearFormatPK.setFont(font)
        self.btnLinearFormatPK.setObjectName("btnLinearFormatPK")
        self.lblSectorFormattedPK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblSectorFormattedPK.setGeometry(QtCore.QRect(355, 117, 101, 16))
        self.lblSectorFormattedPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorFormattedPK.setObjectName("lblSectorFormattedPK")
        self.cboSectorTrailerAccessBitsPK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboSectorTrailerAccessBitsPK.setGeometry(QtCore.QRect(220, 52, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboSectorTrailerAccessBitsPK.setFont(font)
        self.cboSectorTrailerAccessBitsPK.setObjectName("cboSectorTrailerAccessBitsPK")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.cboSectorTrailerAccessBitsPK.addItem("")
        self.txtSectorFormattedPK = QtWidgets.QLineEdit(self.fmContainerPK)
        self.txtSectorFormattedPK.setGeometry(QtCore.QRect(470, 109, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorFormattedPK.setFont(font)
        self.txtSectorFormattedPK.setAutoFillBackground(False)
        self.txtSectorFormattedPK.setStyleSheet("background-color: rgb(150, 145, 140);\n"
"color: rgb(255, 255, 255);")
        self.txtSectorFormattedPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorFormattedPK.setReadOnly(True)
        self.txtSectorFormattedPK.setObjectName("txtSectorFormattedPK")
        self.cboBlockAccessBitsPK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboBlockAccessBitsPK.setGeometry(QtCore.QRect(220, 21, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboBlockAccessBitsPK.setFont(font)
        self.cboBlockAccessBitsPK.setObjectName("cboBlockAccessBitsPK")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.cboBlockAccessBitsPK.addItem("")
        self.txtSectorTrailerByte9PK = QtWidgets.QLineEdit(self.fmContainerPK)
        self.txtSectorTrailerByte9PK.setGeometry(QtCore.QRect(220, 84, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9PK.setFont(font)
        self.txtSectorTrailerByte9PK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9PK.setObjectName("txtSectorTrailerByte9PK")
        self.tabLinearFormatCard.addTab(self.tbFormatCardPK, "")

        self.retranslateUi(LinearFormatCard)
        self.tabLinearFormatCard.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LinearFormatCard)
        LinearFormatCard.setTabOrder(self.tabLinearFormatCard, self.cboBlockAccessBits)
        LinearFormatCard.setTabOrder(self.cboBlockAccessBits, self.cboSectorTrailerAccessBits)
        LinearFormatCard.setTabOrder(self.cboSectorTrailerAccessBits, self.txtSectorTrailerByte9)
        LinearFormatCard.setTabOrder(self.txtSectorTrailerByte9, self.btnLinearFormat)
        LinearFormatCard.setTabOrder(self.btnLinearFormat, self.cboBlockAccessBitsAKM1)
        LinearFormatCard.setTabOrder(self.cboBlockAccessBitsAKM1, self.cboSectorTrailerAccessBitsAKM1)
        LinearFormatCard.setTabOrder(self.cboSectorTrailerAccessBitsAKM1, self.txtSectorTrailerByte9AKM1)
        LinearFormatCard.setTabOrder(self.txtSectorTrailerByte9AKM1, self.btnLinearFormatAKM1)
        LinearFormatCard.setTabOrder(self.btnLinearFormatAKM1, self.cboBlockAccessBitsAKM2)
        LinearFormatCard.setTabOrder(self.cboBlockAccessBitsAKM2, self.cboSectorTrailerAccessBitsAKM2)
        LinearFormatCard.setTabOrder(self.cboSectorTrailerAccessBitsAKM2, self.txtSectorTrailerByte9AKM2)
        LinearFormatCard.setTabOrder(self.txtSectorTrailerByte9AKM2, self.btnLinearFormatAKM2)
        LinearFormatCard.setTabOrder(self.btnLinearFormatAKM2, self.cboBlockAccessBitsPK)
        LinearFormatCard.setTabOrder(self.cboBlockAccessBitsPK, self.cboSectorTrailerAccessBitsPK)
        LinearFormatCard.setTabOrder(self.cboSectorTrailerAccessBitsPK, self.txtSectorTrailerByte9PK)
        LinearFormatCard.setTabOrder(self.txtSectorTrailerByte9PK, self.btnLinearFormatPK)
        LinearFormatCard.setTabOrder(self.btnLinearFormatPK, self.rbAUTH1A)
        LinearFormatCard.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        LinearFormatCard.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        LinearFormatCard.setTabOrder(self.cboKeyIndex, self.chkKeyA)
        LinearFormatCard.setTabOrder(self.chkKeyA, self.chkKeyB)
        LinearFormatCard.setTabOrder(self.chkKeyB, self.txtSectorFormatted)
        LinearFormatCard.setTabOrder(self.txtSectorFormatted, self.txtSectorFormattedAKM1)
        LinearFormatCard.setTabOrder(self.txtSectorFormattedAKM1, self.txtSectorFormattedAKM2)
        LinearFormatCard.setTabOrder(self.txtSectorFormattedAKM2, self.txtSectorFormattedPK)

    def retranslateUi(self, LinearFormatCard):
        _translate = QtCore.QCoreApplication.translate
        LinearFormatCard.setWindowTitle(_translate("LinearFormatCard", "Dialog"))
        self.rbAUTH1A.setText(_translate("LinearFormatCard", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("LinearFormatCard", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("LinearFormatCard", "Key Index"))
        self.lblPKKeys.setText(_translate("LinearFormatCard", "PK Key"))
        self.lblFnError.setText(_translate("LinearFormatCard", "Function Error :"))
        self.chkKeyA.setText(_translate("LinearFormatCard", "Hex"))
        self.lblKeyA.setText(_translate("LinearFormatCard", "KEY A"))
        self.chkKeyB.setText(_translate("LinearFormatCard", "Hex"))
        self.lblKeyB.setText(_translate("LinearFormatCard", "KEY B"))
        self.lblBlockAccessBits.setText(_translate("LinearFormatCard", "Block Access Bits"))
        self.lblSectorTrailerAccessBits.setText(_translate("LinearFormatCard", "Sector Trailer  Access Bits"))
        self.lblSectorTrailerByte9.setText(_translate("LinearFormatCard", "Sector Trailer  Byte 9"))
        self.btnLinearFormat.setText(_translate("LinearFormatCard", "LINEAR FORMAT"))
        self.lblSectorFormatted.setText(_translate("LinearFormatCard", "Sector Formatted"))
        self.cboSectorTrailerAccessBits.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboSectorTrailerAccessBits.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboSectorTrailerAccessBits.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboSectorTrailerAccessBits.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboSectorTrailerAccessBits.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboSectorTrailerAccessBits.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboSectorTrailerAccessBits.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboSectorTrailerAccessBits.setItemText(7, _translate("LinearFormatCard", "7"))
        self.cboBlockAccessBits.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboBlockAccessBits.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboBlockAccessBits.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboBlockAccessBits.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboBlockAccessBits.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboBlockAccessBits.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboBlockAccessBits.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboBlockAccessBits.setItemText(7, _translate("LinearFormatCard", "7"))
        self.tabLinearFormatCard.setTabText(self.tabLinearFormatCard.indexOf(self.tbFormatCard), _translate("LinearFormatCard", "Format Card"))
        self.lblBlockAccessBitsAKM1.setText(_translate("LinearFormatCard", "Block Access Bits"))
        self.lblSectorTrailerAccessBitsAKM1.setText(_translate("LinearFormatCard", "Sector Trailer  Access Bits"))
        self.lblSectorTrailerByte9AKM1.setText(_translate("LinearFormatCard", "Sector Trailer  Byte 9"))
        self.btnLinearFormatAKM1.setText(_translate("LinearFormatCard", "LINEAR FORMAT"))
        self.lblSectorFormattedAKM1.setText(_translate("LinearFormatCard", "Sector Formatted"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboSectorTrailerAccessBitsAKM1.setItemText(7, _translate("LinearFormatCard", "7"))
        self.cboBlockAccessBitsAKM1.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboBlockAccessBitsAKM1.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboBlockAccessBitsAKM1.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboBlockAccessBitsAKM1.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboBlockAccessBitsAKM1.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboBlockAccessBitsAKM1.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboBlockAccessBitsAKM1.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboBlockAccessBitsAKM1.setItemText(7, _translate("LinearFormatCard", "7"))
        self.tabLinearFormatCard.setTabText(self.tabLinearFormatCard.indexOf(self.tbFormatCardAKM1), _translate("LinearFormatCard", "FormatCard AKM1"))
        self.lblBlockAccessBitsAKM2.setText(_translate("LinearFormatCard", "Block Access Bits"))
        self.lblSectorTrailerAccessBitsAKM2.setText(_translate("LinearFormatCard", "Sector Trailer  Access Bits"))
        self.lblSectorTrailerByte9AKM2.setText(_translate("LinearFormatCard", "Sector Trailer  Byte 9"))
        self.btnLinearFormatAKM2.setText(_translate("LinearFormatCard", "LINEAR FORMAT"))
        self.lblSectorFormattedAKM2.setText(_translate("LinearFormatCard", "Sector Formatted"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboSectorTrailerAccessBitsAKM2.setItemText(7, _translate("LinearFormatCard", "7"))
        self.cboBlockAccessBitsAKM2.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboBlockAccessBitsAKM2.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboBlockAccessBitsAKM2.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboBlockAccessBitsAKM2.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboBlockAccessBitsAKM2.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboBlockAccessBitsAKM2.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboBlockAccessBitsAKM2.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboBlockAccessBitsAKM2.setItemText(7, _translate("LinearFormatCard", "7"))
        self.tabLinearFormatCard.setTabText(self.tabLinearFormatCard.indexOf(self.tbFormatCardAKM2), _translate("LinearFormatCard", "FormatCard AKM2"))
        self.lblBlockAccessBitsPK.setText(_translate("LinearFormatCard", "Block Access Bits"))
        self.lblSectorTrailerAccessBitsPK.setText(_translate("LinearFormatCard", "Sector Trailer  Access Bits"))
        self.lblSectorTrailerByte9PK.setText(_translate("LinearFormatCard", "Sector Trailer  Byte 9"))
        self.btnLinearFormatPK.setText(_translate("LinearFormatCard", "LINEAR FORMAT"))
        self.lblSectorFormattedPK.setText(_translate("LinearFormatCard", "Sector Formatted"))
        self.cboSectorTrailerAccessBitsPK.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboSectorTrailerAccessBitsPK.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboSectorTrailerAccessBitsPK.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboSectorTrailerAccessBitsPK.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboSectorTrailerAccessBitsPK.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboSectorTrailerAccessBitsPK.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboSectorTrailerAccessBitsPK.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboSectorTrailerAccessBitsPK.setItemText(7, _translate("LinearFormatCard", "7"))
        self.cboBlockAccessBitsPK.setItemText(0, _translate("LinearFormatCard", "0"))
        self.cboBlockAccessBitsPK.setItemText(1, _translate("LinearFormatCard", "1"))
        self.cboBlockAccessBitsPK.setItemText(2, _translate("LinearFormatCard", "2"))
        self.cboBlockAccessBitsPK.setItemText(3, _translate("LinearFormatCard", "3"))
        self.cboBlockAccessBitsPK.setItemText(4, _translate("LinearFormatCard", "4"))
        self.cboBlockAccessBitsPK.setItemText(5, _translate("LinearFormatCard", "5"))
        self.cboBlockAccessBitsPK.setItemText(6, _translate("LinearFormatCard", "6"))
        self.cboBlockAccessBitsPK.setItemText(7, _translate("LinearFormatCard", "7"))
        self.tabLinearFormatCard.setTabText(self.tabLinearFormatCard.indexOf(self.tbFormatCardPK), _translate("LinearFormatCard", "FormatCard PK"))

