# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SectorTrailerWrite.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SectorTrailerWrite(object):
    def setupUi(self, SectorTrailerWrite):
        SectorTrailerWrite.setObjectName("SectorTrailerWrite")
        SectorTrailerWrite.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(SectorTrailerWrite)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 610, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.lblFnError = QtWidgets.QLabel(SectorTrailerWrite)
        self.lblFnError.setGeometry(QtCore.QRect(8, 340, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnValue = QtWidgets.QLabel(SectorTrailerWrite)
        self.lblFnValue.setGeometry(QtCore.QRect(118, 340, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnExplain = QtWidgets.QLabel(SectorTrailerWrite)
        self.lblFnExplain.setGeometry(QtCore.QRect(199, 340, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.fmKeyA = QtWidgets.QFrame(SectorTrailerWrite)
        self.fmKeyA.setGeometry(QtCore.QRect(4, 40, 300, 90))
        self.fmKeyA.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fmKeyA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmKeyA.setObjectName("fmKeyA")
        self.chkKeyA = QtWidgets.QCheckBox(self.fmKeyA)
        self.chkKeyA.setGeometry(QtCore.QRect(56, 57, 86, 21))
        self.chkKeyA.setObjectName("chkKeyA")
        self.lblKeyA = QtWidgets.QLabel(self.fmKeyA)
        self.lblKeyA.setGeometry(QtCore.QRect(1, 1, 300, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblKeyA.setFont(font)
        self.lblKeyA.setAutoFillBackground(False)
        self.lblKeyA.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lblKeyA.setFrameShape(QtWidgets.QFrame.Box)
        self.lblKeyA.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblKeyA.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKeyA.setObjectName("lblKeyA")
        self.fmKeyB = QtWidgets.QFrame(SectorTrailerWrite)
        self.fmKeyB.setGeometry(QtCore.QRect(308, 40, 300, 90))
        self.fmKeyB.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.fmKeyB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmKeyB.setObjectName("fmKeyB")
        self.chkKeyB = QtWidgets.QCheckBox(self.fmKeyB)
        self.chkKeyB.setGeometry(QtCore.QRect(56, 57, 86, 21))
        self.chkKeyB.setObjectName("chkKeyB")
        self.lblKeyB = QtWidgets.QLabel(self.fmKeyB)
        self.lblKeyB.setGeometry(QtCore.QRect(0, 1, 300, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblKeyB.setFont(font)
        self.lblKeyB.setAutoFillBackground(False)
        self.lblKeyB.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lblKeyB.setFrameShape(QtWidgets.QFrame.Box)
        self.lblKeyB.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblKeyB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKeyB.setObjectName("lblKeyB")
        self.tabSectorTrailerWrite = QtWidgets.QTabWidget(SectorTrailerWrite)
        self.tabSectorTrailerWrite.setGeometry(QtCore.QRect(0, 130, 611, 201))
        self.tabSectorTrailerWrite.setAutoFillBackground(True)
        self.tabSectorTrailerWrite.setObjectName("tabSectorTrailerWrite")
        self.tbSectorTrailerWrite = QtWidgets.QWidget()
        self.tbSectorTrailerWrite.setObjectName("tbSectorTrailerWrite")
        self.fmContainer = QtWidgets.QFrame(self.tbSectorTrailerWrite)
        self.fmContainer.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainer.setObjectName("fmContainer")
        self.lblAddressMode = QtWidgets.QLabel(self.fmContainer)
        self.lblAddressMode.setGeometry(QtCore.QRect(70, 13, 101, 16))
        self.lblAddressMode.setTextFormat(QtCore.Qt.AutoText)
        self.lblAddressMode.setObjectName("lblAddressMode")
        self.lblAccessBits0 = QtWidgets.QLabel(self.fmContainer)
        self.lblAccessBits0.setGeometry(QtCore.QRect(70, 74, 141, 16))
        self.lblAccessBits0.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits0.setObjectName("lblAccessBits0")
        self.lblBlockorSectorAccess = QtWidgets.QLabel(self.fmContainer)
        self.lblBlockorSectorAccess.setGeometry(QtCore.QRect(70, 41, 141, 16))
        self.lblBlockorSectorAccess.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockorSectorAccess.setObjectName("lblBlockorSectorAccess")
        self.btnSectorTrailerWrite = QtWidgets.QPushButton(self.fmContainer)
        self.btnSectorTrailerWrite.setGeometry(QtCore.QRect(350, 74, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSectorTrailerWrite.setFont(font)
        self.btnSectorTrailerWrite.setObjectName("btnSectorTrailerWrite")
        self.cboAccessBits0 = QtWidgets.QComboBox(self.fmContainer)
        self.cboAccessBits0.setGeometry(QtCore.QRect(221, 66, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits0.setFont(font)
        self.cboAccessBits0.setObjectName("cboAccessBits0")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAccessBits0.addItem("")
        self.cboAddressingMode = QtWidgets.QComboBox(self.fmContainer)
        self.cboAddressingMode.setGeometry(QtCore.QRect(221, 4, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAddressingMode.setFont(font)
        self.cboAddressingMode.setObjectName("cboAddressingMode")
        self.cboAddressingMode.addItem("")
        self.cboAddressingMode.addItem("")
        self.txtBlockOrSectorAddress = QtWidgets.QLineEdit(self.fmContainer)
        self.txtBlockOrSectorAddress.setGeometry(QtCore.QRect(221, 35, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockOrSectorAddress.setFont(font)
        self.txtBlockOrSectorAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockOrSectorAddress.setObjectName("txtBlockOrSectorAddress")
        self.lblTrailerAccessBits = QtWidgets.QLabel(self.fmContainer)
        self.lblTrailerAccessBits.setGeometry(QtCore.QRect(350, 13, 101, 16))
        self.lblTrailerAccessBits.setTextFormat(QtCore.Qt.AutoText)
        self.lblTrailerAccessBits.setObjectName("lblTrailerAccessBits")
        self.cboTrailerAccessBits = QtWidgets.QComboBox(self.fmContainer)
        self.cboTrailerAccessBits.setGeometry(QtCore.QRect(500, 5, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboTrailerAccessBits.setFont(font)
        self.cboTrailerAccessBits.setObjectName("cboTrailerAccessBits")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.cboTrailerAccessBits.addItem("")
        self.lblAccessBits1 = QtWidgets.QLabel(self.fmContainer)
        self.lblAccessBits1.setGeometry(QtCore.QRect(70, 104, 101, 16))
        self.lblAccessBits1.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits1.setObjectName("lblAccessBits1")
        self.cboAccessBits1 = QtWidgets.QComboBox(self.fmContainer)
        self.cboAccessBits1.setGeometry(QtCore.QRect(221, 97, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits1.setFont(font)
        self.cboAccessBits1.setObjectName("cboAccessBits1")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits1.addItem("")
        self.cboAccessBits2 = QtWidgets.QComboBox(self.fmContainer)
        self.cboAccessBits2.setGeometry(QtCore.QRect(221, 128, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits2.setFont(font)
        self.cboAccessBits2.setObjectName("cboAccessBits2")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.cboAccessBits2.addItem("")
        self.lblAccessBits2 = QtWidgets.QLabel(self.fmContainer)
        self.lblAccessBits2.setGeometry(QtCore.QRect(70, 135, 141, 16))
        self.lblAccessBits2.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits2.setObjectName("lblAccessBits2")
        self.txtSectorTrailerByte9 = QtWidgets.QLineEdit(self.fmContainer)
        self.txtSectorTrailerByte9.setGeometry(QtCore.QRect(500, 36, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9.setFont(font)
        self.txtSectorTrailerByte9.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9.setObjectName("txtSectorTrailerByte9")
        self.lblSectorTrailerByte9 = QtWidgets.QLabel(self.fmContainer)
        self.lblSectorTrailerByte9.setGeometry(QtCore.QRect(350, 41, 141, 16))
        self.lblSectorTrailerByte9.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9.setObjectName("lblSectorTrailerByte9")
        self.tabSectorTrailerWrite.addTab(self.tbSectorTrailerWrite, "")
        self.tbSectorTrailerWriteAKM1 = QtWidgets.QWidget()
        self.tbSectorTrailerWriteAKM1.setObjectName("tbSectorTrailerWriteAKM1")
        self.fmContainer_2 = QtWidgets.QFrame(self.tbSectorTrailerWriteAKM1)
        self.fmContainer_2.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainer_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainer_2.setObjectName("fmContainer_2")
        self.lblAddressModeAKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblAddressModeAKM1.setGeometry(QtCore.QRect(70, 13, 101, 16))
        self.lblAddressModeAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblAddressModeAKM1.setObjectName("lblAddressModeAKM1")
        self.lblAccessBits0AKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblAccessBits0AKM1.setGeometry(QtCore.QRect(70, 74, 141, 16))
        self.lblAccessBits0AKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits0AKM1.setObjectName("lblAccessBits0AKM1")
        self.lblBlockorSectorAccessAKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblBlockorSectorAccessAKM1.setGeometry(QtCore.QRect(70, 41, 141, 16))
        self.lblBlockorSectorAccessAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockorSectorAccessAKM1.setObjectName("lblBlockorSectorAccessAKM1")
        self.btnSectorTrailerWriteAKM1 = QtWidgets.QPushButton(self.fmContainer_2)
        self.btnSectorTrailerWriteAKM1.setGeometry(QtCore.QRect(350, 74, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSectorTrailerWriteAKM1.setFont(font)
        self.btnSectorTrailerWriteAKM1.setObjectName("btnSectorTrailerWriteAKM1")
        self.cboAccessBits0AKM1 = QtWidgets.QComboBox(self.fmContainer_2)
        self.cboAccessBits0AKM1.setGeometry(QtCore.QRect(221, 66, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits0AKM1.setFont(font)
        self.cboAccessBits0AKM1.setObjectName("cboAccessBits0AKM1")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAccessBits0AKM1.addItem("")
        self.cboAddressingModeAKM1 = QtWidgets.QComboBox(self.fmContainer_2)
        self.cboAddressingModeAKM1.setGeometry(QtCore.QRect(221, 4, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAddressingModeAKM1.setFont(font)
        self.cboAddressingModeAKM1.setObjectName("cboAddressingModeAKM1")
        self.cboAddressingModeAKM1.addItem("")
        self.cboAddressingModeAKM1.addItem("")
        self.txtBlockOrSectorAddressAKM1 = QtWidgets.QLineEdit(self.fmContainer_2)
        self.txtBlockOrSectorAddressAKM1.setGeometry(QtCore.QRect(221, 35, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockOrSectorAddressAKM1.setFont(font)
        self.txtBlockOrSectorAddressAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockOrSectorAddressAKM1.setObjectName("txtBlockOrSectorAddressAKM1")
        self.lblTrailerAccessBitsAKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblTrailerAccessBitsAKM1.setGeometry(QtCore.QRect(350, 13, 101, 16))
        self.lblTrailerAccessBitsAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblTrailerAccessBitsAKM1.setObjectName("lblTrailerAccessBitsAKM1")
        self.cboTrailerAccessBitsAKM1 = QtWidgets.QComboBox(self.fmContainer_2)
        self.cboTrailerAccessBitsAKM1.setGeometry(QtCore.QRect(500, 5, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboTrailerAccessBitsAKM1.setFont(font)
        self.cboTrailerAccessBitsAKM1.setObjectName("cboTrailerAccessBitsAKM1")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.cboTrailerAccessBitsAKM1.addItem("")
        self.lblAccessBits1AKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblAccessBits1AKM1.setGeometry(QtCore.QRect(70, 104, 101, 16))
        self.lblAccessBits1AKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits1AKM1.setObjectName("lblAccessBits1AKM1")
        self.cboAccessBits1AKM1 = QtWidgets.QComboBox(self.fmContainer_2)
        self.cboAccessBits1AKM1.setGeometry(QtCore.QRect(221, 97, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits1AKM1.setFont(font)
        self.cboAccessBits1AKM1.setObjectName("cboAccessBits1AKM1")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits1AKM1.addItem("")
        self.cboAccessBits2AKM1 = QtWidgets.QComboBox(self.fmContainer_2)
        self.cboAccessBits2AKM1.setGeometry(QtCore.QRect(221, 128, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits2AKM1.setFont(font)
        self.cboAccessBits2AKM1.setObjectName("cboAccessBits2AKM1")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.cboAccessBits2AKM1.addItem("")
        self.lblAccessBits2AKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblAccessBits2AKM1.setGeometry(QtCore.QRect(70, 135, 141, 16))
        self.lblAccessBits2AKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits2AKM1.setObjectName("lblAccessBits2AKM1")
        self.txtSectorTrailerByte9AKM1 = QtWidgets.QLineEdit(self.fmContainer_2)
        self.txtSectorTrailerByte9AKM1.setGeometry(QtCore.QRect(500, 36, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9AKM1.setFont(font)
        self.txtSectorTrailerByte9AKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9AKM1.setObjectName("txtSectorTrailerByte9AKM1")
        self.lblSectorTrailerByte9AKM1 = QtWidgets.QLabel(self.fmContainer_2)
        self.lblSectorTrailerByte9AKM1.setGeometry(QtCore.QRect(350, 41, 141, 16))
        self.lblSectorTrailerByte9AKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9AKM1.setObjectName("lblSectorTrailerByte9AKM1")
        self.tabSectorTrailerWrite.addTab(self.tbSectorTrailerWriteAKM1, "")
        self.tbSectorTrailerWriteAKM2 = QtWidgets.QWidget()
        self.tbSectorTrailerWriteAKM2.setObjectName("tbSectorTrailerWriteAKM2")
        self.fmContainerAKM2 = QtWidgets.QFrame(self.tbSectorTrailerWriteAKM2)
        self.fmContainerAKM2.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainerAKM2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainerAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainerAKM2.setObjectName("fmContainerAKM2")
        self.lblAddressModeAKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblAddressModeAKM2.setGeometry(QtCore.QRect(70, 13, 101, 16))
        self.lblAddressModeAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblAddressModeAKM2.setObjectName("lblAddressModeAKM2")
        self.lblAccessBits0AKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblAccessBits0AKM2.setGeometry(QtCore.QRect(70, 74, 141, 16))
        self.lblAccessBits0AKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits0AKM2.setObjectName("lblAccessBits0AKM2")
        self.lblBlockorSectorAccessAKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblBlockorSectorAccessAKM2.setGeometry(QtCore.QRect(70, 41, 141, 16))
        self.lblBlockorSectorAccessAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockorSectorAccessAKM2.setObjectName("lblBlockorSectorAccessAKM2")
        self.btnSectorTrailerWriteAKM2 = QtWidgets.QPushButton(self.fmContainerAKM2)
        self.btnSectorTrailerWriteAKM2.setGeometry(QtCore.QRect(350, 74, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSectorTrailerWriteAKM2.setFont(font)
        self.btnSectorTrailerWriteAKM2.setObjectName("btnSectorTrailerWriteAKM2")
        self.cboAccessBits0AKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboAccessBits0AKM2.setGeometry(QtCore.QRect(221, 66, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits0AKM2.setFont(font)
        self.cboAccessBits0AKM2.setObjectName("cboAccessBits0AKM2")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAccessBits0AKM2.addItem("")
        self.cboAddressingModeAKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboAddressingModeAKM2.setGeometry(QtCore.QRect(221, 4, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAddressingModeAKM2.setFont(font)
        self.cboAddressingModeAKM2.setObjectName("cboAddressingModeAKM2")
        self.cboAddressingModeAKM2.addItem("")
        self.cboAddressingModeAKM2.addItem("")
        self.txtBlockOrSectorAddressAKM2 = QtWidgets.QLineEdit(self.fmContainerAKM2)
        self.txtBlockOrSectorAddressAKM2.setGeometry(QtCore.QRect(221, 35, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockOrSectorAddressAKM2.setFont(font)
        self.txtBlockOrSectorAddressAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockOrSectorAddressAKM2.setObjectName("txtBlockOrSectorAddressAKM2")
        self.lblTrailerAccessBitsAKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblTrailerAccessBitsAKM2.setGeometry(QtCore.QRect(350, 13, 101, 16))
        self.lblTrailerAccessBitsAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblTrailerAccessBitsAKM2.setObjectName("lblTrailerAccessBitsAKM2")
        self.cboTrailerAccessBitsAKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboTrailerAccessBitsAKM2.setGeometry(QtCore.QRect(500, 5, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboTrailerAccessBitsAKM2.setFont(font)
        self.cboTrailerAccessBitsAKM2.setObjectName("cboTrailerAccessBitsAKM2")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.cboTrailerAccessBitsAKM2.addItem("")
        self.lblAccessBits1AKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblAccessBits1AKM2.setGeometry(QtCore.QRect(70, 104, 101, 16))
        self.lblAccessBits1AKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits1AKM2.setObjectName("lblAccessBits1AKM2")
        self.cboAccessBits1AKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboAccessBits1AKM2.setGeometry(QtCore.QRect(221, 97, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits1AKM2.setFont(font)
        self.cboAccessBits1AKM2.setObjectName("cboAccessBits1AKM2")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits1AKM2.addItem("")
        self.cboAccessBits2AKM2 = QtWidgets.QComboBox(self.fmContainerAKM2)
        self.cboAccessBits2AKM2.setGeometry(QtCore.QRect(221, 128, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits2AKM2.setFont(font)
        self.cboAccessBits2AKM2.setObjectName("cboAccessBits2AKM2")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.cboAccessBits2AKM2.addItem("")
        self.lblAccessBits2AKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblAccessBits2AKM2.setGeometry(QtCore.QRect(70, 135, 141, 16))
        self.lblAccessBits2AKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits2AKM2.setObjectName("lblAccessBits2AKM2")
        self.txtSectorTrailerByte9AKM2 = QtWidgets.QLineEdit(self.fmContainerAKM2)
        self.txtSectorTrailerByte9AKM2.setGeometry(QtCore.QRect(500, 36, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9AKM2.setFont(font)
        self.txtSectorTrailerByte9AKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9AKM2.setObjectName("txtSectorTrailerByte9AKM2")
        self.lblSectorTrailerByte9AKM2 = QtWidgets.QLabel(self.fmContainerAKM2)
        self.lblSectorTrailerByte9AKM2.setGeometry(QtCore.QRect(350, 41, 141, 16))
        self.lblSectorTrailerByte9AKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9AKM2.setObjectName("lblSectorTrailerByte9AKM2")
        self.tabSectorTrailerWrite.addTab(self.tbSectorTrailerWriteAKM2, "")
        self.tbSectorTrailerWritePK = QtWidgets.QWidget()
        self.tbSectorTrailerWritePK.setObjectName("tbSectorTrailerWritePK")
        self.fmContainerPK = QtWidgets.QFrame(self.tbSectorTrailerWritePK)
        self.fmContainerPK.setGeometry(QtCore.QRect(7, 5, 591, 161))
        self.fmContainerPK.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmContainerPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmContainerPK.setObjectName("fmContainerPK")
        self.lblAddressModePK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblAddressModePK.setGeometry(QtCore.QRect(70, 13, 101, 16))
        self.lblAddressModePK.setTextFormat(QtCore.Qt.AutoText)
        self.lblAddressModePK.setObjectName("lblAddressModePK")
        self.lblAccessBits0PK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblAccessBits0PK.setGeometry(QtCore.QRect(70, 74, 141, 16))
        self.lblAccessBits0PK.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits0PK.setObjectName("lblAccessBits0PK")
        self.lblBlockorSectorAccessPK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblBlockorSectorAccessPK.setGeometry(QtCore.QRect(70, 41, 141, 16))
        self.lblBlockorSectorAccessPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblBlockorSectorAccessPK.setObjectName("lblBlockorSectorAccessPK")
        self.btnSectorTrailerWritePK = QtWidgets.QPushButton(self.fmContainerPK)
        self.btnSectorTrailerWritePK.setGeometry(QtCore.QRect(350, 74, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSectorTrailerWritePK.setFont(font)
        self.btnSectorTrailerWritePK.setObjectName("btnSectorTrailerWritePK")
        self.cboAccessBits0PK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboAccessBits0PK.setGeometry(QtCore.QRect(221, 66, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits0PK.setFont(font)
        self.cboAccessBits0PK.setObjectName("cboAccessBits0PK")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAccessBits0PK.addItem("")
        self.cboAddressingModePK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboAddressingModePK.setGeometry(QtCore.QRect(221, 4, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAddressingModePK.setFont(font)
        self.cboAddressingModePK.setObjectName("cboAddressingModePK")
        self.cboAddressingModePK.addItem("")
        self.cboAddressingModePK.addItem("")
        self.txtBlockOrSectorAddressPK = QtWidgets.QLineEdit(self.fmContainerPK)
        self.txtBlockOrSectorAddressPK.setGeometry(QtCore.QRect(221, 35, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockOrSectorAddressPK.setFont(font)
        self.txtBlockOrSectorAddressPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockOrSectorAddressPK.setObjectName("txtBlockOrSectorAddressPK")
        self.lblTrailerAccessBitsPK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblTrailerAccessBitsPK.setGeometry(QtCore.QRect(350, 13, 101, 16))
        self.lblTrailerAccessBitsPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblTrailerAccessBitsPK.setObjectName("lblTrailerAccessBitsPK")
        self.cboTrailerAccessBitsPK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboTrailerAccessBitsPK.setGeometry(QtCore.QRect(500, 5, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboTrailerAccessBitsPK.setFont(font)
        self.cboTrailerAccessBitsPK.setObjectName("cboTrailerAccessBitsPK")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.cboTrailerAccessBitsPK.addItem("")
        self.lblAccessBits1PK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblAccessBits1PK.setGeometry(QtCore.QRect(70, 104, 101, 16))
        self.lblAccessBits1PK.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits1PK.setObjectName("lblAccessBits1PK")
        self.cboAccessBits1PK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboAccessBits1PK.setGeometry(QtCore.QRect(221, 97, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits1PK.setFont(font)
        self.cboAccessBits1PK.setObjectName("cboAccessBits1PK")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits1PK.addItem("")
        self.cboAccessBits2PK = QtWidgets.QComboBox(self.fmContainerPK)
        self.cboAccessBits2PK.setGeometry(QtCore.QRect(221, 128, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.cboAccessBits2PK.setFont(font)
        self.cboAccessBits2PK.setObjectName("cboAccessBits2PK")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.cboAccessBits2PK.addItem("")
        self.lblAccessBits2PK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblAccessBits2PK.setGeometry(QtCore.QRect(70, 135, 141, 16))
        self.lblAccessBits2PK.setTextFormat(QtCore.Qt.AutoText)
        self.lblAccessBits2PK.setObjectName("lblAccessBits2PK")
        self.txtSectorTrailerByte9PK = QtWidgets.QLineEdit(self.fmContainerPK)
        self.txtSectorTrailerByte9PK.setGeometry(QtCore.QRect(500, 36, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorTrailerByte9PK.setFont(font)
        self.txtSectorTrailerByte9PK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorTrailerByte9PK.setObjectName("txtSectorTrailerByte9PK")
        self.lblSectorTrailerByte9PK = QtWidgets.QLabel(self.fmContainerPK)
        self.lblSectorTrailerByte9PK.setGeometry(QtCore.QRect(350, 41, 141, 16))
        self.lblSectorTrailerByte9PK.setTextFormat(QtCore.Qt.AutoText)
        self.lblSectorTrailerByte9PK.setObjectName("lblSectorTrailerByte9PK")
        self.tabSectorTrailerWrite.addTab(self.tbSectorTrailerWritePK, "")

        self.retranslateUi(SectorTrailerWrite)
        self.tabSectorTrailerWrite.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SectorTrailerWrite)
        SectorTrailerWrite.setTabOrder(self.tabSectorTrailerWrite, self.cboAddressingMode)
        SectorTrailerWrite.setTabOrder(self.cboAddressingMode, self.txtBlockOrSectorAddress)
        SectorTrailerWrite.setTabOrder(self.txtBlockOrSectorAddress, self.cboAccessBits0)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits0, self.cboAccessBits1)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits1, self.cboAccessBits2)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits2, self.cboTrailerAccessBits)
        SectorTrailerWrite.setTabOrder(self.cboTrailerAccessBits, self.cboAddressingModeAKM1)
        SectorTrailerWrite.setTabOrder(self.cboAddressingModeAKM1, self.txtBlockOrSectorAddressAKM1)
        SectorTrailerWrite.setTabOrder(self.txtBlockOrSectorAddressAKM1, self.txtSectorTrailerByte9)
        SectorTrailerWrite.setTabOrder(self.txtSectorTrailerByte9, self.btnSectorTrailerWrite)
        SectorTrailerWrite.setTabOrder(self.btnSectorTrailerWrite, self.cboAccessBits0AKM1)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits0AKM1, self.cboAccessBits1AKM1)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits1AKM1, self.cboAccessBits2AKM1)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits2AKM1, self.cboTrailerAccessBitsAKM1)
        SectorTrailerWrite.setTabOrder(self.cboTrailerAccessBitsAKM1, self.txtSectorTrailerByte9AKM1)
        SectorTrailerWrite.setTabOrder(self.txtSectorTrailerByte9AKM1, self.btnSectorTrailerWriteAKM1)
        SectorTrailerWrite.setTabOrder(self.btnSectorTrailerWriteAKM1, self.cboAddressingModeAKM2)
        SectorTrailerWrite.setTabOrder(self.cboAddressingModeAKM2, self.txtBlockOrSectorAddressAKM2)
        SectorTrailerWrite.setTabOrder(self.txtBlockOrSectorAddressAKM2, self.cboAccessBits0AKM2)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits0AKM2, self.cboAccessBits1AKM2)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits1AKM2, self.cboAccessBits2AKM2)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits2AKM2, self.cboTrailerAccessBitsAKM2)
        SectorTrailerWrite.setTabOrder(self.cboTrailerAccessBitsAKM2, self.txtSectorTrailerByte9AKM2)
        SectorTrailerWrite.setTabOrder(self.txtSectorTrailerByte9AKM2, self.btnSectorTrailerWriteAKM2)
        SectorTrailerWrite.setTabOrder(self.btnSectorTrailerWriteAKM2, self.cboAddressingModePK)
        SectorTrailerWrite.setTabOrder(self.cboAddressingModePK, self.txtBlockOrSectorAddressPK)
        SectorTrailerWrite.setTabOrder(self.txtBlockOrSectorAddressPK, self.cboAccessBits0PK)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits0PK, self.cboAccessBits1PK)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits1PK, self.cboAccessBits2PK)
        SectorTrailerWrite.setTabOrder(self.cboAccessBits2PK, self.cboTrailerAccessBitsPK)
        SectorTrailerWrite.setTabOrder(self.cboTrailerAccessBitsPK, self.txtSectorTrailerByte9PK)
        SectorTrailerWrite.setTabOrder(self.txtSectorTrailerByte9PK, self.btnSectorTrailerWritePK)
        SectorTrailerWrite.setTabOrder(self.btnSectorTrailerWritePK, self.rbAUTH1A)
        SectorTrailerWrite.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        SectorTrailerWrite.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        SectorTrailerWrite.setTabOrder(self.cboKeyIndex, self.chkKeyA)
        SectorTrailerWrite.setTabOrder(self.chkKeyA, self.chkKeyB)
        #=======================================================================
        # SectorTrailerWrite.setTabOrder(self.chkKeyB, SectorTrailerWrite.btnLinearFormat_2)
        # SectorTrailerWrite.setTabOrder(SectorTrailerWrite.btnLinearFormat_2, SectorTrailerWrite.cboSectorTrailerAccessBits_3)
        # SectorTrailerWrite.setTabOrder(SectorTrailerWrite.cboSectorTrailerAccessBits_3, SectorTrailerWrite.cboBlockAccessBits_4)
        # SectorTrailerWrite.setTabOrder(SectorTrailerWrite.cboBlockAccessBits_4, SectorTrailerWrite.txtSectorTrailerByte9_2)
        # SectorTrailerWrite.setTabOrder(SectorTrailerWrite.txtSectorTrailerByte9_2, SectorTrailerWrite.cboBlockAccessBits_5)
        # SectorTrailerWrite.setTabOrder(SectorTrailerWrite.cboBlockAccessBits_5, SectorTrailerWrite.cboBlockAccessBits_6)
        # SectorTrailerWrite.setTabOrder(SectorTrailerWrite.cboBlockAccessBits_6, SectorTrailerWrite.cboSectorTrailerAccessBits_4)
        #=======================================================================

    def retranslateUi(self, SectorTrailerWrite):
        _translate = QtCore.QCoreApplication.translate
        SectorTrailerWrite.setWindowTitle(_translate("SectorTrailerWrite", "Dialog"))
        self.rbAUTH1A.setText(_translate("SectorTrailerWrite", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("SectorTrailerWrite", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("SectorTrailerWrite", "Key Index"))
        self.lblPKKeys.setText(_translate("SectorTrailerWrite", "PK Key"))
        self.lblFnError.setText(_translate("SectorTrailerWrite", "Function Error :"))
        self.chkKeyA.setText(_translate("SectorTrailerWrite", "Hex"))
        self.lblKeyA.setText(_translate("SectorTrailerWrite", "KEY A"))
        self.chkKeyB.setText(_translate("SectorTrailerWrite", "Hex"))
        self.lblKeyB.setText(_translate("SectorTrailerWrite", "KEY B"))
        self.lblAddressMode.setText(_translate("SectorTrailerWrite", "Addressing Mod"))
        self.lblAccessBits0.setText(_translate("SectorTrailerWrite", "Access Bits 0"))
        self.lblBlockorSectorAccess.setText(_translate("SectorTrailerWrite", "Block or Sector Access"))
        self.btnSectorTrailerWrite.setText(_translate("SectorTrailerWrite", "SECTOR WRITE"))
        self.cboAccessBits0.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits0.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits0.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits0.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits0.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits0.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits0.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits0.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAddressingMode.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAddressingMode.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.lblTrailerAccessBits.setText(_translate("SectorTrailerWrite", "Trailer Access Bits"))
        self.cboTrailerAccessBits.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboTrailerAccessBits.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboTrailerAccessBits.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboTrailerAccessBits.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboTrailerAccessBits.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboTrailerAccessBits.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboTrailerAccessBits.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboTrailerAccessBits.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits1.setText(_translate("SectorTrailerWrite", "Access Bits 1"))
        self.cboAccessBits1.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits1.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits1.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits1.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits1.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits1.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits1.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits1.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAccessBits2.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits2.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits2.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits2.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits2.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits2.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits2.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits2.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits2.setText(_translate("SectorTrailerWrite", "Access Bits 2"))
        self.lblSectorTrailerByte9.setText(_translate("SectorTrailerWrite", "Sector Trailer  Byte 9"))
        self.tabSectorTrailerWrite.setTabText(self.tabSectorTrailerWrite.indexOf(self.tbSectorTrailerWrite), _translate("SectorTrailerWrite", "SectorTrailer Write"))
        self.lblAddressModeAKM1.setText(_translate("SectorTrailerWrite", "Addressing Mod"))
        self.lblAccessBits0AKM1.setText(_translate("SectorTrailerWrite", "Access Bits 0"))
        self.lblBlockorSectorAccessAKM1.setText(_translate("SectorTrailerWrite", "Block or Sector Access"))
        self.btnSectorTrailerWriteAKM1.setText(_translate("SectorTrailerWrite", "SECTOR WRITE"))
        self.cboAccessBits0AKM1.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits0AKM1.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits0AKM1.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits0AKM1.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits0AKM1.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits0AKM1.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits0AKM1.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits0AKM1.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAddressingModeAKM1.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAddressingModeAKM1.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.lblTrailerAccessBitsAKM1.setText(_translate("SectorTrailerWrite", "Trailer Access Bits"))
        self.cboTrailerAccessBitsAKM1.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboTrailerAccessBitsAKM1.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboTrailerAccessBitsAKM1.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboTrailerAccessBitsAKM1.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboTrailerAccessBitsAKM1.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboTrailerAccessBitsAKM1.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboTrailerAccessBitsAKM1.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboTrailerAccessBitsAKM1.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits1AKM1.setText(_translate("SectorTrailerWrite", "Access Bits 1"))
        self.cboAccessBits1AKM1.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits1AKM1.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits1AKM1.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits1AKM1.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits1AKM1.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits1AKM1.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits1AKM1.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits1AKM1.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAccessBits2AKM1.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits2AKM1.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits2AKM1.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits2AKM1.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits2AKM1.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits2AKM1.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits2AKM1.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits2AKM1.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits2AKM1.setText(_translate("SectorTrailerWrite", "Access Bits 2"))
        self.lblSectorTrailerByte9AKM1.setText(_translate("SectorTrailerWrite", "Sector Trailer  Byte 9"))
        self.tabSectorTrailerWrite.setTabText(self.tabSectorTrailerWrite.indexOf(self.tbSectorTrailerWriteAKM1), _translate("SectorTrailerWrite", "SectorTrailer Write AKM1"))
        self.lblAddressModeAKM2.setText(_translate("SectorTrailerWrite", "Addressing Mod"))
        self.lblAccessBits0AKM2.setText(_translate("SectorTrailerWrite", "Access Bits 0"))
        self.lblBlockorSectorAccessAKM2.setText(_translate("SectorTrailerWrite", "Block or Sector Access"))
        self.btnSectorTrailerWriteAKM2.setText(_translate("SectorTrailerWrite", "SECTOR WRITE"))
        self.cboAccessBits0AKM2.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits0AKM2.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits0AKM2.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits0AKM2.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits0AKM2.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits0AKM2.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits0AKM2.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits0AKM2.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAddressingModeAKM2.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAddressingModeAKM2.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.lblTrailerAccessBitsAKM2.setText(_translate("SectorTrailerWrite", "Trailer Access Bits"))
        self.cboTrailerAccessBitsAKM2.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboTrailerAccessBitsAKM2.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboTrailerAccessBitsAKM2.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboTrailerAccessBitsAKM2.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboTrailerAccessBitsAKM2.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboTrailerAccessBitsAKM2.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboTrailerAccessBitsAKM2.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboTrailerAccessBitsAKM2.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits1AKM2.setText(_translate("SectorTrailerWrite", "Access Bits 1"))
        self.cboAccessBits1AKM2.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits1AKM2.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits1AKM2.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits1AKM2.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits1AKM2.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits1AKM2.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits1AKM2.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits1AKM2.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAccessBits2AKM2.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits2AKM2.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits2AKM2.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits2AKM2.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits2AKM2.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits2AKM2.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits2AKM2.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits2AKM2.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits2AKM2.setText(_translate("SectorTrailerWrite", "Access Bits 2"))
        self.lblSectorTrailerByte9AKM2.setText(_translate("SectorTrailerWrite", "Sector Trailer  Byte 9"))
        self.tabSectorTrailerWrite.setTabText(self.tabSectorTrailerWrite.indexOf(self.tbSectorTrailerWriteAKM2), _translate("SectorTrailerWrite", "SectorTrailer Write AKM2"))
        self.lblAddressModePK.setText(_translate("SectorTrailerWrite", "Addressing Mod"))
        self.lblAccessBits0PK.setText(_translate("SectorTrailerWrite", "Access Bits 0"))
        self.lblBlockorSectorAccessPK.setText(_translate("SectorTrailerWrite", "Block or Sector Access"))
        self.btnSectorTrailerWritePK.setText(_translate("SectorTrailerWrite", "SECTOR WRITE"))
        self.cboAccessBits0PK.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits0PK.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits0PK.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits0PK.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits0PK.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits0PK.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits0PK.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits0PK.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAddressingModePK.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAddressingModePK.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.lblTrailerAccessBitsPK.setText(_translate("SectorTrailerWrite", "Trailer Access Bits"))
        self.cboTrailerAccessBitsPK.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboTrailerAccessBitsPK.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboTrailerAccessBitsPK.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboTrailerAccessBitsPK.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboTrailerAccessBitsPK.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboTrailerAccessBitsPK.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboTrailerAccessBitsPK.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboTrailerAccessBitsPK.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits1PK.setText(_translate("SectorTrailerWrite", "Access Bits 1"))
        self.cboAccessBits1PK.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits1PK.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits1PK.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits1PK.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits1PK.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits1PK.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits1PK.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits1PK.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.cboAccessBits2PK.setItemText(0, _translate("SectorTrailerWrite", "0"))
        self.cboAccessBits2PK.setItemText(1, _translate("SectorTrailerWrite", "1"))
        self.cboAccessBits2PK.setItemText(2, _translate("SectorTrailerWrite", "2"))
        self.cboAccessBits2PK.setItemText(3, _translate("SectorTrailerWrite", "3"))
        self.cboAccessBits2PK.setItemText(4, _translate("SectorTrailerWrite", "4"))
        self.cboAccessBits2PK.setItemText(5, _translate("SectorTrailerWrite", "5"))
        self.cboAccessBits2PK.setItemText(6, _translate("SectorTrailerWrite", "6"))
        self.cboAccessBits2PK.setItemText(7, _translate("SectorTrailerWrite", "7"))
        self.lblAccessBits2PK.setText(_translate("SectorTrailerWrite", "Access Bits 2"))
        self.lblSectorTrailerByte9PK.setText(_translate("SectorTrailerWrite", "Sector Trailer  Byte 9"))
        self.tabSectorTrailerWrite.setTabText(self.tabSectorTrailerWrite.indexOf(self.tbSectorTrailerWritePK), _translate("SectorTrailerWrite", "SectorTrailer Write PK"))

