# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ValueBlockIncrDecr.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ValueBlockIncremDecrem(object):
    def setupUi(self, ValueBlockIncremDecrem):
        ValueBlockIncremDecrem.setObjectName("ValueBlockIncremDecrem")
        ValueBlockIncremDecrem.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(ValueBlockIncremDecrem)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.tabValueBlockIncrDecr = QtWidgets.QTabWidget(ValueBlockIncremDecrem)
        self.tabValueBlockIncrDecr.setGeometry(QtCore.QRect(4, 48, 600, 290))
        self.tabValueBlockIncrDecr.setObjectName("tabValueBlockIncrDecr")
        self.tbValueBlockIncr = QtWidgets.QWidget()
        self.tbValueBlockIncr.setObjectName("tbValueBlockIncr")
        self.fmValueBlockIncr = QtWidgets.QFrame(self.tbValueBlockIncr)
        self.fmValueBlockIncr.setGeometry(QtCore.QRect(10, 10, 281, 120))
        self.fmValueBlockIncr.setAutoFillBackground(True)
        self.fmValueBlockIncr.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncr.setObjectName("fmValueBlockIncr")
        self.lblHeaderVBIncr = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblHeaderVBIncr.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBIncr.setFont(font)
        self.lblHeaderVBIncr.setAutoFillBackground(False)
        self.lblHeaderVBIncr.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBIncr.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBIncr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBIncr.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBIncr.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBIncr.setObjectName("lblHeaderVBIncr")
        self.lblBlockAddress = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblBlockAddress.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddress.setFont(font)
        self.lblBlockAddress.setObjectName("lblBlockAddress")
        self.txtBlockAddressIncr = QtWidgets.QLineEdit(self.fmValueBlockIncr)
        self.txtBlockAddressIncr.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncr.setFont(font)
        self.txtBlockAddressIncr.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncr.setObjectName("txtBlockAddressIncr")
        self.btnIncrementValue = QtWidgets.QPushButton(self.fmValueBlockIncr)
        self.btnIncrementValue.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValue.setFont(font)
        self.btnIncrementValue.setObjectName("btnIncrementValue")
        self.lblIncrementValue = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblIncrementValue.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValue.setFont(font)
        self.lblIncrementValue.setObjectName("lblIncrementValue")
        self.txtIncrementValue = QtWidgets.QLineEdit(self.fmValueBlockIncr)
        self.txtIncrementValue.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValue.setFont(font)
        self.txtIncrementValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValue.setReadOnly(False)
        self.txtIncrementValue.setObjectName("txtIncrementValue")
        self.fmValueBlockIncrAKM1 = QtWidgets.QFrame(self.tbValueBlockIncr)
        self.fmValueBlockIncrAKM1.setGeometry(QtCore.QRect(300, 10, 281, 120))
        self.fmValueBlockIncrAKM1.setAutoFillBackground(True)
        self.fmValueBlockIncrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncrAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncrAKM1.setObjectName("fmValueBlockIncrAKM1")
        self.lblHeaderVBIncrAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblHeaderVBIncrAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBIncrAKM1.setFont(font)
        self.lblHeaderVBIncrAKM1.setAutoFillBackground(False)
        self.lblHeaderVBIncrAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBIncrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBIncrAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBIncrAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBIncrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBIncrAKM1.setObjectName("lblHeaderVBIncrAKM1")
        self.lblBlockAddressAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblBlockAddressAKM1.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressAKM1.setFont(font)
        self.lblBlockAddressAKM1.setObjectName("lblBlockAddressAKM1")
        self.txtBlockAddressIncrAKM1 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM1)
        self.txtBlockAddressIncrAKM1.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncrAKM1.setFont(font)
        self.txtBlockAddressIncrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncrAKM1.setObjectName("txtBlockAddressIncrAKM1")
        self.btnIncrementValueAKM1 = QtWidgets.QPushButton(self.fmValueBlockIncrAKM1)
        self.btnIncrementValueAKM1.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValueAKM1.setFont(font)
        self.btnIncrementValueAKM1.setObjectName("btnIncrementValueAKM1")
        self.lblIncrementValueAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblIncrementValueAKM1.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValueAKM1.setFont(font)
        self.lblIncrementValueAKM1.setObjectName("lblIncrementValueAKM1")
        self.txtIncrementValueAKM1 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM1)
        self.txtIncrementValueAKM1.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValueAKM1.setFont(font)
        self.txtIncrementValueAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValueAKM1.setReadOnly(False)
        self.txtIncrementValueAKM1.setObjectName("txtIncrementValueAKM1")
        self.fmValueBlockIncrAKM2 = QtWidgets.QFrame(self.tbValueBlockIncr)
        self.fmValueBlockIncrAKM2.setGeometry(QtCore.QRect(10, 134, 281, 120))
        self.fmValueBlockIncrAKM2.setAutoFillBackground(True)
        self.fmValueBlockIncrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncrAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncrAKM2.setObjectName("fmValueBlockIncrAKM2")
        self.lblHeaderVBIncrAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblHeaderVBIncrAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBIncrAKM2.setFont(font)
        self.lblHeaderVBIncrAKM2.setAutoFillBackground(False)
        self.lblHeaderVBIncrAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBIncrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBIncrAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBIncrAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBIncrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBIncrAKM2.setObjectName("lblHeaderVBIncrAKM2")
        self.lblBlockAddressAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblBlockAddressAKM2.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressAKM2.setFont(font)
        self.lblBlockAddressAKM2.setObjectName("lblBlockAddressAKM2")
        self.txtBlockAddressIncrAKM2 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM2)
        self.txtBlockAddressIncrAKM2.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncrAKM2.setFont(font)
        self.txtBlockAddressIncrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncrAKM2.setObjectName("txtBlockAddressIncrAKM2")
        self.btnIncrementValueAKM2 = QtWidgets.QPushButton(self.fmValueBlockIncrAKM2)
        self.btnIncrementValueAKM2.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValueAKM2.setFont(font)
        self.btnIncrementValueAKM2.setObjectName("btnIncrementValueAKM2")
        self.lblIncrementValueAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblIncrementValueAKM2.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValueAKM2.setFont(font)
        self.lblIncrementValueAKM2.setObjectName("lblIncrementValueAKM2")
        self.txtIncrementValueAKM2 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM2)
        self.txtIncrementValueAKM2.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValueAKM2.setFont(font)
        self.txtIncrementValueAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValueAKM2.setReadOnly(False)
        self.txtIncrementValueAKM2.setObjectName("txtIncrementValueAKM2")
        self.fmValueBlockIncrPK = QtWidgets.QFrame(self.tbValueBlockIncr)
        self.fmValueBlockIncrPK.setGeometry(QtCore.QRect(300, 134, 281, 120))
        self.fmValueBlockIncrPK.setAutoFillBackground(True)
        self.fmValueBlockIncrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncrPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncrPK.setObjectName("fmValueBlockIncrPK")
        self.lblHeaderVBIncrAKM1_3 = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblHeaderVBIncrAKM1_3.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBIncrAKM1_3.setFont(font)
        self.lblHeaderVBIncrAKM1_3.setAutoFillBackground(False)
        self.lblHeaderVBIncrAKM1_3.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBIncrAKM1_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBIncrAKM1_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBIncrAKM1_3.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBIncrAKM1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBIncrAKM1_3.setObjectName("lblHeaderVBIncrAKM1_3")
        self.lblBlockAddressPK = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblBlockAddressPK.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressPK.setFont(font)
        self.lblBlockAddressPK.setObjectName("lblBlockAddressPK")
        self.txtBlockAddressIncrPK = QtWidgets.QLineEdit(self.fmValueBlockIncrPK)
        self.txtBlockAddressIncrPK.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncrPK.setFont(font)
        self.txtBlockAddressIncrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncrPK.setObjectName("txtBlockAddressIncrPK")
        self.btnIncrementValuePK = QtWidgets.QPushButton(self.fmValueBlockIncrPK)
        self.btnIncrementValuePK.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValuePK.setFont(font)
        self.btnIncrementValuePK.setObjectName("btnIncrementValuePK")
        self.lblIncrementValuePK = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblIncrementValuePK.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValuePK.setFont(font)
        self.lblIncrementValuePK.setObjectName("lblIncrementValuePK")
        self.txtIncrementValuePK = QtWidgets.QLineEdit(self.fmValueBlockIncrPK)
        self.txtIncrementValuePK.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValuePK.setFont(font)
        self.txtIncrementValuePK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValuePK.setReadOnly(False)
        self.txtIncrementValuePK.setObjectName("txtIncrementValuePK")
        self.tabValueBlockIncrDecr.addTab(self.tbValueBlockIncr, "")
        self.tbValueBlockDecr = QtWidgets.QWidget()
        self.tbValueBlockDecr.setObjectName("tbValueBlockDecr")
        self.fmValueBlockDecrAKM1 = QtWidgets.QFrame(self.tbValueBlockDecr)
        self.fmValueBlockDecrAKM1.setGeometry(QtCore.QRect(300, 10, 281, 120))
        self.fmValueBlockDecrAKM1.setAutoFillBackground(True)
        self.fmValueBlockDecrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecrAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecrAKM1.setObjectName("fmValueBlockDecrAKM1")
        self.lblHeaderVBDecrAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblHeaderVBDecrAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBDecrAKM1.setFont(font)
        self.lblHeaderVBDecrAKM1.setAutoFillBackground(False)
        self.lblHeaderVBDecrAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBDecrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBDecrAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBDecrAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBDecrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBDecrAKM1.setObjectName("lblHeaderVBDecrAKM1")
        self.lblBlockAddressDecrAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblBlockAddressDecrAKM1.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecrAKM1.setFont(font)
        self.lblBlockAddressDecrAKM1.setObjectName("lblBlockAddressDecrAKM1")
        self.txtBlockAddressDecrAKM1 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM1)
        self.txtBlockAddressDecrAKM1.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecrAKM1.setFont(font)
        self.txtBlockAddressDecrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecrAKM1.setObjectName("txtBlockAddressDecrAKM1")
        self.btnDecrementValueAKM1 = QtWidgets.QPushButton(self.fmValueBlockDecrAKM1)
        self.btnDecrementValueAKM1.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValueAKM1.setFont(font)
        self.btnDecrementValueAKM1.setObjectName("btnDecrementValueAKM1")
        self.lblDecrementValueAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblDecrementValueAKM1.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValueAKM1.setFont(font)
        self.lblDecrementValueAKM1.setObjectName("lblDecrementValueAKM1")
        self.txtDecrementValueAKM1 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM1)
        self.txtDecrementValueAKM1.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValueAKM1.setFont(font)
        self.txtDecrementValueAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValueAKM1.setReadOnly(False)
        self.txtDecrementValueAKM1.setObjectName("txtDecrementValueAKM1")
        self.fmValueBlockDecrPK = QtWidgets.QFrame(self.tbValueBlockDecr)
        self.fmValueBlockDecrPK.setGeometry(QtCore.QRect(300, 134, 281, 120))
        self.fmValueBlockDecrPK.setAutoFillBackground(True)
        self.fmValueBlockDecrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecrPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecrPK.setObjectName("fmValueBlockDecrPK")
        self.lblHeaderVBDecrPK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblHeaderVBDecrPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBDecrPK.setFont(font)
        self.lblHeaderVBDecrPK.setAutoFillBackground(False)
        self.lblHeaderVBDecrPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBDecrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBDecrPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBDecrPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBDecrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBDecrPK.setObjectName("lblHeaderVBDecrPK")
        self.lblBlockAddressDecrPK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblBlockAddressDecrPK.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecrPK.setFont(font)
        self.lblBlockAddressDecrPK.setObjectName("lblBlockAddressDecrPK")
        self.txtBlockAddressDecrPK = QtWidgets.QLineEdit(self.fmValueBlockDecrPK)
        self.txtBlockAddressDecrPK.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecrPK.setFont(font)
        self.txtBlockAddressDecrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecrPK.setObjectName("txtBlockAddressDecrPK")
        self.btnDecrementValuePK = QtWidgets.QPushButton(self.fmValueBlockDecrPK)
        self.btnDecrementValuePK.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValuePK.setFont(font)
        self.btnDecrementValuePK.setObjectName("btnDecrementValuePK")
        self.lblDecrementValuePK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblDecrementValuePK.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValuePK.setFont(font)
        self.lblDecrementValuePK.setObjectName("lblDecrementValuePK")
        self.txtDecrementValuePK = QtWidgets.QLineEdit(self.fmValueBlockDecrPK)
        self.txtDecrementValuePK.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValuePK.setFont(font)
        self.txtDecrementValuePK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValuePK.setReadOnly(False)
        self.txtDecrementValuePK.setObjectName("txtDecrementValuePK")
        self.fmValueBlockDecrAKM2 = QtWidgets.QFrame(self.tbValueBlockDecr)
        self.fmValueBlockDecrAKM2.setGeometry(QtCore.QRect(10, 134, 281, 120))
        self.fmValueBlockDecrAKM2.setAutoFillBackground(True)
        self.fmValueBlockDecrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecrAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecrAKM2.setObjectName("fmValueBlockDecrAKM2")
        self.lblHeaderVBDecrAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblHeaderVBDecrAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBDecrAKM2.setFont(font)
        self.lblHeaderVBDecrAKM2.setAutoFillBackground(False)
        self.lblHeaderVBDecrAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBDecrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBDecrAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBDecrAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBDecrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBDecrAKM2.setObjectName("lblHeaderVBDecrAKM2")
        self.lblBlockAddressDecrAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblBlockAddressDecrAKM2.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecrAKM2.setFont(font)
        self.lblBlockAddressDecrAKM2.setObjectName("lblBlockAddressDecrAKM2")
        self.txtBlockAddressDecrAKM2 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM2)
        self.txtBlockAddressDecrAKM2.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecrAKM2.setFont(font)
        self.txtBlockAddressDecrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecrAKM2.setObjectName("txtBlockAddressDecrAKM2")
        self.btnDecrementValueAKM2 = QtWidgets.QPushButton(self.fmValueBlockDecrAKM2)
        self.btnDecrementValueAKM2.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValueAKM2.setFont(font)
        self.btnDecrementValueAKM2.setObjectName("btnDecrementValueAKM2")
        self.lblDecrementValueAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblDecrementValueAKM2.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValueAKM2.setFont(font)
        self.lblDecrementValueAKM2.setObjectName("lblDecrementValueAKM2")
        self.txtDecrementValueAKM2 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM2)
        self.txtDecrementValueAKM2.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValueAKM2.setFont(font)
        self.txtDecrementValueAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValueAKM2.setReadOnly(False)
        self.txtDecrementValueAKM2.setObjectName("txtDecrementValueAKM2")
        self.fmValueBlockDecr = QtWidgets.QFrame(self.tbValueBlockDecr)
        self.fmValueBlockDecr.setGeometry(QtCore.QRect(10, 10, 281, 120))
        self.fmValueBlockDecr.setAutoFillBackground(True)
        self.fmValueBlockDecr.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecr.setObjectName("fmValueBlockDecr")
        self.lblHeaderVBDecr = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblHeaderVBDecr.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBDecr.setFont(font)
        self.lblHeaderVBDecr.setAutoFillBackground(False)
        self.lblHeaderVBDecr.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBDecr.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBDecr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBDecr.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBDecr.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBDecr.setObjectName("lblHeaderVBDecr")
        self.lblBlockAddressDecr = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblBlockAddressDecr.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecr.setFont(font)
        self.lblBlockAddressDecr.setObjectName("lblBlockAddressDecr")
        self.txtBlockAddressDecr = QtWidgets.QLineEdit(self.fmValueBlockDecr)
        self.txtBlockAddressDecr.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecr.setFont(font)
        self.txtBlockAddressDecr.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecr.setObjectName("txtBlockAddressDecr")
        self.btnDecrementValue = QtWidgets.QPushButton(self.fmValueBlockDecr)
        self.btnDecrementValue.setGeometry(QtCore.QRect(10, 82, 261, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValue.setFont(font)
        self.btnDecrementValue.setObjectName("btnDecrementValue")
        self.lblDecrementValue = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblDecrementValue.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValue.setFont(font)
        self.lblDecrementValue.setObjectName("lblDecrementValue")
        self.txtDecrementValue = QtWidgets.QLineEdit(self.fmValueBlockDecr)
        self.txtDecrementValue.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValue.setFont(font)
        self.txtDecrementValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValue.setReadOnly(False)
        self.txtDecrementValue.setObjectName("txtDecrementValue")
        self.tabValueBlockIncrDecr.addTab(self.tbValueBlockDecr, "")
        self.lblFnError = QtWidgets.QLabel(ValueBlockIncremDecrem)
        self.lblFnError.setGeometry(QtCore.QRect(3, 345, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnValue = QtWidgets.QLabel(ValueBlockIncremDecrem)
        self.lblFnValue.setGeometry(QtCore.QRect(113, 345, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnExplain = QtWidgets.QLabel(ValueBlockIncremDecrem)
        self.lblFnExplain.setGeometry(QtCore.QRect(194, 345, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")

        self.retranslateUi(ValueBlockIncremDecrem)
        self.tabValueBlockIncrDecr.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ValueBlockIncremDecrem)
        ValueBlockIncremDecrem.setTabOrder(self.tabValueBlockIncrDecr, self.txtIncrementValue)
        ValueBlockIncremDecrem.setTabOrder(self.txtIncrementValue, self.txtBlockAddressIncr)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressIncr, self.btnIncrementValue)
        ValueBlockIncremDecrem.setTabOrder(self.btnIncrementValue, self.txtIncrementValueAKM1)
        ValueBlockIncremDecrem.setTabOrder(self.txtIncrementValueAKM1, self.txtBlockAddressIncrAKM1)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressIncrAKM1, self.btnIncrementValueAKM1)
        ValueBlockIncremDecrem.setTabOrder(self.btnIncrementValueAKM1, self.txtIncrementValueAKM2)
        ValueBlockIncremDecrem.setTabOrder(self.txtIncrementValueAKM2, self.txtBlockAddressIncrAKM2)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressIncrAKM2, self.btnIncrementValueAKM2)
        ValueBlockIncremDecrem.setTabOrder(self.btnIncrementValueAKM2, self.txtIncrementValuePK)
        ValueBlockIncremDecrem.setTabOrder(self.txtIncrementValuePK, self.txtBlockAddressIncrPK)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressIncrPK, self.btnIncrementValuePK)
        ValueBlockIncremDecrem.setTabOrder(self.btnIncrementValuePK, self.txtDecrementValue)
        ValueBlockIncremDecrem.setTabOrder(self.txtDecrementValue, self.txtBlockAddressDecr)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressDecr, self.btnDecrementValue)
        ValueBlockIncremDecrem.setTabOrder(self.btnDecrementValue, self.txtDecrementValueAKM1)
        ValueBlockIncremDecrem.setTabOrder(self.txtDecrementValueAKM1, self.txtBlockAddressDecrAKM1)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressDecrAKM1, self.btnDecrementValueAKM1)
        ValueBlockIncremDecrem.setTabOrder(self.btnDecrementValueAKM1, self.txtDecrementValueAKM2)
        ValueBlockIncremDecrem.setTabOrder(self.txtDecrementValueAKM2, self.txtBlockAddressDecrAKM2)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressDecrAKM2, self.btnDecrementValueAKM2)
        ValueBlockIncremDecrem.setTabOrder(self.btnDecrementValueAKM2, self.txtDecrementValuePK)
        ValueBlockIncremDecrem.setTabOrder(self.txtDecrementValuePK, self.txtBlockAddressDecrPK)
        ValueBlockIncremDecrem.setTabOrder(self.txtBlockAddressDecrPK, self.btnDecrementValuePK)
        ValueBlockIncremDecrem.setTabOrder(self.btnDecrementValuePK, self.rbAUTH1A)
        ValueBlockIncremDecrem.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        ValueBlockIncremDecrem.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)

    def retranslateUi(self, ValueBlockIncremDecrem):
        _translate = QtCore.QCoreApplication.translate
        ValueBlockIncremDecrem.setWindowTitle(_translate("ValueBlockIncremDecrem", "Dialog"))
        self.rbAUTH1A.setText(_translate("ValueBlockIncremDecrem", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("ValueBlockIncremDecrem", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("ValueBlockIncremDecrem", "Key Index"))
        self.lblPKKeys.setText(_translate("ValueBlockIncremDecrem", "PK Key"))
        self.lblHeaderVBIncr.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK INCREMENT"))
        self.lblBlockAddress.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnIncrementValue.setText(_translate("ValueBlockIncremDecrem", "INCREMENT"))
        self.lblIncrementValue.setText(_translate("ValueBlockIncremDecrem", "Increment Value"))
        self.lblHeaderVBIncrAKM1.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK INCREMENT AKM1"))
        self.lblBlockAddressAKM1.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnIncrementValueAKM1.setText(_translate("ValueBlockIncremDecrem", "INCREMENT"))
        self.lblIncrementValueAKM1.setText(_translate("ValueBlockIncremDecrem", "Increment Value"))
        self.lblHeaderVBIncrAKM2.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK INCREMENT AKM2"))
        self.lblBlockAddressAKM2.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnIncrementValueAKM2.setText(_translate("ValueBlockIncremDecrem", "INCREMENT"))
        self.lblIncrementValueAKM2.setText(_translate("ValueBlockIncremDecrem", "Increment Value"))
        self.lblHeaderVBIncrAKM1_3.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK INCREMENT PK"))
        self.lblBlockAddressPK.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnIncrementValuePK.setText(_translate("ValueBlockIncremDecrem", "INCREMENT"))
        self.lblIncrementValuePK.setText(_translate("ValueBlockIncremDecrem", "Increment Value"))
        self.tabValueBlockIncrDecr.setTabText(self.tabValueBlockIncrDecr.indexOf(self.tbValueBlockIncr), _translate("ValueBlockIncremDecrem", "ValueBlock Increment"))
        self.lblHeaderVBDecrAKM1.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK DECREMENT AKM1"))
        self.lblBlockAddressDecrAKM1.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnDecrementValueAKM1.setText(_translate("ValueBlockIncremDecrem", "DECREMENT"))
        self.lblDecrementValueAKM1.setText(_translate("ValueBlockIncremDecrem", "Decrement Value"))
        self.lblHeaderVBDecrPK.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK DECREMENT AKM1"))
        self.lblBlockAddressDecrPK.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnDecrementValuePK.setText(_translate("ValueBlockIncremDecrem", "DECREMENT"))
        self.lblDecrementValuePK.setText(_translate("ValueBlockIncremDecrem", "Decrement Value"))
        self.lblHeaderVBDecrAKM2.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK DECREMENT AKM1"))
        self.lblBlockAddressDecrAKM2.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnDecrementValueAKM2.setText(_translate("ValueBlockIncremDecrem", "DECREMENT"))
        self.lblDecrementValueAKM2.setText(_translate("ValueBlockIncremDecrem", "Decrement Value"))
        self.lblHeaderVBDecr.setText(_translate("ValueBlockIncremDecrem", "VALUE BLOCK DECREMENT"))
        self.lblBlockAddressDecr.setText(_translate("ValueBlockIncremDecrem", "Block Address"))
        self.btnDecrementValue.setText(_translate("ValueBlockIncremDecrem", "DECREMENT"))
        self.lblDecrementValue.setText(_translate("ValueBlockIncremDecrem", "Decrement Value"))
        self.tabValueBlockIncrDecr.setTabText(self.tabValueBlockIncrDecr.indexOf(self.tbValueBlockDecr), _translate("ValueBlockIncremDecrem", "ValueBlock Decrement"))
        self.lblFnError.setText(_translate("ValueBlockIncremDecrem", "Function Error :"))

