# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ValueBlockReadWrite.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ValueBlockRW(object):
    def setupUi(self, ValueBlockRW):
        ValueBlockRW.setObjectName("ValueBlockRW")
        ValueBlockRW.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(ValueBlockRW)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.lblFnExplain = QtWidgets.QLabel(ValueBlockRW)
        self.lblFnExplain.setGeometry(QtCore.QRect(194, 341, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.lblFnError = QtWidgets.QLabel(ValueBlockRW)
        self.lblFnError.setGeometry(QtCore.QRect(3, 341, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnValue = QtWidgets.QLabel(ValueBlockRW)
        self.lblFnValue.setGeometry(QtCore.QRect(113, 341, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.tabValueBlockReadWrite = QtWidgets.QTabWidget(ValueBlockRW)
        self.tabValueBlockReadWrite.setGeometry(QtCore.QRect(3, 44, 600, 290))
        self.tabValueBlockReadWrite.setObjectName("tabValueBlockReadWrite")
        self.tbValueBlockRead = QtWidgets.QWidget()
        self.tbValueBlockRead.setObjectName("tbValueBlockRead")
        self.fmValueBlockRead = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockRead.setGeometry(QtCore.QRect(9, 10, 281, 120))
        self.fmValueBlockRead.setAutoFillBackground(True)
        self.fmValueBlockRead.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockRead.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockRead.setObjectName("fmValueBlockRead")
        self.lblHeaderVBBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblHeaderVBBR.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBBR.setFont(font)
        self.lblHeaderVBBR.setAutoFillBackground(False)
        self.lblHeaderVBBR.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBBR.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBBR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBBR.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBBR.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBBR.setObjectName("lblHeaderVBBR")
        self.lblValueBlockAddressBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblValueBlockAddressBR.setGeometry(QtCore.QRect(13, 35, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueBlockAddressBR.setFont(font)
        self.lblValueBlockAddressBR.setObjectName("lblValueBlockAddressBR")
        self.txtValueBlockAddressBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtValueBlockAddressBR.setGeometry(QtCore.QRect(105, 31, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBR.setFont(font)
        self.txtValueBlockAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBR.setObjectName("txtValueBlockAddressBR")
        self.btnValueBlockRead = QtWidgets.QPushButton(self.fmValueBlockRead)
        self.btnValueBlockRead.setGeometry(QtCore.QRect(164, 31, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockRead.setFont(font)
        self.btnValueBlockRead.setObjectName("btnValueBlockRead")
        self.lblReadDataBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblReadDataBR.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBR.setFont(font)
        self.lblReadDataBR.setObjectName("lblReadDataBR")
        self.txtValueReadDataBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtValueReadDataBR.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBR.setFont(font)
        self.txtValueReadDataBR.setReadOnly(True)
        self.txtValueReadDataBR.setObjectName("txtValueReadDataBR")
        self.txtValueAddressBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtValueAddressBR.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBR.setFont(font)
        self.txtValueAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBR.setReadOnly(True)
        self.txtValueAddressBR.setObjectName("txtValueAddressBR")
        self.lblValueAddressBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblValueAddressBR.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBR.setFont(font)
        self.lblValueAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressBR.setWordWrap(True)
        self.lblValueAddressBR.setObjectName("lblValueAddressBR")
        self.fmValueBlockReadAKM1 = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockReadAKM1.setGeometry(QtCore.QRect(305, 10, 281, 120))
        self.fmValueBlockReadAKM1.setAutoFillBackground(True)
        self.fmValueBlockReadAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockReadAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockReadAKM1.setObjectName("fmValueBlockReadAKM1")
        self.lblHeaderVBBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblHeaderVBBRAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBBRAKM1.setFont(font)
        self.lblHeaderVBBRAKM1.setAutoFillBackground(False)
        self.lblHeaderVBBRAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBBRAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBBRAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBBRAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBBRAKM1.setObjectName("lblHeaderVBBRAKM1")
        self.lblValueBlockAddressBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblValueBlockAddressBRAKM1.setGeometry(QtCore.QRect(13, 35, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueBlockAddressBRAKM1.setFont(font)
        self.lblValueBlockAddressBRAKM1.setObjectName("lblValueBlockAddressBRAKM1")
        self.txtValueBlockAddressAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtValueBlockAddressAKM1.setGeometry(QtCore.QRect(105, 31, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressAKM1.setFont(font)
        self.txtValueBlockAddressAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressAKM1.setObjectName("txtValueBlockAddressAKM1")
        self.btnValueBlockReadAKM1 = QtWidgets.QPushButton(self.fmValueBlockReadAKM1)
        self.btnValueBlockReadAKM1.setGeometry(QtCore.QRect(164, 31, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockReadAKM1.setFont(font)
        self.btnValueBlockReadAKM1.setObjectName("btnValueBlockReadAKM1")
        self.lblReadDataBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblReadDataBRAKM1.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM1.setFont(font)
        self.lblReadDataBRAKM1.setObjectName("lblReadDataBRAKM1")
        self.txtValueReadDataBRAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtValueReadDataBRAKM1.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBRAKM1.setFont(font)
        self.txtValueReadDataBRAKM1.setReadOnly(True)
        self.txtValueReadDataBRAKM1.setObjectName("txtValueReadDataBRAKM1")
        self.txtValueAddressAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtValueAddressAKM1.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressAKM1.setFont(font)
        self.txtValueAddressAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressAKM1.setReadOnly(True)
        self.txtValueAddressAKM1.setObjectName("txtValueAddressAKM1")
        self.lblValueAddressAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblValueAddressAKM1.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressAKM1.setFont(font)
        self.lblValueAddressAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressAKM1.setWordWrap(True)
        self.lblValueAddressAKM1.setObjectName("lblValueAddressAKM1")
        self.fmValueBlockReadAKM2 = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockReadAKM2.setGeometry(QtCore.QRect(9, 134, 281, 120))
        self.fmValueBlockReadAKM2.setAutoFillBackground(True)
        self.fmValueBlockReadAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockReadAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockReadAKM2.setObjectName("fmValueBlockReadAKM2")
        self.lblHeaderVBBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblHeaderVBBRAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBBRAKM2.setFont(font)
        self.lblHeaderVBBRAKM2.setAutoFillBackground(False)
        self.lblHeaderVBBRAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBBRAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBBRAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBBRAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBBRAKM2.setObjectName("lblHeaderVBBRAKM2")
        self.lblValueBlockAddressBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblValueBlockAddressBRAKM2.setGeometry(QtCore.QRect(13, 35, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueBlockAddressBRAKM2.setFont(font)
        self.lblValueBlockAddressBRAKM2.setObjectName("lblValueBlockAddressBRAKM2")
        self.txtValueBlockAddressAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtValueBlockAddressAKM2.setGeometry(QtCore.QRect(105, 31, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressAKM2.setFont(font)
        self.txtValueBlockAddressAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressAKM2.setObjectName("txtValueBlockAddressAKM2")
        self.btnValueBlockReadAKM2 = QtWidgets.QPushButton(self.fmValueBlockReadAKM2)
        self.btnValueBlockReadAKM2.setGeometry(QtCore.QRect(164, 31, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockReadAKM2.setFont(font)
        self.btnValueBlockReadAKM2.setObjectName("btnValueBlockReadAKM2")
        self.lblReadDataBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblReadDataBRAKM2.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM2.setFont(font)
        self.lblReadDataBRAKM2.setObjectName("lblReadDataBRAKM2")
        self.txtValueReadDataBRAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtValueReadDataBRAKM2.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBRAKM2.setFont(font)
        self.txtValueReadDataBRAKM2.setReadOnly(True)
        self.txtValueReadDataBRAKM2.setObjectName("txtValueReadDataBRAKM2")
        self.txtValueAddressAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtValueAddressAKM2.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressAKM2.setFont(font)
        self.txtValueAddressAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressAKM2.setReadOnly(True)
        self.txtValueAddressAKM2.setObjectName("txtValueAddressAKM2")
        self.lblValueAddressAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblValueAddressAKM2.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressAKM2.setFont(font)
        self.lblValueAddressAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressAKM2.setWordWrap(True)
        self.lblValueAddressAKM2.setObjectName("lblValueAddressAKM2")
        self.fmValueBlockReadPK = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockReadPK.setGeometry(QtCore.QRect(305, 134, 281, 120))
        self.fmValueBlockReadPK.setAutoFillBackground(True)
        self.fmValueBlockReadPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockReadPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockReadPK.setObjectName("fmValueBlockReadPK")
        self.lblHeaderVBBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblHeaderVBBRPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBBRPK.setFont(font)
        self.lblHeaderVBBRPK.setAutoFillBackground(False)
        self.lblHeaderVBBRPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBBRPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBBRPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBBRPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBBRPK.setObjectName("lblHeaderVBBRPK")
        self.lblValueBlockAddressBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblValueBlockAddressBRPK.setGeometry(QtCore.QRect(13, 35, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueBlockAddressBRPK.setFont(font)
        self.lblValueBlockAddressBRPK.setObjectName("lblValueBlockAddressBRPK")
        self.txtValueBlockAddressPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtValueBlockAddressPK.setGeometry(QtCore.QRect(105, 31, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressPK.setFont(font)
        self.txtValueBlockAddressPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressPK.setObjectName("txtValueBlockAddressPK")
        self.btnValueBlockReadPK = QtWidgets.QPushButton(self.fmValueBlockReadPK)
        self.btnValueBlockReadPK.setGeometry(QtCore.QRect(164, 31, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockReadPK.setFont(font)
        self.btnValueBlockReadPK.setObjectName("btnValueBlockReadPK")
        self.lblReadDataBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblReadDataBRPK.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRPK.setFont(font)
        self.lblReadDataBRPK.setObjectName("lblReadDataBRPK")
        self.txtValueReadDataBRPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtValueReadDataBRPK.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBRPK.setFont(font)
        self.txtValueReadDataBRPK.setReadOnly(True)
        self.txtValueReadDataBRPK.setObjectName("txtValueReadDataBRPK")
        self.txtValueAddressPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtValueAddressPK.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressPK.setFont(font)
        self.txtValueAddressPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressPK.setReadOnly(True)
        self.txtValueAddressPK.setObjectName("txtValueAddressPK")
        self.lblValueAddressPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblValueAddressPK.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressPK.setFont(font)
        self.lblValueAddressPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressPK.setWordWrap(True)
        self.lblValueAddressPK.setObjectName("lblValueAddressPK")
        self.tabValueBlockReadWrite.addTab(self.tbValueBlockRead, "")
        self.tbValueBlockWrite = QtWidgets.QWidget()
        self.tbValueBlockWrite.setObjectName("tbValueBlockWrite")
        self.fmValueBlockWrite = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWrite.setGeometry(QtCore.QRect(9, 10, 281, 120))
        self.fmValueBlockWrite.setAutoFillBackground(True)
        self.fmValueBlockWrite.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWrite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWrite.setObjectName("fmValueBlockWrite")
        self.lblHeaderBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblHeaderBW.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBW.setFont(font)
        self.lblHeaderBW.setAutoFillBackground(False)
        self.lblHeaderBW.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBW.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBW.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBW.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBW.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBW.setObjectName("lblHeaderBW")
        self.lblBlockAddressBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblBlockAddressBW.setGeometry(QtCore.QRect(17, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBW.setFont(font)
        self.lblBlockAddressBW.setObjectName("lblBlockAddressBW")
        self.txtValueBlockAddressBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtValueBlockAddressBW.setGeometry(QtCore.QRect(109, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBW.setFont(font)
        self.txtValueBlockAddressBW.setObjectName("txtValueBlockAddressBW")
        self.btnValueBlockWrite = QtWidgets.QPushButton(self.fmValueBlockWrite)
        self.btnValueBlockWrite.setGeometry(QtCore.QRect(166, 67, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWrite.setFont(font)
        self.btnValueBlockWrite.setObjectName("btnValueBlockWrite")
        self.lblEnterValueBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblEnterValueBW.setGeometry(QtCore.QRect(73, 22, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueBW.setFont(font)
        self.lblEnterValueBW.setObjectName("lblEnterValueBW")
        self.txtValueWriteDataBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtValueWriteDataBW.setGeometry(QtCore.QRect(70, 39, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBW.setFont(font)
        self.txtValueWriteDataBW.setReadOnly(False)
        self.txtValueWriteDataBW.setObjectName("txtValueWriteDataBW")
        self.lblValueAddressBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblValueAddressBW.setGeometry(QtCore.QRect(15, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBW.setFont(font)
        self.lblValueAddressBW.setObjectName("lblValueAddressBW")
        self.txtValueAddressBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtValueAddressBW.setGeometry(QtCore.QRect(109, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBW.setFont(font)
        self.txtValueAddressBW.setObjectName("txtValueAddressBW")
        self.fmValueBlockWriteAKM1 = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWriteAKM1.setGeometry(QtCore.QRect(305, 10, 281, 120))
        self.fmValueBlockWriteAKM1.setAutoFillBackground(True)
        self.fmValueBlockWriteAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWriteAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWriteAKM1.setObjectName("fmValueBlockWriteAKM1")
        self.lblHeaderBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblHeaderBWAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM1.setFont(font)
        self.lblHeaderBWAKM1.setAutoFillBackground(False)
        self.lblHeaderBWAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM1.setObjectName("lblHeaderBWAKM1")
        self.lblBlockAddressBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblBlockAddressBWAKM1.setGeometry(QtCore.QRect(17, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM1.setFont(font)
        self.lblBlockAddressBWAKM1.setObjectName("lblBlockAddressBWAKM1")
        self.txtValueBlockAddressBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtValueBlockAddressBWAKM1.setGeometry(QtCore.QRect(109, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBWAKM1.setFont(font)
        self.txtValueBlockAddressBWAKM1.setObjectName("txtValueBlockAddressBWAKM1")
        self.btnValueBlockWriteAKM1 = QtWidgets.QPushButton(self.fmValueBlockWriteAKM1)
        self.btnValueBlockWriteAKM1.setGeometry(QtCore.QRect(166, 67, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWriteAKM1.setFont(font)
        self.btnValueBlockWriteAKM1.setObjectName("btnValueBlockWriteAKM1")
        self.lblEnterValueAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblEnterValueAKM1.setGeometry(QtCore.QRect(73, 22, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueAKM1.setFont(font)
        self.lblEnterValueAKM1.setObjectName("lblEnterValueAKM1")
        self.txtValueWriteDataBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtValueWriteDataBWAKM1.setGeometry(QtCore.QRect(70, 39, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBWAKM1.setFont(font)
        self.txtValueWriteDataBWAKM1.setReadOnly(False)
        self.txtValueWriteDataBWAKM1.setObjectName("txtValueWriteDataBWAKM1")
        self.lblValueAddressBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblValueAddressBWAKM1.setGeometry(QtCore.QRect(15, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBWAKM1.setFont(font)
        self.lblValueAddressBWAKM1.setObjectName("lblValueAddressBWAKM1")
        self.txtValueAddressBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtValueAddressBWAKM1.setGeometry(QtCore.QRect(109, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBWAKM1.setFont(font)
        self.txtValueAddressBWAKM1.setObjectName("txtValueAddressBWAKM1")
        self.fmValueBlockWritePK = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWritePK.setGeometry(QtCore.QRect(305, 133, 281, 120))
        self.fmValueBlockWritePK.setAutoFillBackground(True)
        self.fmValueBlockWritePK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWritePK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWritePK.setObjectName("fmValueBlockWritePK")
        self.lblHeaderBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblHeaderBWPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWPK.setFont(font)
        self.lblHeaderBWPK.setAutoFillBackground(False)
        self.lblHeaderBWPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWPK.setObjectName("lblHeaderBWPK")
        self.lblBlockAddressBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblBlockAddressBWPK.setGeometry(QtCore.QRect(17, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWPK.setFont(font)
        self.lblBlockAddressBWPK.setObjectName("lblBlockAddressBWPK")
        self.txtValueBlockAddressBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtValueBlockAddressBWPK.setGeometry(QtCore.QRect(109, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBWPK.setFont(font)
        self.txtValueBlockAddressBWPK.setObjectName("txtValueBlockAddressBWPK")
        self.btnValueBlockWritePK = QtWidgets.QPushButton(self.fmValueBlockWritePK)
        self.btnValueBlockWritePK.setGeometry(QtCore.QRect(166, 67, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWritePK.setFont(font)
        self.btnValueBlockWritePK.setObjectName("btnValueBlockWritePK")
        self.lblEnterValuePK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblEnterValuePK.setGeometry(QtCore.QRect(73, 22, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValuePK.setFont(font)
        self.lblEnterValuePK.setObjectName("lblEnterValuePK")
        self.txtValueWriteDataBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtValueWriteDataBWPK.setGeometry(QtCore.QRect(70, 39, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBWPK.setFont(font)
        self.txtValueWriteDataBWPK.setReadOnly(False)
        self.txtValueWriteDataBWPK.setObjectName("txtValueWriteDataBWPK")
        self.lblValueAddressBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblValueAddressBWPK.setGeometry(QtCore.QRect(15, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBWPK.setFont(font)
        self.lblValueAddressBWPK.setObjectName("lblValueAddressBWPK")
        self.txtValueAddressBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtValueAddressBWPK.setGeometry(QtCore.QRect(109, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBWPK.setFont(font)
        self.txtValueAddressBWPK.setObjectName("txtValueAddressBWPK")
        self.fmValueBlockWriteAKM2 = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWriteAKM2.setGeometry(QtCore.QRect(8, 133, 281, 120))
        self.fmValueBlockWriteAKM2.setAutoFillBackground(True)
        self.fmValueBlockWriteAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWriteAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWriteAKM2.setObjectName("fmValueBlockWriteAKM2")
        self.lblHeaderBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblHeaderBWAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM2.setFont(font)
        self.lblHeaderBWAKM2.setAutoFillBackground(False)
        self.lblHeaderBWAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM2.setObjectName("lblHeaderBWAKM2")
        self.lblBlockAddressBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblBlockAddressBWAKM2.setGeometry(QtCore.QRect(17, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM2.setFont(font)
        self.lblBlockAddressBWAKM2.setObjectName("lblBlockAddressBWAKM2")
        self.txtValueBlockAddressBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtValueBlockAddressBWAKM2.setGeometry(QtCore.QRect(109, 89, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBWAKM2.setFont(font)
        self.txtValueBlockAddressBWAKM2.setObjectName("txtValueBlockAddressBWAKM2")
        self.btnValueBlockWriteAKM2 = QtWidgets.QPushButton(self.fmValueBlockWriteAKM2)
        self.btnValueBlockWriteAKM2.setGeometry(QtCore.QRect(166, 67, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWriteAKM2.setFont(font)
        self.btnValueBlockWriteAKM2.setObjectName("btnValueBlockWriteAKM2")
        self.lblEnterValueAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblEnterValueAKM2.setGeometry(QtCore.QRect(73, 22, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueAKM2.setFont(font)
        self.lblEnterValueAKM2.setObjectName("lblEnterValueAKM2")
        self.txtValueWriteDataBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtValueWriteDataBWAKM2.setGeometry(QtCore.QRect(70, 39, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBWAKM2.setFont(font)
        self.txtValueWriteDataBWAKM2.setReadOnly(False)
        self.txtValueWriteDataBWAKM2.setObjectName("txtValueWriteDataBWAKM2")
        self.lblValueAddressBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblValueAddressBWAKM2.setGeometry(QtCore.QRect(15, 66, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBWAKM2.setFont(font)
        self.lblValueAddressBWAKM2.setObjectName("lblValueAddressBWAKM2")
        self.txtValueAddressBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtValueAddressBWAKM2.setGeometry(QtCore.QRect(109, 66, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBWAKM2.setFont(font)
        self.txtValueAddressBWAKM2.setObjectName("txtValueAddressBWAKM2")
        self.tabValueBlockReadWrite.addTab(self.tbValueBlockWrite, "")

        self.retranslateUi(ValueBlockRW)
        self.tabValueBlockReadWrite.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ValueBlockRW)
        ValueBlockRW.setTabOrder(self.tabValueBlockReadWrite, self.txtValueBlockAddressBR)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressBR, self.btnValueBlockRead)
        ValueBlockRW.setTabOrder(self.btnValueBlockRead, self.txtValueReadDataBR)
        ValueBlockRW.setTabOrder(self.txtValueReadDataBR, self.txtValueAddressBR)
        ValueBlockRW.setTabOrder(self.txtValueAddressBR, self.txtValueBlockAddressAKM1)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressAKM1, self.btnValueBlockReadAKM1)
        ValueBlockRW.setTabOrder(self.btnValueBlockReadAKM1, self.txtValueReadDataBRAKM1)
        ValueBlockRW.setTabOrder(self.txtValueReadDataBRAKM1, self.txtValueAddressAKM1)
        ValueBlockRW.setTabOrder(self.txtValueAddressAKM1, self.txtValueBlockAddressAKM2)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressAKM2, self.btnValueBlockReadAKM2)
        ValueBlockRW.setTabOrder(self.btnValueBlockReadAKM2, self.txtValueReadDataBRAKM2)
        ValueBlockRW.setTabOrder(self.txtValueReadDataBRAKM2, self.txtValueAddressAKM2)
        ValueBlockRW.setTabOrder(self.txtValueAddressAKM2, self.txtValueBlockAddressPK)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressPK, self.btnValueBlockReadPK)
        ValueBlockRW.setTabOrder(self.btnValueBlockReadPK, self.txtValueReadDataBRPK)
        ValueBlockRW.setTabOrder(self.txtValueReadDataBRPK, self.txtValueAddressPK)
        ValueBlockRW.setTabOrder(self.txtValueAddressPK, self.txtValueWriteDataBW)
        ValueBlockRW.setTabOrder(self.txtValueWriteDataBW, self.txtValueAddressBW)
        ValueBlockRW.setTabOrder(self.txtValueAddressBW, self.txtValueBlockAddressBW)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressBW, self.btnValueBlockWrite)
        ValueBlockRW.setTabOrder(self.btnValueBlockWrite, self.txtValueWriteDataBWAKM1)
        ValueBlockRW.setTabOrder(self.txtValueWriteDataBWAKM1, self.txtValueAddressBWAKM1)
        ValueBlockRW.setTabOrder(self.txtValueAddressBWAKM1, self.txtValueBlockAddressBWAKM1)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressBWAKM1, self.btnValueBlockWriteAKM1)
        ValueBlockRW.setTabOrder(self.btnValueBlockWriteAKM1, self.txtValueWriteDataBWAKM2)
        ValueBlockRW.setTabOrder(self.txtValueWriteDataBWAKM2, self.txtValueAddressBWAKM2)
        ValueBlockRW.setTabOrder(self.txtValueAddressBWAKM2, self.txtValueBlockAddressBWAKM2)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressBWAKM2, self.btnValueBlockWriteAKM2)
        ValueBlockRW.setTabOrder(self.btnValueBlockWriteAKM2, self.txtValueWriteDataBWPK)
        ValueBlockRW.setTabOrder(self.txtValueWriteDataBWPK, self.txtValueAddressBWPK)
        ValueBlockRW.setTabOrder(self.txtValueAddressBWPK, self.txtValueBlockAddressBWPK)
        ValueBlockRW.setTabOrder(self.txtValueBlockAddressBWPK, self.btnValueBlockWritePK)
        ValueBlockRW.setTabOrder(self.btnValueBlockWritePK, self.rbAUTH1A)
        ValueBlockRW.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        ValueBlockRW.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)

    def retranslateUi(self, ValueBlockRW):
        _translate = QtCore.QCoreApplication.translate
        ValueBlockRW.setWindowTitle(_translate("ValueBlockRW", "Dialog"))
        self.rbAUTH1A.setText(_translate("ValueBlockRW", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("ValueBlockRW", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("ValueBlockRW", "Key Index"))
        self.lblPKKeys.setText(_translate("ValueBlockRW", "PK Key"))
        self.lblFnError.setText(_translate("ValueBlockRW", "Function Error :"))
        self.lblHeaderVBBR.setText(_translate("ValueBlockRW", "VALUE BLOCK READ"))
        self.lblValueBlockAddressBR.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockRead.setText(_translate("ValueBlockRW", "READ"))
        self.lblReadDataBR.setText(_translate("ValueBlockRW", "Read Value"))
        self.lblValueAddressBR.setText(_translate("ValueBlockRW", "Value Address"))
        self.lblHeaderVBBRAKM1.setText(_translate("ValueBlockRW", "VALUE BLOCK READ AKM1"))
        self.lblValueBlockAddressBRAKM1.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockReadAKM1.setText(_translate("ValueBlockRW", "READ"))
        self.lblReadDataBRAKM1.setText(_translate("ValueBlockRW", "Read Value"))
        self.lblValueAddressAKM1.setText(_translate("ValueBlockRW", "Value Address"))
        self.lblHeaderVBBRAKM2.setText(_translate("ValueBlockRW", "VALUE BLOCK READ AKM2"))
        self.lblValueBlockAddressBRAKM2.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockReadAKM2.setText(_translate("ValueBlockRW", "READ"))
        self.lblReadDataBRAKM2.setText(_translate("ValueBlockRW", "Read Value"))
        self.lblValueAddressAKM2.setText(_translate("ValueBlockRW", "Value Address"))
        self.lblHeaderVBBRPK.setText(_translate("ValueBlockRW", "VALUE BLOCK READ PK"))
        self.lblValueBlockAddressBRPK.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockReadPK.setText(_translate("ValueBlockRW", "READ"))
        self.lblReadDataBRPK.setText(_translate("ValueBlockRW", "Read Value"))
        self.lblValueAddressPK.setText(_translate("ValueBlockRW", "Value Address"))
        self.tabValueBlockReadWrite.setTabText(self.tabValueBlockReadWrite.indexOf(self.tbValueBlockRead), _translate("ValueBlockRW", "ValueBlock Read"))
        self.lblHeaderBW.setText(_translate("ValueBlockRW", "VALUE BLOCK WRITE"))
        self.lblBlockAddressBW.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockWrite.setText(_translate("ValueBlockRW", "WRITE"))
        self.lblEnterValueBW.setText(_translate("ValueBlockRW", "Enter Value"))
        self.lblValueAddressBW.setText(_translate("ValueBlockRW", "Value Address"))
        self.lblHeaderBWAKM1.setText(_translate("ValueBlockRW", "VALUE BLOCK WRITE AKM1"))
        self.lblBlockAddressBWAKM1.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockWriteAKM1.setText(_translate("ValueBlockRW", "WRITE"))
        self.lblEnterValueAKM1.setText(_translate("ValueBlockRW", "Enter Value"))
        self.lblValueAddressBWAKM1.setText(_translate("ValueBlockRW", "Value Address"))
        self.lblHeaderBWPK.setText(_translate("ValueBlockRW", "VALUE BLOCK WRITE PK"))
        self.lblBlockAddressBWPK.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockWritePK.setText(_translate("ValueBlockRW", "WRITE"))
        self.lblEnterValuePK.setText(_translate("ValueBlockRW", "Enter Value"))
        self.lblValueAddressBWPK.setText(_translate("ValueBlockRW", "Value Address"))
        self.lblHeaderBWAKM2.setText(_translate("ValueBlockRW", "VALUE BLOCK WRITE AKM2"))
        self.lblBlockAddressBWAKM2.setText(_translate("ValueBlockRW", "Block Address"))
        self.btnValueBlockWriteAKM2.setText(_translate("ValueBlockRW", "WRITE"))
        self.lblEnterValueAKM2.setText(_translate("ValueBlockRW", "Enter Value"))
        self.lblValueAddressBWAKM2.setText(_translate("ValueBlockRW", "Value Address"))
        self.tabValueBlockReadWrite.setTabText(self.tabValueBlockReadWrite.indexOf(self.tbValueBlockWrite), _translate("ValueBlockRW", "ValueBlock Write"))

