# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ValueBlockInSectorIncrDecr.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ValueBlockInSectorIncrDecr(object):
    def setupUi(self, ValueBlockInSectorIncrDecr):
        ValueBlockInSectorIncrDecr.setObjectName("ValueBlockInSectorIncrDecr")
        ValueBlockInSectorIncrDecr.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(ValueBlockInSectorIncrDecr)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.tabValueBlockInSIncrDecr = QtWidgets.QTabWidget(ValueBlockInSectorIncrDecr)
        self.tabValueBlockInSIncrDecr.setGeometry(QtCore.QRect(4, 47, 600, 290))
        self.tabValueBlockInSIncrDecr.setObjectName("tabValueBlockInSIncrDecr")
        self.tbValueBlockInSIncr = QtWidgets.QWidget()
        self.tbValueBlockInSIncr.setObjectName("tbValueBlockInSIncr")
        self.fmValueBlockIncr = QtWidgets.QFrame(self.tbValueBlockInSIncr)
        self.fmValueBlockIncr.setGeometry(QtCore.QRect(10, 10, 281, 120))
        self.fmValueBlockIncr.setAutoFillBackground(True)
        self.fmValueBlockIncr.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncr.setObjectName("fmValueBlockIncr")
        self.lblHeaderVBISIncr = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblHeaderVBISIncr.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISIncr.setFont(font)
        self.lblHeaderVBISIncr.setAutoFillBackground(False)
        self.lblHeaderVBISIncr.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISIncr.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISIncr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISIncr.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISIncr.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISIncr.setObjectName("lblHeaderVBISIncr")
        self.lblBlockAddress = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblBlockAddress.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddress.setFont(font)
        self.lblBlockAddress.setObjectName("lblBlockAddress")
        self.txtBlockAddressIncr = QtWidgets.QLineEdit(self.fmValueBlockIncr)
        self.txtBlockAddressIncr.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncr.setFont(font)
        self.txtBlockAddressIncr.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncr.setObjectName("txtBlockAddressIncr")
        self.btnIncrementValue = QtWidgets.QPushButton(self.fmValueBlockIncr)
        self.btnIncrementValue.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValue.setFont(font)
        self.btnIncrementValue.setObjectName("btnIncrementValue")
        self.lblIncrementValue = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblIncrementValue.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValue.setFont(font)
        self.lblIncrementValue.setObjectName("lblIncrementValue")
        self.txtIncrementValue = QtWidgets.QLineEdit(self.fmValueBlockIncr)
        self.txtIncrementValue.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValue.setFont(font)
        self.txtIncrementValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValue.setReadOnly(False)
        self.txtIncrementValue.setObjectName("txtIncrementValue")
        self.lblSectorAddressIncr = QtWidgets.QLabel(self.fmValueBlockIncr)
        self.lblSectorAddressIncr.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressIncr.setFont(font)
        self.lblSectorAddressIncr.setObjectName("lblSectorAddressIncr")
        self.txtSectorAddressIncr = QtWidgets.QLineEdit(self.fmValueBlockIncr)
        self.txtSectorAddressIncr.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressIncr.setFont(font)
        self.txtSectorAddressIncr.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressIncr.setObjectName("txtSectorAddressIncr")
        self.fmValueBlockIncrAKM1 = QtWidgets.QFrame(self.tbValueBlockInSIncr)
        self.fmValueBlockIncrAKM1.setGeometry(QtCore.QRect(306, 10, 281, 120))
        self.fmValueBlockIncrAKM1.setAutoFillBackground(True)
        self.fmValueBlockIncrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncrAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncrAKM1.setObjectName("fmValueBlockIncrAKM1")
        self.lblHeaderVBISIncrAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblHeaderVBISIncrAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISIncrAKM1.setFont(font)
        self.lblHeaderVBISIncrAKM1.setAutoFillBackground(False)
        self.lblHeaderVBISIncrAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISIncrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISIncrAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISIncrAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISIncrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISIncrAKM1.setObjectName("lblHeaderVBISIncrAKM1")
        self.lblBlockAddressAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblBlockAddressAKM1.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressAKM1.setFont(font)
        self.lblBlockAddressAKM1.setObjectName("lblBlockAddressAKM1")
        self.txtBlockAddressIncrAKM1 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM1)
        self.txtBlockAddressIncrAKM1.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncrAKM1.setFont(font)
        self.txtBlockAddressIncrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncrAKM1.setObjectName("txtBlockAddressIncrAKM1")
        self.btnIncrementValueAKM1 = QtWidgets.QPushButton(self.fmValueBlockIncrAKM1)
        self.btnIncrementValueAKM1.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValueAKM1.setFont(font)
        self.btnIncrementValueAKM1.setObjectName("btnIncrementValueAKM1")
        self.lblIncrementValueAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblIncrementValueAKM1.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValueAKM1.setFont(font)
        self.lblIncrementValueAKM1.setObjectName("lblIncrementValueAKM1")
        self.txtIncrementValueAKM1 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM1)
        self.txtIncrementValueAKM1.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValueAKM1.setFont(font)
        self.txtIncrementValueAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValueAKM1.setReadOnly(False)
        self.txtIncrementValueAKM1.setObjectName("txtIncrementValueAKM1")
        self.lblSectorAddressIncrAKM1 = QtWidgets.QLabel(self.fmValueBlockIncrAKM1)
        self.lblSectorAddressIncrAKM1.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressIncrAKM1.setFont(font)
        self.lblSectorAddressIncrAKM1.setObjectName("lblSectorAddressIncrAKM1")
        self.txtSectorAddressIncrAKM1 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM1)
        self.txtSectorAddressIncrAKM1.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressIncrAKM1.setFont(font)
        self.txtSectorAddressIncrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressIncrAKM1.setObjectName("txtSectorAddressIncrAKM1")
        self.fmValueBlockIncrAKM2 = QtWidgets.QFrame(self.tbValueBlockInSIncr)
        self.fmValueBlockIncrAKM2.setGeometry(QtCore.QRect(10, 134, 281, 120))
        self.fmValueBlockIncrAKM2.setAutoFillBackground(True)
        self.fmValueBlockIncrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncrAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncrAKM2.setObjectName("fmValueBlockIncrAKM2")
        self.lblHeaderVBISIncrAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblHeaderVBISIncrAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISIncrAKM2.setFont(font)
        self.lblHeaderVBISIncrAKM2.setAutoFillBackground(False)
        self.lblHeaderVBISIncrAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISIncrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISIncrAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISIncrAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISIncrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISIncrAKM2.setObjectName("lblHeaderVBISIncrAKM2")
        self.lblBlockAddressAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblBlockAddressAKM2.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressAKM2.setFont(font)
        self.lblBlockAddressAKM2.setObjectName("lblBlockAddressAKM2")
        self.txtBlockAddressIncrAKM2 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM2)
        self.txtBlockAddressIncrAKM2.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncrAKM2.setFont(font)
        self.txtBlockAddressIncrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncrAKM2.setObjectName("txtBlockAddressIncrAKM2")
        self.btnIncrementValueAKM2 = QtWidgets.QPushButton(self.fmValueBlockIncrAKM2)
        self.btnIncrementValueAKM2.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValueAKM2.setFont(font)
        self.btnIncrementValueAKM2.setObjectName("btnIncrementValueAKM2")
        self.lblIncrementValueAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblIncrementValueAKM2.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValueAKM2.setFont(font)
        self.lblIncrementValueAKM2.setObjectName("lblIncrementValueAKM2")
        self.txtIncrementValueAKM2 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM2)
        self.txtIncrementValueAKM2.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValueAKM2.setFont(font)
        self.txtIncrementValueAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValueAKM2.setReadOnly(False)
        self.txtIncrementValueAKM2.setObjectName("txtIncrementValueAKM2")
        self.lblSectorAddressIncrAKM2 = QtWidgets.QLabel(self.fmValueBlockIncrAKM2)
        self.lblSectorAddressIncrAKM2.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressIncrAKM2.setFont(font)
        self.lblSectorAddressIncrAKM2.setObjectName("lblSectorAddressIncrAKM2")
        self.txtSectorAddressIncrAKM2 = QtWidgets.QLineEdit(self.fmValueBlockIncrAKM2)
        self.txtSectorAddressIncrAKM2.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressIncrAKM2.setFont(font)
        self.txtSectorAddressIncrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressIncrAKM2.setObjectName("txtSectorAddressIncrAKM2")
        self.fmValueBlockIncrPK = QtWidgets.QFrame(self.tbValueBlockInSIncr)
        self.fmValueBlockIncrPK.setGeometry(QtCore.QRect(306, 134, 281, 120))
        self.fmValueBlockIncrPK.setAutoFillBackground(True)
        self.fmValueBlockIncrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockIncrPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockIncrPK.setObjectName("fmValueBlockIncrPK")
        self.lblHeaderVBISIncrPK = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblHeaderVBISIncrPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISIncrPK.setFont(font)
        self.lblHeaderVBISIncrPK.setAutoFillBackground(False)
        self.lblHeaderVBISIncrPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISIncrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISIncrPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISIncrPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISIncrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISIncrPK.setObjectName("lblHeaderVBISIncrPK")
        self.lblBlockAddressPK = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblBlockAddressPK.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressPK.setFont(font)
        self.lblBlockAddressPK.setObjectName("lblBlockAddressPK")
        self.txtBlockAddressIncrPK = QtWidgets.QLineEdit(self.fmValueBlockIncrPK)
        self.txtBlockAddressIncrPK.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressIncrPK.setFont(font)
        self.txtBlockAddressIncrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressIncrPK.setObjectName("txtBlockAddressIncrPK")
        self.btnIncrementValuePK = QtWidgets.QPushButton(self.fmValueBlockIncrPK)
        self.btnIncrementValuePK.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnIncrementValuePK.setFont(font)
        self.btnIncrementValuePK.setObjectName("btnIncrementValuePK")
        self.lblIncrementValuePK = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblIncrementValuePK.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblIncrementValuePK.setFont(font)
        self.lblIncrementValuePK.setObjectName("lblIncrementValuePK")
        self.txtIncrementValuePK = QtWidgets.QLineEdit(self.fmValueBlockIncrPK)
        self.txtIncrementValuePK.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtIncrementValuePK.setFont(font)
        self.txtIncrementValuePK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIncrementValuePK.setReadOnly(False)
        self.txtIncrementValuePK.setObjectName("txtIncrementValuePK")
        self.lblSectorAddressIncrPK = QtWidgets.QLabel(self.fmValueBlockIncrPK)
        self.lblSectorAddressIncrPK.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressIncrPK.setFont(font)
        self.lblSectorAddressIncrPK.setObjectName("lblSectorAddressIncrPK")
        self.txtSectorAddressIncrPK = QtWidgets.QLineEdit(self.fmValueBlockIncrPK)
        self.txtSectorAddressIncrPK.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressIncrPK.setFont(font)
        self.txtSectorAddressIncrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressIncrPK.setObjectName("txtSectorAddressIncrPK")
        self.tabValueBlockInSIncrDecr.addTab(self.tbValueBlockInSIncr, "")
        self.tbValueBlockInSDecr = QtWidgets.QWidget()
        self.tbValueBlockInSDecr.setObjectName("tbValueBlockInSDecr")
        self.fmValueBlockDecr = QtWidgets.QFrame(self.tbValueBlockInSDecr)
        self.fmValueBlockDecr.setGeometry(QtCore.QRect(10, 10, 281, 120))
        self.fmValueBlockDecr.setAutoFillBackground(True)
        self.fmValueBlockDecr.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecr.setObjectName("fmValueBlockDecr")
        self.lblHeaderVBISDecr = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblHeaderVBISDecr.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISDecr.setFont(font)
        self.lblHeaderVBISDecr.setAutoFillBackground(False)
        self.lblHeaderVBISDecr.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISDecr.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISDecr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISDecr.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISDecr.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISDecr.setObjectName("lblHeaderVBISDecr")
        self.lblBlockAddressDecr = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblBlockAddressDecr.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecr.setFont(font)
        self.lblBlockAddressDecr.setObjectName("lblBlockAddressDecr")
        self.txtBlockAddressDecr = QtWidgets.QLineEdit(self.fmValueBlockDecr)
        self.txtBlockAddressDecr.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecr.setFont(font)
        self.txtBlockAddressDecr.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecr.setObjectName("txtBlockAddressDecr")
        self.btnDecrementValue = QtWidgets.QPushButton(self.fmValueBlockDecr)
        self.btnDecrementValue.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValue.setFont(font)
        self.btnDecrementValue.setObjectName("btnDecrementValue")
        self.lblDecrementValue = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblDecrementValue.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValue.setFont(font)
        self.lblDecrementValue.setObjectName("lblDecrementValue")
        self.txtDecrementValue = QtWidgets.QLineEdit(self.fmValueBlockDecr)
        self.txtDecrementValue.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValue.setFont(font)
        self.txtDecrementValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValue.setReadOnly(False)
        self.txtDecrementValue.setObjectName("txtDecrementValue")
        self.lblSectorAddressDecr = QtWidgets.QLabel(self.fmValueBlockDecr)
        self.lblSectorAddressDecr.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressDecr.setFont(font)
        self.lblSectorAddressDecr.setObjectName("lblSectorAddressDecr")
        self.txtSectorAddressDecr = QtWidgets.QLineEdit(self.fmValueBlockDecr)
        self.txtSectorAddressDecr.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressDecr.setFont(font)
        self.txtSectorAddressDecr.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressDecr.setObjectName("txtSectorAddressDecr")
        self.fmValueBlockDecrAKM1 = QtWidgets.QFrame(self.tbValueBlockInSDecr)
        self.fmValueBlockDecrAKM1.setGeometry(QtCore.QRect(306, 10, 281, 120))
        self.fmValueBlockDecrAKM1.setAutoFillBackground(True)
        self.fmValueBlockDecrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecrAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecrAKM1.setObjectName("fmValueBlockDecrAKM1")
        self.lblHeaderVBISDecrAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblHeaderVBISDecrAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISDecrAKM1.setFont(font)
        self.lblHeaderVBISDecrAKM1.setAutoFillBackground(False)
        self.lblHeaderVBISDecrAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISDecrAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISDecrAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISDecrAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISDecrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISDecrAKM1.setObjectName("lblHeaderVBISDecrAKM1")
        self.lblBlockAddressDecrAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblBlockAddressDecrAKM1.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecrAKM1.setFont(font)
        self.lblBlockAddressDecrAKM1.setObjectName("lblBlockAddressDecrAKM1")
        self.txtBlockAddressDecrAKM1 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM1)
        self.txtBlockAddressDecrAKM1.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecrAKM1.setFont(font)
        self.txtBlockAddressDecrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecrAKM1.setObjectName("txtBlockAddressDecrAKM1")
        self.btnDecrementValueAKM1 = QtWidgets.QPushButton(self.fmValueBlockDecrAKM1)
        self.btnDecrementValueAKM1.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValueAKM1.setFont(font)
        self.btnDecrementValueAKM1.setObjectName("btnDecrementValueAKM1")
        self.lblDecrementValueAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblDecrementValueAKM1.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValueAKM1.setFont(font)
        self.lblDecrementValueAKM1.setObjectName("lblDecrementValueAKM1")
        self.txtDecrementValueAKM1 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM1)
        self.txtDecrementValueAKM1.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValueAKM1.setFont(font)
        self.txtDecrementValueAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValueAKM1.setReadOnly(False)
        self.txtDecrementValueAKM1.setObjectName("txtDecrementValueAKM1")
        self.lblSectorAddressDecrAKM1 = QtWidgets.QLabel(self.fmValueBlockDecrAKM1)
        self.lblSectorAddressDecrAKM1.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressDecrAKM1.setFont(font)
        self.lblSectorAddressDecrAKM1.setObjectName("lblSectorAddressDecrAKM1")
        self.txtSectorAddressDecrAKM1 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM1)
        self.txtSectorAddressDecrAKM1.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressDecrAKM1.setFont(font)
        self.txtSectorAddressDecrAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressDecrAKM1.setObjectName("txtSectorAddressDecrAKM1")
        self.fmValueBlockDecrAKM2 = QtWidgets.QFrame(self.tbValueBlockInSDecr)
        self.fmValueBlockDecrAKM2.setGeometry(QtCore.QRect(10, 134, 281, 120))
        self.fmValueBlockDecrAKM2.setAutoFillBackground(True)
        self.fmValueBlockDecrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecrAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecrAKM2.setObjectName("fmValueBlockDecrAKM2")
        self.lblHeaderVBISDecrAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblHeaderVBISDecrAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISDecrAKM2.setFont(font)
        self.lblHeaderVBISDecrAKM2.setAutoFillBackground(False)
        self.lblHeaderVBISDecrAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISDecrAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISDecrAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISDecrAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISDecrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISDecrAKM2.setObjectName("lblHeaderVBISDecrAKM2")
        self.lblBlockAddressDecrAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblBlockAddressDecrAKM2.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecrAKM2.setFont(font)
        self.lblBlockAddressDecrAKM2.setObjectName("lblBlockAddressDecrAKM2")
        self.txtBlockAddressDecrAKM2 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM2)
        self.txtBlockAddressDecrAKM2.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecrAKM2.setFont(font)
        self.txtBlockAddressDecrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecrAKM2.setObjectName("txtBlockAddressDecrAKM2")
        self.btnDecrementValueAKM2 = QtWidgets.QPushButton(self.fmValueBlockDecrAKM2)
        self.btnDecrementValueAKM2.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValueAKM2.setFont(font)
        self.btnDecrementValueAKM2.setObjectName("btnDecrementValueAKM2")
        self.lblDecrementValueAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblDecrementValueAKM2.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValueAKM2.setFont(font)
        self.lblDecrementValueAKM2.setObjectName("lblDecrementValueAKM2")
        self.txtDecrementValueAKM2 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM2)
        self.txtDecrementValueAKM2.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValueAKM2.setFont(font)
        self.txtDecrementValueAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValueAKM2.setReadOnly(False)
        self.txtDecrementValueAKM2.setObjectName("txtDecrementValueAKM2")
        self.lblSectorAddressDecrAKM2 = QtWidgets.QLabel(self.fmValueBlockDecrAKM2)
        self.lblSectorAddressDecrAKM2.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressDecrAKM2.setFont(font)
        self.lblSectorAddressDecrAKM2.setObjectName("lblSectorAddressDecrAKM2")
        self.txtSectorAddressDecrAKM2 = QtWidgets.QLineEdit(self.fmValueBlockDecrAKM2)
        self.txtSectorAddressDecrAKM2.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressDecrAKM2.setFont(font)
        self.txtSectorAddressDecrAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressDecrAKM2.setObjectName("txtSectorAddressDecrAKM2")
        self.fmValueBlockDecrPK = QtWidgets.QFrame(self.tbValueBlockInSDecr)
        self.fmValueBlockDecrPK.setGeometry(QtCore.QRect(306, 134, 281, 120))
        self.fmValueBlockDecrPK.setAutoFillBackground(True)
        self.fmValueBlockDecrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockDecrPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockDecrPK.setObjectName("fmValueBlockDecrPK")
        self.lblHeaderVBISDecrPK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblHeaderVBISDecrPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBISDecrPK.setFont(font)
        self.lblHeaderVBISDecrPK.setAutoFillBackground(False)
        self.lblHeaderVBISDecrPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBISDecrPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBISDecrPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBISDecrPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBISDecrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBISDecrPK.setObjectName("lblHeaderVBISDecrPK")
        self.lblBlockAddressDecrPK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblBlockAddressDecrPK.setGeometry(QtCore.QRect(15, 89, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressDecrPK.setFont(font)
        self.lblBlockAddressDecrPK.setObjectName("lblBlockAddressDecrPK")
        self.txtBlockAddressDecrPK = QtWidgets.QLineEdit(self.fmValueBlockDecrPK)
        self.txtBlockAddressDecrPK.setGeometry(QtCore.QRect(125, 81, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtBlockAddressDecrPK.setFont(font)
        self.txtBlockAddressDecrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBlockAddressDecrPK.setObjectName("txtBlockAddressDecrPK")
        self.btnDecrementValuePK = QtWidgets.QPushButton(self.fmValueBlockDecrPK)
        self.btnDecrementValuePK.setGeometry(QtCore.QRect(180, 50, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrementValuePK.setFont(font)
        self.btnDecrementValuePK.setObjectName("btnDecrementValuePK")
        self.lblDecrementValuePK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblDecrementValuePK.setGeometry(QtCore.QRect(15, 30, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblDecrementValuePK.setFont(font)
        self.lblDecrementValuePK.setObjectName("lblDecrementValuePK")
        self.txtDecrementValuePK = QtWidgets.QLineEdit(self.fmValueBlockDecrPK)
        self.txtDecrementValuePK.setGeometry(QtCore.QRect(125, 28, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtDecrementValuePK.setFont(font)
        self.txtDecrementValuePK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecrementValuePK.setReadOnly(False)
        self.txtDecrementValuePK.setObjectName("txtDecrementValuePK")
        self.lblSectorAddressDecrPK = QtWidgets.QLabel(self.fmValueBlockDecrPK)
        self.lblSectorAddressDecrPK.setGeometry(QtCore.QRect(15, 58, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressDecrPK.setFont(font)
        self.lblSectorAddressDecrPK.setObjectName("lblSectorAddressDecrPK")
        self.txtSectorAddressDecrPK = QtWidgets.QLineEdit(self.fmValueBlockDecrPK)
        self.txtSectorAddressDecrPK.setGeometry(QtCore.QRect(125, 50, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressDecrPK.setFont(font)
        self.txtSectorAddressDecrPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressDecrPK.setObjectName("txtSectorAddressDecrPK")
        self.tabValueBlockInSIncrDecr.addTab(self.tbValueBlockInSDecr, "")
        self.lblFnValue = QtWidgets.QLabel(ValueBlockInSectorIncrDecr)
        self.lblFnValue.setGeometry(QtCore.QRect(115, 343, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnError = QtWidgets.QLabel(ValueBlockInSectorIncrDecr)
        self.lblFnError.setGeometry(QtCore.QRect(5, 343, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")
        self.lblFnExplain = QtWidgets.QLabel(ValueBlockInSectorIncrDecr)
        self.lblFnExplain.setGeometry(QtCore.QRect(196, 343, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")

        self.retranslateUi(ValueBlockInSectorIncrDecr)
        self.tabValueBlockInSIncrDecr.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ValueBlockInSectorIncrDecr)
        ValueBlockInSectorIncrDecr.setTabOrder(self.tabValueBlockInSIncrDecr, self.txtIncrementValue)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtIncrementValue, self.txtSectorAddressIncr)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressIncr, self.txtBlockAddressIncr)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressIncr, self.btnIncrementValue)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnIncrementValue, self.txtIncrementValueAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtIncrementValueAKM1, self.txtSectorAddressIncrAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressIncrAKM1, self.txtBlockAddressIncrAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressIncrAKM1, self.btnIncrementValueAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnIncrementValueAKM1, self.txtIncrementValueAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtIncrementValueAKM2, self.txtSectorAddressIncrAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressIncrAKM2, self.txtBlockAddressIncrAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressIncrAKM2, self.btnIncrementValueAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnIncrementValueAKM2, self.txtIncrementValuePK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtIncrementValuePK, self.txtSectorAddressIncrPK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressIncrPK, self.btnIncrementValuePK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnIncrementValuePK, self.txtDecrementValue)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtDecrementValue, self.txtSectorAddressDecr)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressDecr, self.txtBlockAddressDecr)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressDecr, self.btnDecrementValue)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnDecrementValue, self.txtDecrementValueAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtDecrementValueAKM1, self.txtSectorAddressDecrAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressDecrAKM1, self.txtBlockAddressDecrAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressDecrAKM1, self.btnDecrementValueAKM1)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnDecrementValueAKM1, self.txtDecrementValueAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtDecrementValueAKM2, self.txtSectorAddressDecrAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressDecrAKM2, self.txtBlockAddressDecrAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressDecrAKM2, self.btnDecrementValueAKM2)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnDecrementValueAKM2, self.txtDecrementValuePK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtDecrementValuePK, self.txtSectorAddressDecrPK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtSectorAddressDecrPK, self.txtBlockAddressDecrPK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.txtBlockAddressDecrPK, self.btnDecrementValuePK)
        ValueBlockInSectorIncrDecr.setTabOrder(self.btnDecrementValuePK, self.rbAUTH1A)
        ValueBlockInSectorIncrDecr.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        ValueBlockInSectorIncrDecr.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        ValueBlockInSectorIncrDecr.setTabOrder(self.cboKeyIndex, self.txtBlockAddressIncrPK)

    def retranslateUi(self, ValueBlockInSectorIncrDecr):
        _translate = QtCore.QCoreApplication.translate
        ValueBlockInSectorIncrDecr.setWindowTitle(_translate("ValueBlockInSectorIncrDecr", "Dialog"))
        self.rbAUTH1A.setText(_translate("ValueBlockInSectorIncrDecr", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("ValueBlockInSectorIncrDecr", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("ValueBlockInSectorIncrDecr", "Key Index"))
        self.lblPKKeys.setText(_translate("ValueBlockInSectorIncrDecr", "PK Key"))
        self.lblHeaderVBISIncr.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR INCREMENT"))
        self.lblBlockAddress.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnIncrementValue.setText(_translate("ValueBlockInSectorIncrDecr", "INCREMENT"))
        self.lblIncrementValue.setText(_translate("ValueBlockInSectorIncrDecr", "Increment Value"))
        self.lblSectorAddressIncr.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.lblHeaderVBISIncrAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR INCREMENT AKM1"))
        self.lblBlockAddressAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnIncrementValueAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "INCREMENT"))
        self.lblIncrementValueAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "Increment Value"))
        self.lblSectorAddressIncrAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.lblHeaderVBISIncrAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR INCREMENT AKM2"))
        self.lblBlockAddressAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnIncrementValueAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "INCREMENT"))
        self.lblIncrementValueAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "Increment Value"))
        self.lblSectorAddressIncrAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.lblHeaderVBISIncrPK.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR INCREMENT PK"))
        self.lblBlockAddressPK.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnIncrementValuePK.setText(_translate("ValueBlockInSectorIncrDecr", "INCREMENT"))
        self.lblIncrementValuePK.setText(_translate("ValueBlockInSectorIncrDecr", "Increment Value"))
        self.lblSectorAddressIncrPK.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.tabValueBlockInSIncrDecr.setTabText(self.tabValueBlockInSIncrDecr.indexOf(self.tbValueBlockInSIncr), _translate("ValueBlockInSectorIncrDecr", "ValueBlockInSector Increment"))
        self.lblHeaderVBISDecr.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR DECREMENT"))
        self.lblBlockAddressDecr.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnDecrementValue.setText(_translate("ValueBlockInSectorIncrDecr", "DECREMENT"))
        self.lblDecrementValue.setText(_translate("ValueBlockInSectorIncrDecr", "Decrement Value"))
        self.lblSectorAddressDecr.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.lblHeaderVBISDecrAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR DECREMENT AKM1"))
        self.lblBlockAddressDecrAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnDecrementValueAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "DECREMENT"))
        self.lblDecrementValueAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "Decrement Value"))
        self.lblSectorAddressDecrAKM1.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.lblHeaderVBISDecrAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR DECREMENT AKM2"))
        self.lblBlockAddressDecrAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnDecrementValueAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "DECREMENT"))
        self.lblDecrementValueAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "Decrement Value"))
        self.lblSectorAddressDecrAKM2.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.lblHeaderVBISDecrPK.setText(_translate("ValueBlockInSectorIncrDecr", "VALUE BLOCK IN SECTOR DECREMENT PK"))
        self.lblBlockAddressDecrPK.setText(_translate("ValueBlockInSectorIncrDecr", "Block Address"))
        self.btnDecrementValuePK.setText(_translate("ValueBlockInSectorIncrDecr", "DECREMENT"))
        self.lblDecrementValuePK.setText(_translate("ValueBlockInSectorIncrDecr", "Decrement Value"))
        self.lblSectorAddressDecrPK.setText(_translate("ValueBlockInSectorIncrDecr", "Sector Address"))
        self.tabValueBlockInSIncrDecr.setTabText(self.tabValueBlockInSIncrDecr.indexOf(self.tbValueBlockInSDecr), _translate("ValueBlockInSectorIncrDecr", "ValueBlockInSector Decrement"))
        self.lblFnError.setText(_translate("ValueBlockInSectorIncrDecr", "Function Error :"))

