# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ValueBlockInSectorReadWrite.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ValueBlockInSectorRW(object):
    def setupUi(self, ValueBlockInSectorRW):
        ValueBlockInSectorRW.setObjectName("ValueBlockInSectorRW")
        ValueBlockInSectorRW.resize(620, 380)
        self.pnlAuth = QtWidgets.QFrame(ValueBlockInSectorRW)
        self.pnlAuth.setGeometry(QtCore.QRect(0, 0, 620, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pnlAuth.setFont(font)
        self.pnlAuth.setAutoFillBackground(True)
        self.pnlAuth.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pnlAuth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pnlAuth.setObjectName("pnlAuth")
        self.rbAUTH1A = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1A.setGeometry(QtCore.QRect(13, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1A.setFont(font)
        self.rbAUTH1A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1A.setChecked(True)
        self.rbAUTH1A.setObjectName("rbAUTH1A")
        self.rbAUTH1B = QtWidgets.QRadioButton(self.pnlAuth)
        self.rbAUTH1B.setGeometry(QtCore.QRect(113, 10, 99, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rbAUTH1B.setFont(font)
        self.rbAUTH1B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rbAUTH1B.setChecked(False)
        self.rbAUTH1B.setObjectName("rbAUTH1B")
        self.lblKeyIndex = QtWidgets.QLabel(self.pnlAuth)
        self.lblKeyIndex.setGeometry(QtCore.QRect(204, 12, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblKeyIndex.setFont(font)
        self.lblKeyIndex.setObjectName("lblKeyIndex")
        self.cboKeyIndex = QtWidgets.QComboBox(self.pnlAuth)
        self.cboKeyIndex.setGeometry(QtCore.QRect(267, 10, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cboKeyIndex.setFont(font)
        self.cboKeyIndex.setAutoFillBackground(True)
        self.cboKeyIndex.setProperty("currentText", "")
        self.cboKeyIndex.setObjectName("cboKeyIndex")
        self.lblPKKeys = QtWidgets.QLabel(self.pnlAuth)
        self.lblPKKeys.setGeometry(QtCore.QRect(331, 12, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPKKeys.setFont(font)
        self.lblPKKeys.setObjectName("lblPKKeys")
        self.tabValueBlockInSReadWrite = QtWidgets.QTabWidget(ValueBlockInSectorRW)
        self.tabValueBlockInSReadWrite.setGeometry(QtCore.QRect(4, 45, 600, 290))
        self.tabValueBlockInSReadWrite.setObjectName("tabValueBlockInSReadWrite")
        self.tbValueBlockRead = QtWidgets.QWidget()
        self.tbValueBlockRead.setObjectName("tbValueBlockRead")
        self.fmValueBlockRead = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockRead.setGeometry(QtCore.QRect(9, 10, 281, 120))
        self.fmValueBlockRead.setAutoFillBackground(True)
        self.fmValueBlockRead.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockRead.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockRead.setObjectName("fmValueBlockRead")
        self.lblHeaderVBInSBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblHeaderVBInSBR.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBInSBR.setFont(font)
        self.lblHeaderVBInSBR.setAutoFillBackground(False)
        self.lblHeaderVBInSBR.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBInSBR.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBInSBR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBInSBR.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBInSBR.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBInSBR.setObjectName("lblHeaderVBInSBR")
        self.lblBlockAddressBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblBlockAddressBR.setGeometry(QtCore.QRect(13, 50, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBR.setFont(font)
        self.lblBlockAddressBR.setObjectName("lblBlockAddressBR")
        self.txtValueBlockAddressBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtValueBlockAddressBR.setGeometry(QtCore.QRect(105, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBR.setFont(font)
        self.txtValueBlockAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBR.setObjectName("txtValueBlockAddressBR")
        self.btnValueBlockRead = QtWidgets.QPushButton(self.fmValueBlockRead)
        self.btnValueBlockRead.setGeometry(QtCore.QRect(164, 26, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockRead.setFont(font)
        self.btnValueBlockRead.setObjectName("btnValueBlockRead")
        self.lblReadDataBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblReadDataBR.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBR.setFont(font)
        self.lblReadDataBR.setObjectName("lblReadDataBR")
        self.txtValueReadDataBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtValueReadDataBR.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBR.setFont(font)
        self.txtValueReadDataBR.setReadOnly(True)
        self.txtValueReadDataBR.setObjectName("txtValueReadDataBR")
        self.txtValueAddressBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtValueAddressBR.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBR.setFont(font)
        self.txtValueAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBR.setReadOnly(True)
        self.txtValueAddressBR.setObjectName("txtValueAddressBR")
        self.lblValueAddressBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblValueAddressBR.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBR.setFont(font)
        self.lblValueAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressBR.setWordWrap(True)
        self.lblValueAddressBR.setObjectName("lblValueAddressBR")
        self.lblSectorAddressBR = QtWidgets.QLabel(self.fmValueBlockRead)
        self.lblSectorAddressBR.setGeometry(QtCore.QRect(13, 27, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBR.setFont(font)
        self.lblSectorAddressBR.setObjectName("lblSectorAddressBR")
        self.txtSectorAddressBR = QtWidgets.QLineEdit(self.fmValueBlockRead)
        self.txtSectorAddressBR.setGeometry(QtCore.QRect(105, 27, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBR.setFont(font)
        self.txtSectorAddressBR.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBR.setObjectName("txtSectorAddressBR")
        self.fmValueBlockReadAKM1 = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockReadAKM1.setGeometry(QtCore.QRect(300, 10, 281, 120))
        self.fmValueBlockReadAKM1.setAutoFillBackground(True)
        self.fmValueBlockReadAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockReadAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockReadAKM1.setObjectName("fmValueBlockReadAKM1")
        self.lblHeaderVBInSBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblHeaderVBInSBRAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBInSBRAKM1.setFont(font)
        self.lblHeaderVBInSBRAKM1.setAutoFillBackground(False)
        self.lblHeaderVBInSBRAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBInSBRAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBInSBRAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBInSBRAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBInSBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBInSBRAKM1.setObjectName("lblHeaderVBInSBRAKM1")
        self.lblBlockAddressBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblBlockAddressBRAKM1.setGeometry(QtCore.QRect(13, 50, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRAKM1.setFont(font)
        self.lblBlockAddressBRAKM1.setObjectName("lblBlockAddressBRAKM1")
        self.txtValueBlockAddressBRAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtValueBlockAddressBRAKM1.setGeometry(QtCore.QRect(105, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBRAKM1.setFont(font)
        self.txtValueBlockAddressBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBRAKM1.setObjectName("txtValueBlockAddressBRAKM1")
        self.btnValueBlockReadAKM1 = QtWidgets.QPushButton(self.fmValueBlockReadAKM1)
        self.btnValueBlockReadAKM1.setGeometry(QtCore.QRect(164, 26, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockReadAKM1.setFont(font)
        self.btnValueBlockReadAKM1.setObjectName("btnValueBlockReadAKM1")
        self.lblReadDataBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblReadDataBRAKM1.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM1.setFont(font)
        self.lblReadDataBRAKM1.setObjectName("lblReadDataBRAKM1")
        self.txtValueReadDataBRAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtValueReadDataBRAKM1.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBRAKM1.setFont(font)
        self.txtValueReadDataBRAKM1.setReadOnly(True)
        self.txtValueReadDataBRAKM1.setObjectName("txtValueReadDataBRAKM1")
        self.txtValueAddressBRAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtValueAddressBRAKM1.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBRAKM1.setFont(font)
        self.txtValueAddressBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBRAKM1.setReadOnly(True)
        self.txtValueAddressBRAKM1.setObjectName("txtValueAddressBRAKM1")
        self.lblValueAddressBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblValueAddressBRAKM1.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBRAKM1.setFont(font)
        self.lblValueAddressBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressBRAKM1.setWordWrap(True)
        self.lblValueAddressBRAKM1.setObjectName("lblValueAddressBRAKM1")
        self.lblSectorAddressBRAKM1 = QtWidgets.QLabel(self.fmValueBlockReadAKM1)
        self.lblSectorAddressBRAKM1.setGeometry(QtCore.QRect(13, 27, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBRAKM1.setFont(font)
        self.lblSectorAddressBRAKM1.setObjectName("lblSectorAddressBRAKM1")
        self.txtSectorAddressBRAKM1 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM1)
        self.txtSectorAddressBRAKM1.setGeometry(QtCore.QRect(105, 27, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBRAKM1.setFont(font)
        self.txtSectorAddressBRAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBRAKM1.setObjectName("txtSectorAddressBRAKM1")
        self.fmValueBlockReadAKM2 = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockReadAKM2.setGeometry(QtCore.QRect(10, 134, 281, 120))
        self.fmValueBlockReadAKM2.setAutoFillBackground(True)
        self.fmValueBlockReadAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockReadAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockReadAKM2.setObjectName("fmValueBlockReadAKM2")
        self.lblHeaderVBInSBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblHeaderVBInSBRAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBInSBRAKM2.setFont(font)
        self.lblHeaderVBInSBRAKM2.setAutoFillBackground(False)
        self.lblHeaderVBInSBRAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBInSBRAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBInSBRAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBInSBRAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBInSBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBInSBRAKM2.setObjectName("lblHeaderVBInSBRAKM2")
        self.lblBlockAddressBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblBlockAddressBRAKM2.setGeometry(QtCore.QRect(13, 50, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRAKM2.setFont(font)
        self.lblBlockAddressBRAKM2.setObjectName("lblBlockAddressBRAKM2")
        self.txtValueBlockAddressBRAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtValueBlockAddressBRAKM2.setGeometry(QtCore.QRect(105, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBRAKM2.setFont(font)
        self.txtValueBlockAddressBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBRAKM2.setObjectName("txtValueBlockAddressBRAKM2")
        self.btnValueBlockReadAKM2 = QtWidgets.QPushButton(self.fmValueBlockReadAKM2)
        self.btnValueBlockReadAKM2.setGeometry(QtCore.QRect(164, 26, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockReadAKM2.setFont(font)
        self.btnValueBlockReadAKM2.setObjectName("btnValueBlockReadAKM2")
        self.lblReadDataBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblReadDataBRAKM2.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRAKM2.setFont(font)
        self.lblReadDataBRAKM2.setObjectName("lblReadDataBRAKM2")
        self.txtValueReadDataBRAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtValueReadDataBRAKM2.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBRAKM2.setFont(font)
        self.txtValueReadDataBRAKM2.setReadOnly(True)
        self.txtValueReadDataBRAKM2.setObjectName("txtValueReadDataBRAKM2")
        self.txtValueAddressBRAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtValueAddressBRAKM2.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBRAKM2.setFont(font)
        self.txtValueAddressBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBRAKM2.setReadOnly(True)
        self.txtValueAddressBRAKM2.setObjectName("txtValueAddressBRAKM2")
        self.lblValueAddressBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblValueAddressBRAKM2.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBRAKM2.setFont(font)
        self.lblValueAddressBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressBRAKM2.setWordWrap(True)
        self.lblValueAddressBRAKM2.setObjectName("lblValueAddressBRAKM2")
        self.lblSectorAddressBRAKM2 = QtWidgets.QLabel(self.fmValueBlockReadAKM2)
        self.lblSectorAddressBRAKM2.setGeometry(QtCore.QRect(13, 27, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBRAKM2.setFont(font)
        self.lblSectorAddressBRAKM2.setObjectName("lblSectorAddressBRAKM2")
        self.txtSectorAddressBRAKM2 = QtWidgets.QLineEdit(self.fmValueBlockReadAKM2)
        self.txtSectorAddressBRAKM2.setGeometry(QtCore.QRect(105, 27, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBRAKM2.setFont(font)
        self.txtSectorAddressBRAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBRAKM2.setObjectName("txtSectorAddressBRAKM2")
        self.fmValueBlockReadPK = QtWidgets.QFrame(self.tbValueBlockRead)
        self.fmValueBlockReadPK.setGeometry(QtCore.QRect(300, 134, 281, 120))
        self.fmValueBlockReadPK.setAutoFillBackground(True)
        self.fmValueBlockReadPK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockReadPK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockReadPK.setObjectName("fmValueBlockReadPK")
        self.lblHeaderVBInSBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblHeaderVBInSBRPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderVBInSBRPK.setFont(font)
        self.lblHeaderVBInSBRPK.setAutoFillBackground(False)
        self.lblHeaderVBInSBRPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderVBInSBRPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderVBInSBRPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderVBInSBRPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderVBInSBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderVBInSBRPK.setObjectName("lblHeaderVBInSBRPK")
        self.lblBlockAddressBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblBlockAddressBRPK.setGeometry(QtCore.QRect(13, 50, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBRPK.setFont(font)
        self.lblBlockAddressBRPK.setObjectName("lblBlockAddressBRPK")
        self.txtValueBlockAddressBRPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtValueBlockAddressBRPK.setGeometry(QtCore.QRect(105, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBRPK.setFont(font)
        self.txtValueBlockAddressBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBRPK.setObjectName("txtValueBlockAddressBRPK")
        self.btnValueBlockReadPK = QtWidgets.QPushButton(self.fmValueBlockReadPK)
        self.btnValueBlockReadPK.setGeometry(QtCore.QRect(164, 26, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockReadPK.setFont(font)
        self.btnValueBlockReadPK.setObjectName("btnValueBlockReadPK")
        self.lblReadDataBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblReadDataBRPK.setGeometry(QtCore.QRect(15, 73, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblReadDataBRPK.setFont(font)
        self.lblReadDataBRPK.setObjectName("lblReadDataBRPK")
        self.txtValueReadDataBRPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtValueReadDataBRPK.setGeometry(QtCore.QRect(14, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueReadDataBRPK.setFont(font)
        self.txtValueReadDataBRPK.setReadOnly(True)
        self.txtValueReadDataBRPK.setObjectName("txtValueReadDataBRPK")
        self.txtValueAddressBRPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtValueAddressBRPK.setGeometry(QtCore.QRect(222, 83, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBRPK.setFont(font)
        self.txtValueAddressBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBRPK.setReadOnly(True)
        self.txtValueAddressBRPK.setObjectName("txtValueAddressBRPK")
        self.lblValueAddressBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblValueAddressBRPK.setGeometry(QtCore.QRect(167, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBRPK.setFont(font)
        self.lblValueAddressBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblValueAddressBRPK.setWordWrap(True)
        self.lblValueAddressBRPK.setObjectName("lblValueAddressBRPK")
        self.lblSectorAddressBRPK = QtWidgets.QLabel(self.fmValueBlockReadPK)
        self.lblSectorAddressBRPK.setGeometry(QtCore.QRect(13, 27, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBRPK.setFont(font)
        self.lblSectorAddressBRPK.setObjectName("lblSectorAddressBRPK")
        self.txtSectorAddressBRPK = QtWidgets.QLineEdit(self.fmValueBlockReadPK)
        self.txtSectorAddressBRPK.setGeometry(QtCore.QRect(105, 27, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBRPK.setFont(font)
        self.txtSectorAddressBRPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBRPK.setObjectName("txtSectorAddressBRPK")
        self.tabValueBlockInSReadWrite.addTab(self.tbValueBlockRead, "")
        self.tbValueBlockWrite = QtWidgets.QWidget()
        self.tbValueBlockWrite.setObjectName("tbValueBlockWrite")
        self.fmValueBlockWrite = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWrite.setGeometry(QtCore.QRect(9, 10, 281, 120))
        self.fmValueBlockWrite.setAutoFillBackground(True)
        self.fmValueBlockWrite.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWrite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWrite.setObjectName("fmValueBlockWrite")
        self.lblHeaderBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblHeaderBW.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBW.setFont(font)
        self.lblHeaderBW.setAutoFillBackground(False)
        self.lblHeaderBW.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBW.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBW.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBW.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBW.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBW.setObjectName("lblHeaderBW")
        self.lblBlockAddressBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblBlockAddressBW.setGeometry(QtCore.QRect(17, 93, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBW.setFont(font)
        self.lblBlockAddressBW.setObjectName("lblBlockAddressBW")
        self.txtValueBlockAddressBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtValueBlockAddressBW.setGeometry(QtCore.QRect(110, 93, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBW.setFont(font)
        self.txtValueBlockAddressBW.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBW.setObjectName("txtValueBlockAddressBW")
        self.btnValueBlockWrite = QtWidgets.QPushButton(self.fmValueBlockWrite)
        self.btnValueBlockWrite.setGeometry(QtCore.QRect(166, 51, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWrite.setFont(font)
        self.btnValueBlockWrite.setObjectName("btnValueBlockWrite")
        self.lblEnterValueBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblEnterValueBW.setGeometry(QtCore.QRect(17, 28, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueBW.setFont(font)
        self.lblEnterValueBW.setObjectName("lblEnterValueBW")
        self.txtValueWriteDataBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtValueWriteDataBW.setGeometry(QtCore.QRect(110, 27, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBW.setFont(font)
        self.txtValueWriteDataBW.setReadOnly(False)
        self.txtValueWriteDataBW.setObjectName("txtValueWriteDataBW")
        self.lblValueAddressBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblValueAddressBW.setGeometry(QtCore.QRect(17, 71, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBW.setFont(font)
        self.lblValueAddressBW.setObjectName("lblValueAddressBW")
        self.txtValueAddressBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtValueAddressBW.setGeometry(QtCore.QRect(110, 71, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBW.setFont(font)
        self.txtValueAddressBW.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBW.setObjectName("txtValueAddressBW")
        self.txtSectorAddressBW = QtWidgets.QLineEdit(self.fmValueBlockWrite)
        self.txtSectorAddressBW.setGeometry(QtCore.QRect(110, 49, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBW.setFont(font)
        self.txtSectorAddressBW.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBW.setObjectName("txtSectorAddressBW")
        self.lblSectorAddressBW = QtWidgets.QLabel(self.fmValueBlockWrite)
        self.lblSectorAddressBW.setGeometry(QtCore.QRect(17, 49, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBW.setFont(font)
        self.lblSectorAddressBW.setObjectName("lblSectorAddressBW")
        self.fmValueBlockWriteAKM1 = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWriteAKM1.setGeometry(QtCore.QRect(300, 10, 281, 120))
        self.fmValueBlockWriteAKM1.setAutoFillBackground(True)
        self.fmValueBlockWriteAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWriteAKM1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWriteAKM1.setObjectName("fmValueBlockWriteAKM1")
        self.lblHeaderBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblHeaderBWAKM1.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM1.setFont(font)
        self.lblHeaderBWAKM1.setAutoFillBackground(False)
        self.lblHeaderBWAKM1.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM1.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM1.setObjectName("lblHeaderBWAKM1")
        self.lblBlockAddressBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblBlockAddressBWAKM1.setGeometry(QtCore.QRect(17, 93, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM1.setFont(font)
        self.lblBlockAddressBWAKM1.setObjectName("lblBlockAddressBWAKM1")
        self.txtValueBlockAddressBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtValueBlockAddressBWAKM1.setGeometry(QtCore.QRect(110, 93, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBWAKM1.setFont(font)
        self.txtValueBlockAddressBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBWAKM1.setObjectName("txtValueBlockAddressBWAKM1")
        self.btnValueBlockWriteAKM1 = QtWidgets.QPushButton(self.fmValueBlockWriteAKM1)
        self.btnValueBlockWriteAKM1.setGeometry(QtCore.QRect(166, 51, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWriteAKM1.setFont(font)
        self.btnValueBlockWriteAKM1.setObjectName("btnValueBlockWriteAKM1")
        self.lblEnterValueBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblEnterValueBWAKM1.setGeometry(QtCore.QRect(17, 28, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueBWAKM1.setFont(font)
        self.lblEnterValueBWAKM1.setObjectName("lblEnterValueBWAKM1")
        self.txtValueWriteDataBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtValueWriteDataBWAKM1.setGeometry(QtCore.QRect(110, 27, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBWAKM1.setFont(font)
        self.txtValueWriteDataBWAKM1.setReadOnly(False)
        self.txtValueWriteDataBWAKM1.setObjectName("txtValueWriteDataBWAKM1")
        self.lblValueAddressBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblValueAddressBWAKM1.setGeometry(QtCore.QRect(17, 71, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBWAKM1.setFont(font)
        self.lblValueAddressBWAKM1.setObjectName("lblValueAddressBWAKM1")
        self.txtValueAddressBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtValueAddressBWAKM1.setGeometry(QtCore.QRect(110, 71, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBWAKM1.setFont(font)
        self.txtValueAddressBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBWAKM1.setObjectName("txtValueAddressBWAKM1")
        self.txtSectorAddressBWAKM1 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM1)
        self.txtSectorAddressBWAKM1.setGeometry(QtCore.QRect(110, 49, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBWAKM1.setFont(font)
        self.txtSectorAddressBWAKM1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBWAKM1.setObjectName("txtSectorAddressBWAKM1")
        self.lblSectorAddressBWAKM1 = QtWidgets.QLabel(self.fmValueBlockWriteAKM1)
        self.lblSectorAddressBWAKM1.setGeometry(QtCore.QRect(17, 49, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBWAKM1.setFont(font)
        self.lblSectorAddressBWAKM1.setObjectName("lblSectorAddressBWAKM1")
        self.fmValueBlockWriteAKM2 = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWriteAKM2.setGeometry(QtCore.QRect(8, 134, 281, 120))
        self.fmValueBlockWriteAKM2.setAutoFillBackground(True)
        self.fmValueBlockWriteAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWriteAKM2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWriteAKM2.setObjectName("fmValueBlockWriteAKM2")
        self.lblHeaderBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblHeaderBWAKM2.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWAKM2.setFont(font)
        self.lblHeaderBWAKM2.setAutoFillBackground(False)
        self.lblHeaderBWAKM2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWAKM2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWAKM2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWAKM2.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWAKM2.setObjectName("lblHeaderBWAKM2")
        self.lblBlockAddressBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblBlockAddressBWAKM2.setGeometry(QtCore.QRect(17, 93, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWAKM2.setFont(font)
        self.lblBlockAddressBWAKM2.setObjectName("lblBlockAddressBWAKM2")
        self.txtValueBlockAddressBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtValueBlockAddressBWAKM2.setGeometry(QtCore.QRect(110, 93, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBWAKM2.setFont(font)
        self.txtValueBlockAddressBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBWAKM2.setObjectName("txtValueBlockAddressBWAKM2")
        self.btnValueBlockWriteAKM2 = QtWidgets.QPushButton(self.fmValueBlockWriteAKM2)
        self.btnValueBlockWriteAKM2.setGeometry(QtCore.QRect(166, 51, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWriteAKM2.setFont(font)
        self.btnValueBlockWriteAKM2.setObjectName("btnValueBlockWriteAKM2")
        self.lblEnterValueBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblEnterValueBWAKM2.setGeometry(QtCore.QRect(17, 28, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueBWAKM2.setFont(font)
        self.lblEnterValueBWAKM2.setObjectName("lblEnterValueBWAKM2")
        self.txtValueWriteDataBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtValueWriteDataBWAKM2.setGeometry(QtCore.QRect(110, 27, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBWAKM2.setFont(font)
        self.txtValueWriteDataBWAKM2.setReadOnly(False)
        self.txtValueWriteDataBWAKM2.setObjectName("txtValueWriteDataBWAKM2")
        self.lblValueAddressBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblValueAddressBWAKM2.setGeometry(QtCore.QRect(17, 71, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBWAKM2.setFont(font)
        self.lblValueAddressBWAKM2.setObjectName("lblValueAddressBWAKM2")
        self.txtValueAddressBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtValueAddressBWAKM2.setGeometry(QtCore.QRect(110, 71, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBWAKM2.setFont(font)
        self.txtValueAddressBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBWAKM2.setObjectName("txtValueAddressBWAKM2")
        self.txtSectorAddressBWAKM2 = QtWidgets.QLineEdit(self.fmValueBlockWriteAKM2)
        self.txtSectorAddressBWAKM2.setGeometry(QtCore.QRect(110, 49, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBWAKM2.setFont(font)
        self.txtSectorAddressBWAKM2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBWAKM2.setObjectName("txtSectorAddressBWAKM2")
        self.lblSectorAddressBWAKM2 = QtWidgets.QLabel(self.fmValueBlockWriteAKM2)
        self.lblSectorAddressBWAKM2.setGeometry(QtCore.QRect(17, 49, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBWAKM2.setFont(font)
        self.lblSectorAddressBWAKM2.setObjectName("lblSectorAddressBWAKM2")
        self.fmValueBlockWritePK = QtWidgets.QFrame(self.tbValueBlockWrite)
        self.fmValueBlockWritePK.setGeometry(QtCore.QRect(300, 135, 281, 120))
        self.fmValueBlockWritePK.setAutoFillBackground(True)
        self.fmValueBlockWritePK.setFrameShape(QtWidgets.QFrame.Box)
        self.fmValueBlockWritePK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmValueBlockWritePK.setObjectName("fmValueBlockWritePK")
        self.lblHeaderBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblHeaderBWPK.setGeometry(QtCore.QRect(2, 2, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeaderBWPK.setFont(font)
        self.lblHeaderBWPK.setAutoFillBackground(False)
        self.lblHeaderBWPK.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.lblHeaderBWPK.setFrameShape(QtWidgets.QFrame.Box)
        self.lblHeaderBWPK.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblHeaderBWPK.setTextFormat(QtCore.Qt.AutoText)
        self.lblHeaderBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderBWPK.setObjectName("lblHeaderBWPK")
        self.lblBlockAddressBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblBlockAddressBWPK.setGeometry(QtCore.QRect(17, 93, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblBlockAddressBWPK.setFont(font)
        self.lblBlockAddressBWPK.setObjectName("lblBlockAddressBWPK")
        self.txtValueBlockAddressBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtValueBlockAddressBWPK.setGeometry(QtCore.QRect(110, 93, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueBlockAddressBWPK.setFont(font)
        self.txtValueBlockAddressBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueBlockAddressBWPK.setObjectName("txtValueBlockAddressBWPK")
        self.btnValueBlockWritePK = QtWidgets.QPushButton(self.fmValueBlockWritePK)
        self.btnValueBlockWritePK.setGeometry(QtCore.QRect(166, 51, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnValueBlockWritePK.setFont(font)
        self.btnValueBlockWritePK.setObjectName("btnValueBlockWritePK")
        self.lblEnterValueBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblEnterValueBWPK.setGeometry(QtCore.QRect(17, 28, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblEnterValueBWPK.setFont(font)
        self.lblEnterValueBWPK.setObjectName("lblEnterValueBWPK")
        self.txtValueWriteDataBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtValueWriteDataBWPK.setGeometry(QtCore.QRect(110, 27, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.txtValueWriteDataBWPK.setFont(font)
        self.txtValueWriteDataBWPK.setReadOnly(False)
        self.txtValueWriteDataBWPK.setObjectName("txtValueWriteDataBWPK")
        self.lblValueAddressBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblValueAddressBWPK.setGeometry(QtCore.QRect(17, 71, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblValueAddressBWPK.setFont(font)
        self.lblValueAddressBWPK.setObjectName("lblValueAddressBWPK")
        self.txtValueAddressBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtValueAddressBWPK.setGeometry(QtCore.QRect(110, 71, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueAddressBWPK.setFont(font)
        self.txtValueAddressBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtValueAddressBWPK.setObjectName("txtValueAddressBWPK")
        self.txtSectorAddressBWPK = QtWidgets.QLineEdit(self.fmValueBlockWritePK)
        self.txtSectorAddressBWPK.setGeometry(QtCore.QRect(110, 49, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtSectorAddressBWPK.setFont(font)
        self.txtSectorAddressBWPK.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSectorAddressBWPK.setObjectName("txtSectorAddressBWPK")
        self.lblSectorAddressBWPK = QtWidgets.QLabel(self.fmValueBlockWritePK)
        self.lblSectorAddressBWPK.setGeometry(QtCore.QRect(17, 49, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblSectorAddressBWPK.setFont(font)
        self.lblSectorAddressBWPK.setObjectName("lblSectorAddressBWPK")
        self.tabValueBlockInSReadWrite.addTab(self.tbValueBlockWrite, "")
        self.lblFnValue = QtWidgets.QLabel(ValueBlockInSectorRW)
        self.lblFnValue.setGeometry(QtCore.QRect(113, 340, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnValue.setFont(font)
        self.lblFnValue.setAutoFillBackground(False)
        self.lblFnValue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnValue.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnValue.setText("")
        self.lblFnValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnValue.setObjectName("lblFnValue")
        self.lblFnExplain = QtWidgets.QLabel(ValueBlockInSectorRW)
        self.lblFnExplain.setGeometry(QtCore.QRect(194, 340, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnExplain.setFont(font)
        self.lblFnExplain.setAutoFillBackground(False)
        self.lblFnExplain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnExplain.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnExplain.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnExplain.setText("")
        self.lblFnExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnExplain.setObjectName("lblFnExplain")
        self.lblFnError = QtWidgets.QLabel(ValueBlockInSectorRW)
        self.lblFnError.setGeometry(QtCore.QRect(3, 340, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lblFnError.setFont(font)
        self.lblFnError.setAutoFillBackground(False)
        self.lblFnError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblFnError.setFrameShape(QtWidgets.QFrame.Box)
        self.lblFnError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblFnError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFnError.setObjectName("lblFnError")

        self.retranslateUi(ValueBlockInSectorRW)
        self.tabValueBlockInSReadWrite.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ValueBlockInSectorRW)
        ValueBlockInSectorRW.setTabOrder(self.tabValueBlockInSReadWrite, self.txtSectorAddressBR)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBR, self.txtValueBlockAddressBR)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBR, self.btnValueBlockRead)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockRead, self.txtSectorAddressBRAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBRAKM1, self.txtValueBlockAddressBRAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBRAKM1, self.btnValueBlockReadAKM1)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockReadAKM1, self.txtSectorAddressBRAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBRAKM2, self.txtValueBlockAddressBRAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBRAKM2, self.btnValueBlockReadAKM2)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockReadAKM2, self.txtSectorAddressBRPK)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBRPK, self.txtValueBlockAddressBRPK)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBRPK, self.btnValueBlockReadPK)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockReadPK, self.txtValueWriteDataBW)
        ValueBlockInSectorRW.setTabOrder(self.txtValueWriteDataBW, self.txtSectorAddressBW)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBW, self.txtValueAddressBW)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBW, self.txtValueBlockAddressBW)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBW, self.btnValueBlockWrite)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockWrite, self.txtValueWriteDataBWAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtValueWriteDataBWAKM1, self.txtSectorAddressBWAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBWAKM1, self.txtValueAddressBWAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBWAKM1, self.txtValueBlockAddressBWAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBWAKM1, self.txtValueWriteDataBWAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtValueWriteDataBWAKM2, self.txtSectorAddressBWAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBWAKM2, self.txtValueAddressBWAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBWAKM2, self.txtValueBlockAddressBWAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBWAKM2, self.btnValueBlockWriteAKM2)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockWriteAKM2, self.txtValueWriteDataBWPK)
        ValueBlockInSectorRW.setTabOrder(self.txtValueWriteDataBWPK, self.txtSectorAddressBWPK)
        ValueBlockInSectorRW.setTabOrder(self.txtSectorAddressBWPK, self.txtValueAddressBWPK)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBWPK, self.txtValueBlockAddressBWPK)
        ValueBlockInSectorRW.setTabOrder(self.txtValueBlockAddressBWPK, self.btnValueBlockWritePK)
        ValueBlockInSectorRW.setTabOrder(self.btnValueBlockWritePK, self.rbAUTH1A)
        ValueBlockInSectorRW.setTabOrder(self.rbAUTH1A, self.rbAUTH1B)
        ValueBlockInSectorRW.setTabOrder(self.rbAUTH1B, self.cboKeyIndex)
        ValueBlockInSectorRW.setTabOrder(self.cboKeyIndex, self.txtValueReadDataBR)
        ValueBlockInSectorRW.setTabOrder(self.txtValueReadDataBR, self.txtValueAddressBR)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBR, self.txtValueReadDataBRAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtValueReadDataBRAKM1, self.txtValueAddressBRAKM1)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBRAKM1, self.txtValueReadDataBRAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtValueReadDataBRAKM2, self.txtValueAddressBRAKM2)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBRAKM2, self.txtValueReadDataBRPK)
        ValueBlockInSectorRW.setTabOrder(self.txtValueReadDataBRPK, self.txtValueAddressBRPK)
        ValueBlockInSectorRW.setTabOrder(self.txtValueAddressBRPK, self.btnValueBlockWriteAKM1)

    def retranslateUi(self, ValueBlockInSectorRW):
        _translate = QtCore.QCoreApplication.translate
        ValueBlockInSectorRW.setWindowTitle(_translate("ValueBlockInSectorRW", "Dialog"))
        self.rbAUTH1A.setText(_translate("ValueBlockInSectorRW", "AUTH 1A"))
        self.rbAUTH1B.setText(_translate("ValueBlockInSectorRW", "AUTH 1B"))
        self.lblKeyIndex.setText(_translate("ValueBlockInSectorRW", "Key Index"))
        self.lblPKKeys.setText(_translate("ValueBlockInSectorRW", "PK Key"))
        self.lblHeaderVBInSBR.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR READ"))
        self.lblBlockAddressBR.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockRead.setText(_translate("ValueBlockInSectorRW", "READ"))
        self.lblReadDataBR.setText(_translate("ValueBlockInSectorRW", "Read Value"))
        self.lblValueAddressBR.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBR.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.lblHeaderVBInSBRAKM1.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR READ AKM1"))
        self.lblBlockAddressBRAKM1.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockReadAKM1.setText(_translate("ValueBlockInSectorRW", "READ"))
        self.lblReadDataBRAKM1.setText(_translate("ValueBlockInSectorRW", "Read Value"))
        self.lblValueAddressBRAKM1.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBRAKM1.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.lblHeaderVBInSBRAKM2.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR READ AKM2"))
        self.lblBlockAddressBRAKM2.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockReadAKM2.setText(_translate("ValueBlockInSectorRW", "READ"))
        self.lblReadDataBRAKM2.setText(_translate("ValueBlockInSectorRW", "Read Value"))
        self.lblValueAddressBRAKM2.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBRAKM2.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.lblHeaderVBInSBRPK.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR READ PK"))
        self.lblBlockAddressBRPK.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockReadPK.setText(_translate("ValueBlockInSectorRW", "READ"))
        self.lblReadDataBRPK.setText(_translate("ValueBlockInSectorRW", "Read Value"))
        self.lblValueAddressBRPK.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBRPK.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.tabValueBlockInSReadWrite.setTabText(self.tabValueBlockInSReadWrite.indexOf(self.tbValueBlockRead), _translate("ValueBlockInSectorRW", "ValueBlockInSector Read"))
        self.lblHeaderBW.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR WRITE"))
        self.lblBlockAddressBW.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockWrite.setText(_translate("ValueBlockInSectorRW", "WRITE"))
        self.lblEnterValueBW.setText(_translate("ValueBlockInSectorRW", "Enter Value"))
        self.lblValueAddressBW.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBW.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.lblHeaderBWAKM1.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR WRITE AKM1"))
        self.lblBlockAddressBWAKM1.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockWriteAKM1.setText(_translate("ValueBlockInSectorRW", "WRITE"))
        self.lblEnterValueBWAKM1.setText(_translate("ValueBlockInSectorRW", "Enter Value"))
        self.lblValueAddressBWAKM1.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBWAKM1.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.lblHeaderBWAKM2.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR WRITE AKM2"))
        self.lblBlockAddressBWAKM2.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockWriteAKM2.setText(_translate("ValueBlockInSectorRW", "WRITE"))
        self.lblEnterValueBWAKM2.setText(_translate("ValueBlockInSectorRW", "Enter Value"))
        self.lblValueAddressBWAKM2.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBWAKM2.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.lblHeaderBWPK.setText(_translate("ValueBlockInSectorRW", "VALUE BLOCK IN SECTOR WRITE PK"))
        self.lblBlockAddressBWPK.setText(_translate("ValueBlockInSectorRW", "Block Address"))
        self.btnValueBlockWritePK.setText(_translate("ValueBlockInSectorRW", "WRITE"))
        self.lblEnterValueBWPK.setText(_translate("ValueBlockInSectorRW", "Enter Value"))
        self.lblValueAddressBWPK.setText(_translate("ValueBlockInSectorRW", "Value Address"))
        self.lblSectorAddressBWPK.setText(_translate("ValueBlockInSectorRW", "Sector Address"))
        self.tabValueBlockInSReadWrite.setTabText(self.tabValueBlockInSReadWrite.indexOf(self.tbValueBlockWrite), _translate("ValueBlockInSectorRW", "ValueBlockInSector Write"))
        self.lblFnError.setText(_translate("ValueBlockInSectorRW", "Function Error :"))

